/**
 * The fifteen platform roles, and the permission matcher.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

export const ROLES = [
  'founder',
  'hqExecutive',
  'backOfficeStaff',
  'coordinator',
  'vendor',
  'landlord',
  'tenant',
  'airbnbHost',
  'hotelManager',
  'resortManager',
  'rentalCarCompany',
  'driver',
  'rider',
  'advertiser',
  'publicUser',
] as const;

export type Role = (typeof ROLES)[number];

export function isRole(value: string): value is Role {
  return (ROLES as readonly string[]).includes(value);
}

/**
 * Mirrors the server's matcher, including `*:*`, `resource:*`, `*:action`,
 * and `read` implying `readOwn`. Used by the optional client-side guard —
 * never as a security boundary.
 */
export function can(grants: readonly string[], required: string): boolean {
  if (grants.includes('*:*') || grants.includes(required)) return true;
  const [resource, action] = required.split(':');
  if (grants.includes(`${resource}:*`) || grants.includes(`*:${action}`)) return true;
  const broader = action === 'readOwn' ? 'read' : action === 'updateOwn' ? 'update' : null;
  if (!broader) return false;
  return (
    grants.includes(`${resource}:${broader}`) ||
    grants.includes(`${resource}:*`) ||
    grants.includes(`*:${broader}`)
  );
}
