/**
 * The five HQ zones and the three ad-serving zones.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

export const HQ_ZONES = [
  'FOUNDER_COMMAND_CENTER',
  'HQ_EXECUTIVE',
  'BACK_OFFICE',
  'MEMBER_PORTAL',
  'PUBLIC_PORTAL',
] as const;

export type HQZone = (typeof HQ_ZONES)[number];

export const AD_ZONES = ['PUBLIC_PORTAL', 'MEMBER_PORTAL', 'USUSU_PORTAL'] as const;
export type AdZone = (typeof AD_ZONES)[number];

export interface HQZoneInfo {
  code: string;
  key: HQZone;
  label: string;
  purpose: string;
}

export const HQ_ZONE_INFO: Record<HQZone, HQZoneInfo> = {
  FOUNDER_COMMAND_CENTER: {
    code: 'A',
    key: 'FOUNDER_COMMAND_CENTER',
    label: "Founder Command Center",
    purpose: "Constitutional layer. Writes rules, regulations and policy; approves system-wide change; owns ad pricing and rotation policy; oversees every region and service.",
  },
  HQ_EXECUTIVE: {
    code: 'B',
    key: 'HQ_EXECUTIVE',
    label: "HQ Executive Layer",
    purpose: "Sees the whole institution and steers it: high-level dashboards, KPIs, analytics and system health. Reads into Back Office, Member Portal and public metrics.",
  },
  BACK_OFFICE: {
    code: 'C',
    key: 'BACK_OFFICE',
    label: "Back Office (HR & Staff)",
    purpose: "Operational engine room. Owns coordinator, vendor and staff records, Ususu driver verification, and commercial-client onboarding for Airbnb hosts, hotels, resorts and rental car companies.",
  },
  MEMBER_PORTAL: {
    code: 'D',
    key: 'MEMBER_PORTAL',
    label: "Member Portal",
    purpose: "Where members live: their own profile, their performance, residency, rent, compliance and engagement history.",
  },
  PUBLIC_PORTAL: {
    code: 'E',
    key: 'PUBLIC_PORTAL',
    label: "Public Portal",
    purpose: "The face of the consortium: website stats, traffic analytics, conversion metrics, public content, and ad placement with rotation.",
  },
};

export function isHQZone(value: string): value is HQZone {
  return (HQ_ZONES as readonly string[]).includes(value);
}
