/**
 * Generates the typed surface of the SDK from `backend/docs/openapi.json`.
 *
 *   npm run generate
 *
 * Emits: src/types/index.ts, src/types/roles.ts, src/types/zones.ts,
 *        src/modules/*.ts, src/modules/index.ts
 *
 * Everything here is derived. The hand-written half of the SDK is the runtime —
 * clients, envelope, errors, pagination — which is the part that encodes
 * judgement. The 179 operations and 77 schemas are mechanical, and mechanical
 * things should be generated so they cannot drift from the server.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const SPEC = resolve(process.cwd(), '../backend/docs/openapi.json');
const SRC = resolve(process.cwd(), 'src');

interface Op {
  operationId: string;
  summary?: string;
  description?: string;
  tags: string[];
  'x-zone': string | null;
  'x-roles': string[];
  'x-permissions': string[];
  'x-ownership': 'none' | 'scoped' | 'self';
  security?: unknown[];
  parameters?: { name: string; in: string; required?: boolean; schema?: JsonSchema }[];
  requestBody?: { required?: boolean; content: Record<string, { schema: { $ref?: string } }> };
  responses: Record<string, { content?: Record<string, { schema?: JsonSchema }> }>;
}

type JsonSchema = Record<string, any>;

const spec = JSON.parse(readFileSync(SPEC, 'utf8')) as {
  paths: Record<string, Record<string, Op>>;
  components: { schemas: Record<string, JsonSchema> };
  'x-hq-zones': { code: string; key: string; label: string; purpose: string }[];
  'x-roles-catalogue': string[];
};

const banner = (what: string): string =>
  `/**\n * ${what}\n *\n * GENERATED by \`npm run generate\` from backend/docs/openapi.json.\n * Do not edit — change the API, regenerate.\n */\n\n`;

function write(relative: string, contents: string): void {
  const out = resolve(SRC, relative);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, contents, 'utf8');
}

// ─────────────────────────────────────────────────────────────────────────────
// Schema → TypeScript
// ─────────────────────────────────────────────────────────────────────────────

type Mode = 'response' | 'request';

/** Strip `writeOnly` from responses and `readOnly` from requests. */
function visible(prop: JsonSchema, mode: Mode): boolean {
  if (mode === 'response' && prop.writeOnly === true) return false;
  if (mode === 'request' && prop.readOnly === true) return false;
  return true;
}

/**
 * Two component schemas collide with types the hand-written runtime owns.
 * `PageMeta` is identical, so the runtime's wins and the generated one is
 * skipped. `HQZone` is *not* identical — the schema describes a zone object
 * while `types/zones.ts` exports the union of zone keys — so it is renamed
 * rather than dropped.
 */
const SKIP_SCHEMAS = new Set(['PageMeta']);
const RENAME_SCHEMAS: Record<string, string> = { HQZone: 'HQZoneDescriptor' };

function refName(ref: string): string {
  const raw = ref.replace('#/components/schemas/', '');
  if (raw === 'PageMeta') return 'PageMeta';
  return RENAME_SCHEMAS[raw] ?? raw;
}

/** Which schemas get an `Input` variant. Computed before rendering. */
const inputVariants = new Set<string>();

function tsName(name: string, mode: Mode): string {
  if (mode !== 'request') return name;
  return inputVariants.has(name) ? `${name}Input` : name;
}

function literal(value: unknown): string {
  return typeof value === 'string' ? JSON.stringify(value) : String(value);
}

function renderSchema(schema: JsonSchema | undefined, mode: Mode, depth = 0): string {
  if (!schema) return 'unknown';
  if (schema.$ref) return tsName(refName(schema.$ref), mode);

  if (schema.const !== undefined) return literal(schema.const);
  if (Array.isArray(schema.enum)) {
    return schema.enum.map(literal).join(' | ') || 'never';
  }

  if (Array.isArray(schema.allOf)) {
    const parts = schema.allOf.map((s: JsonSchema) => renderSchema(s, mode, depth));
    return parts.length === 1 ? parts[0]! : `(${parts.join(' & ')})`;
  }
  if (Array.isArray(schema.oneOf)) {
    return schema.oneOf.map((s: JsonSchema) => renderSchema(s, mode, depth)).join(' | ');
  }
  if (Array.isArray(schema.anyOf)) {
    return schema.anyOf.map((s: JsonSchema) => renderSchema(s, mode, depth)).join(' | ');
  }

  const nullable = schema.nullable === true ? ' | null' : '';

  switch (schema.type) {
    case 'string':
      return `string${nullable}`;
    case 'number':
    case 'integer':
      return `number${nullable}`;
    case 'boolean':
      return `boolean${nullable}`;
    case 'array':
      return `${renderSchema(schema.items, mode, depth)}[]${nullable}`;
    case 'object':
    default: {
      if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
        return `Record<string, ${renderSchema(schema.additionalProperties, mode, depth)}>${nullable}`;
      }
      const props = schema.properties as Record<string, JsonSchema> | undefined;
      if (!props) return `Record<string, unknown>${nullable}`;

      const required = new Set<string>((schema.required as string[]) ?? []);
      const pad = '  '.repeat(depth + 1);
      const lines: string[] = [];

      for (const [key, prop] of Object.entries(props)) {
        if (!visible(prop, mode)) continue;
        const optional = required.has(key) && visible(prop, mode) ? '' : '?';
        const doc = prop.description ? `${pad}/** ${String(prop.description).replace(/\*\//g, '*\\/')} */\n` : '';
        const safeKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
        lines.push(`${doc}${pad}${safeKey}${optional}: ${renderSchema(prop, mode, depth + 1)};`);
      }

      if (lines.length === 0) return `Record<string, never>${nullable}`;
      return `{\n${lines.join('\n')}\n${'  '.repeat(depth)}}${nullable}`;
    }
  }
}

/** Does a schema (following $refs) contain any writeOnly/readOnly field? */
function hasMode(schema: JsonSchema, kind: 'writeOnly' | 'readOnly', seen = new Set<string>()): boolean {
  if (!schema || typeof schema !== 'object') return false;
  if (schema.$ref) {
    const name = refName(schema.$ref);
    if (seen.has(name)) return false;
    seen.add(name);
    return hasMode(spec.components.schemas[name]!, kind, seen);
  }
  if (schema[kind] === true) return true;
  for (const part of (schema.allOf ?? []) as JsonSchema[]) if (hasMode(part, kind, seen)) return true;
  for (const prop of Object.values((schema.properties ?? {}) as Record<string, JsonSchema>)) {
    if (hasMode(prop, kind, seen)) return true;
  }
  if (schema.items && hasMode(schema.items as JsonSchema, kind, seen)) return true;
  return false;
}

function generateTypes(): { emittedInputs: Set<string> } {
  const schemas = spec.components.schemas;
  const emittedInputs = new Set<string>();
  const chunks: string[] = [];

  // First pass: decide which schemas need an Input variant, so a `$ref` in
  // request position resolves to a name that will actually exist.
  // A spec that already declares `XInput` has said what the request shape is more
  // precisely than stripping `readOnly` off `X` ever could. Deriving one anyway
  // emits the same name twice. The declaration wins.
  const declared = new Set(Object.keys(schemas).map((n) => RENAME_SCHEMAS[n] ?? n));
  for (const [name, schema] of Object.entries(schemas)) {
    if (SKIP_SCHEMAS.has(name)) continue;
    const resolved = RENAME_SCHEMAS[name] ?? name;
    if (declared.has(`${resolved}Input`)) continue;
    if (hasMode(schema, 'readOnly')) inputVariants.add(resolved);
  }

  chunks.push(banner('All OpenAPI component schemas as TypeScript types.'));
  chunks.push(
    `/**\n * Two variants exist wherever the API distinguishes them:\n *\n *   \`Landlord\`       — a response. \`writeOnly\` fields (ID numbers, payout\n *                     details, security notes) are absent, because the server\n *                     never returns them.\n *   \`LandlordInput\`  — a request. \`readOnly\` fields (verification status,\n *                     counters, timestamps) are absent, because the server\n *                     owns them.\n *\n * Where a schema has neither, only the plain name is emitted.\n */\n\n`,
  );

  const names = Object.keys(schemas).sort();

  chunks.push(
    `import type { PageMeta } from './envelope.js';\n\nexport type { PageMeta };\n\n`,
  );

  for (const rawName of names) {
    if (SKIP_SCHEMAS.has(rawName)) continue;
    const name = RENAME_SCHEMAS[rawName] ?? rawName;
    const schema = schemas[rawName]!;
    const doc = schema.description
      ? `/** ${String(schema.description).replace(/\*\//g, '*\\/')} */\n`
      : '';
    // A schema whose every field is `writeOnly` has no response representation
    // at all — rendering it in response mode empties it to `Record<string,
    // never>`, and a client would be unable to build the body. That is not a
    // response type; render it as the request it is.
    const responseBody = renderSchema(schema, 'response');
    const requestBody = renderSchema(schema, 'request');
    const requestOnly =
      responseBody.startsWith('Record<string, never>') && !requestBody.startsWith('Record<string, never>');
    const body = requestOnly ? requestBody : responseBody;
    const keyword = body.startsWith('{') ? 'interface' : 'type';
    chunks.push(
      keyword === 'interface'
        ? `${doc}export interface ${name} ${body}\n\n`
        : `${doc}export type ${name} = ${body};\n\n`,
    );

    // An Input variant is only worth emitting when it differs — and never for a
    // schema already rendered as its request form.
    if (inputVariants.has(name) && !requestOnly) {
      const inputBody = renderSchema(schema, 'request');
      const inputKeyword = inputBody.startsWith('{') ? 'interface' : 'type';
      emittedInputs.add(name);
      chunks.push(
        inputKeyword === 'interface'
          ? `/** Request variant of \`${name}\` — server-controlled fields removed. */\nexport interface ${name}Input ${inputBody}\n\n`
          : `/** Request variant of \`${name}\`. */\nexport type ${name}Input = ${inputBody};\n\n`,
      );
    }
  }

  write('types/index.ts', chunks.join(''));
  return { emittedInputs };
}

// ─────────────────────────────────────────────────────────────────────────────
// Roles & zones
// ─────────────────────────────────────────────────────────────────────────────

function generateRolesAndZones(): void {
  const roles = spec['x-roles-catalogue'];
  const zones = spec['x-hq-zones'];

  write(
    'types/roles.ts',
    banner('The fifteen platform roles, and the permission matcher.') +
      `export const ROLES = [\n${roles.map((r) => `  '${r}',`).join('\n')}\n] as const;\n\n` +
      `export type Role = (typeof ROLES)[number];\n\n` +
      `export function isRole(value: string): value is Role {\n  return (ROLES as readonly string[]).includes(value);\n}\n\n` +
      `/**\n * Mirrors the server's matcher, including \`*:*\`, \`resource:*\`, \`*:action\`,\n * and \`read\` implying \`readOwn\`. Used by the optional client-side guard —\n * never as a security boundary.\n */\nexport function can(grants: readonly string[], required: string): boolean {\n` +
      `  if (grants.includes('*:*') || grants.includes(required)) return true;\n` +
      `  const [resource, action] = required.split(':');\n` +
      `  if (grants.includes(\`\${resource}:*\`) || grants.includes(\`*:\${action}\`)) return true;\n` +
      `  const broader = action === 'readOwn' ? 'read' : action === 'updateOwn' ? 'update' : null;\n` +
      `  if (!broader) return false;\n` +
      `  return (\n    grants.includes(\`\${resource}:\${broader}\`) ||\n    grants.includes(\`\${resource}:*\`) ||\n    grants.includes(\`*:\${broader}\`)\n  );\n}\n`,
  );

  write(
    'types/zones.ts',
    banner('The five HQ zones and the three ad-serving zones.') +
      `export const HQ_ZONES = [\n${zones.map((z) => `  '${z.key}',`).join('\n')}\n] as const;\n\n` +
      `export type HQZone = (typeof HQ_ZONES)[number];\n\n` +
      `export const AD_ZONES = ['PUBLIC_PORTAL', 'MEMBER_PORTAL', 'USUSU_PORTAL'] as const;\n` +
      `export type AdZone = (typeof AD_ZONES)[number];\n\n` +
      `export interface HQZoneInfo {\n  code: string;\n  key: HQZone;\n  label: string;\n  purpose: string;\n}\n\n` +
      `export const HQ_ZONE_INFO: Record<HQZone, HQZoneInfo> = {\n` +
      zones
        .map(
          (z) =>
            `  ${z.key}: {\n    code: '${z.code}',\n    key: '${z.key}',\n    label: ${JSON.stringify(z.label)},\n    purpose: ${JSON.stringify(z.purpose)},\n  },`,
        )
        .join('\n') +
      `\n};\n\nexport function isHQZone(value: string): value is HQZone {\n  return (HQ_ZONES as readonly string[]).includes(value);\n}\n`,
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Modules
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Which SDK module an operation belongs to. Mostly the OpenAPI tag, but three
 * tags are split so the package matches the requested file layout.
 */
function moduleFor(tag: string, path: string): string {
  if (tag === 'advertising') return path.startsWith('/ad-policy') ? 'adPolicy' : 'ads';
  if (tag === 'auth') {
    return path === '/auth/roles' || path === '/auth/resolve' || path.endsWith('/roles')
      ? 'rbac'
      : 'auth';
  }
  if (tag === 'platform') return 'blueprint';
  if (tag === 'publicPortal') return 'public';
  if (tag === 'backOfficeStaff') return 'staff';
  if (tag === 'property') return 'properties';
  if (tag === 'advertiser') return 'advertisers';
  // Profile tags are singular in the spec; the SDK files are plural.
  const plural: Record<string, string> = {
    founder: 'founders',
    hqExecutive: 'hqExecutives',
    coordinator: 'coordinators',
    vendor: 'vendors',
    landlord: 'landlords',
    tenant: 'tenants',
    driver: 'drivers',
    rider: 'riders',
    airbnbHost: 'airbnbHosts',
    hotel: 'hotels',
    resort: 'resorts',
    rentalCarCompany: 'rentalCarCompanies',
    hq: 'hq',
    // Operational surfaces. `maintenance` and `commercialClient` are named for
    // the collection they address, not for the tag.
    lease: 'leases',
    maintenance: 'maintenanceRequests',
    ride: 'rides',
    payment: 'payments',
    notification: 'notifications',
    commercialClient: 'commercialClients',
    payout: 'payoutBatches',
    document: 'documents',
    fac: 'fac',
    governance: 'governance',
  };
  return plural[tag] ?? tag;
}

/**
 * `public` is a reserved word, so it cannot be a bare import binding or a `const`
 * name. The file and the `api.public` key keep the requested name; only the
 * internal identifier differs.
 */
const RESERVED = new Set(['public', 'private', 'protected', 'package', 'static', 'delete', 'new']);

function identFor(moduleName: string): string {
  return RESERVED.has(moduleName) ? `${moduleName}Api` : moduleName;
}

function camel(input: string): string {
  return input
    .replace(/[{}]/g, '')
    .split(/[-_/]/)
    .filter(Boolean)
    .map((w, i) => (i === 0 ? w[0]!.toLowerCase() + w.slice(1) : w[0]!.toUpperCase() + w.slice(1)))
    .join('');
}

/**
 * Readable method names. The CRUD surface gets the conventional set the brief
 * asks for; everything else is derived from the literal path segments, with a
 * short override table where the derived name would be obtuse.
 */
const NAME_OVERRIDES: Record<string, string> = {
  /* The member-portal maintenance surface.
   *
   * Without these the deduper reaches for `list2`, `update2` and `summary` —
   * names that are unambiguous to a compiler and meaningless to a person. A
   * caller writing `api.maintenanceRequests.list2()` has no way to know whether
   * they picked the right one, and the collision that produced the digit is
   * invisible from the call site. Named for what they actually do instead. */
  'POST /maintenance/request': 'request',
  'POST /maintenance/update': 'updateStatus',
  'GET /maintenance/{userId}/list': 'listForUser',
  'GET /maintenance/{userId}/summary': 'summaryForUser',
  /* Security. `POST /security/errors` and `GET /security/errors` collide on
   * `errors`; naming them for what they do is clearer than `errors2` anyway. */
  'POST /security/errors': 'capture',
  'GET /security/errors': 'recent',
  'GET /security/anomalies': 'anomalies',
  /* Marketplace orders.
   *
   * `get` was `GET /orders` — a *list* called `get` — and `get2` was the single
   * order. Both predate the deduped-name guard, which only ran over modules
   * with an expected-method list and so never saw them. */
  'GET /orders': 'listOrders',
  /* `post` — the HTTP verb as a method name, which tells a caller nothing
   * about what it creates. */
  'POST /orders': 'placeOrder',
  'GET /order/{orderId}': 'readOrder',
  /* Ususu groups.
   *
   * The deduper reaches for `get`, `get2`, `group` and `groupUser` here —
   * names that are unambiguous to a compiler and meaningless to a person.
   * `evidence.group(id)` reads as "make a group"; `evidence.get2(id)` tells a
   * caller nothing about which of two endpoints they picked. */
  'POST /ususu/group/create': 'createGroup',
  'POST /ususu/group/add-member': 'groupAddMember',
  'POST /ususu/group/remove-member': 'groupRemoveMember',
  'POST /ususu/group/contribute': 'groupContribute',
  'POST /ususu/group/miss': 'groupMiss',
  'GET /ususu/group/{groupId}': 'readGroup',
  'GET /ususu/group/{groupId}/summary': 'groupSummary',
  'GET /ususu/group/user/{userId}': 'groupsForUser',
  /* The per-person evidence readers, which collided with each other. */
  'GET /references/{userId}': 'referencesFor',
  'GET /disputes/{subjectId}': 'disputesFor',
  'GET /ususu/{subjectId}': 'ususuFor',
  /* Leases: the member-portal surface.
   *
   * `create2` is what the deduper reaches for, because `POST /leases` already
   * took `create` — and `api.leases.create2()` tells a caller nothing about
   * which of the two they picked. `user` and `property` are worse: they read
   * as nouns, so `leases.user(id)` looks like it returns a user. */
  'POST /leases/create': 'draftForMember',
  'POST /leases/activate': 'activate',
  'POST /leases/complete': 'complete',
  'POST /leases/terminate': 'terminate',
  'GET /leases/{userId}/…': 'unused',
  'GET /leases/user/{userId}': 'listForUser',
  'GET /leases/property/{propertyId}': 'listForProperty',
  /* Payments: one person's ledger, and the ledger's single write route. */
  'GET /payments/{userId}/history': 'history',
  'GET /payments/{userId}/summary': 'summary',
  'POST /payments/record': 'record',
  'GET /drivers/verification-queue': 'verificationQueue',
  'PATCH /driver/me/online': 'setOnline',
  'PATCH /coordinator/{coordinatorId}/assign-properties': 'assignProperties',
  'POST /rental-car-company/{companyId}/fleet': 'addVehicle',
  'GET /rental-car-company/{companyId}/utilization': 'utilization',
  'GET /properties/public': 'searchPublic',
  'GET /ads/serve': 'serve',
  'POST /ads/track/impression': 'trackImpression',
  'POST /ads/track/click': 'trackClick',
  'GET /ads/reports': 'reports',
  'POST /ad/{adId}/submit': 'submitForReview',
  'PATCH /ad/{adId}/status': 'setStatus',
  'PATCH /ad/{adId}/review': 'review',
  'GET /ad-policy': 'current',
  'POST /ad-policy': 'publish',
  'GET /ad-policy/history': 'history',
  'GET /ad-policy/preview-rotation': 'previewRotation',
  'PATCH /ad-policy/advertiser/{advertiserId}/terms': 'setAdvertiserTerms',
  'GET /auth/roles': 'catalogue',
  'GET /auth/resolve': 'resolve',
  'PATCH /auth/user/{userId}/roles': 'assignRoles',
  'GET /hq/zones': 'zones',
  'GET /hq/zones/{zone}': 'zone',
  'GET /hq/dashboard': 'dashboard',
  'GET /hq/kpis': 'kpis',
  'GET /hq/system-health': 'systemHealth',
  'GET /hq/regions': 'regions',
  'GET /hq/command-center': 'commandCenter',
  'GET /hq/audit-log': 'auditLog',
  'GET /': 'index',
  'GET /openapi.json': 'openapi',
  'GET /_blueprint': 'contract',
  'GET /public/content': 'listContent',
  'GET /public/content/{slug}': 'getContent',
  'POST /public/track': 'track',
  'GET /public/metrics': 'metrics',
  'GET /public/admin/content': 'listAllContent',
  'POST /public/admin/content': 'createContent',
  'PATCH /public/admin/content/{contentId}': 'updateContent',
  'POST /public/admin/content/{contentId}/publish': 'publishContent',
  'DELETE /public/admin/content/{contentId}': 'archiveContent',

  // Leases
  'POST /lease/{leaseId}/payments': 'recordPayment',
  'GET /tenant/me/leases': 'mineAsTenant',
  'GET /landlord/me/leases': 'mineAsLandlord',

  // Maintenance
  'POST /maintenance-request/{requestId}/assign-vendor': 'assignVendor',
  'GET /vendor/me/maintenance-queue': 'myQueue',
  'GET /property/{propertyId}/maintenance-history': 'historyForProperty',

  // Rides
  'POST /rides/requests': 'request',
  'GET /driver/me/dispatch-queue': 'dispatchQueue',
  'GET /driver/me/rides': 'mineAsDriver',
  'GET /rider/me/rides': 'mineAsRider',

  // Payments
  'GET /tenant/me/payments': 'mineAsTenant',
  'GET /landlord/me/payments': 'mineAsLandlord',
  'GET /driver/me/payments': 'mineAsDriver',
  'GET /advertiser/me/payments': 'mineAsAdvertiser',

  // Notifications
  'POST /notifications/register-token': 'registerToken',
  'GET /notifications/me': 'inbox',
  'POST /notifications/test': 'sendTest',
  'PATCH /notification/{notificationId}': 'mark',

  // Operational flows
  'GET /lease/{leaseId}/schedule': 'schedule',
  'POST /leases/run-rent-reminders': 'runRentReminders',
  'GET /maintenance-request/{requestId}/sla': 'sla',
  'POST /maintenance-requests/run-sla-escalation': 'runSlaEscalation',
  'GET /ride/{rideId}/matches': 'matches',
  'POST /notifications/broadcast': 'broadcast',
  'GET /commercial-client/{clientId}/analytics': 'analytics',

  // Payout batches
  'GET /payout-batches': 'list',
  'POST /payout-batches': 'build',
  'GET /payout-batch/{batchId}': 'getById',
  'GET /payout-batch/{batchId}/lines': 'lines',
  'POST /payout-batch/{batchId}/settle': 'settle',
  'POST /payout-batch/{batchId}/cancel': 'cancel',

  // Document engine
  'GET /documents': 'list',
  'POST /documents': 'create',
  'GET /document/{documentId}': 'getById',
  'PATCH /document/{documentId}': 'update',
  'DELETE /document/{documentId}': 'delete',
  'POST /document/{documentId}/submit': 'submit',
  'POST /document/{documentId}/review': 'review',
  'POST /document/{documentId}/request-info': 'requestInfo',
  'POST /document/{documentId}/verify': 'verify',
  'POST /document/{documentId}/reject': 'reject',
  'POST /document/{documentId}/expire': 'expire',
  'POST /document/{documentId}/reverify': 'reverify',
  'GET /document/{documentId}/verification-summary': 'verificationSummary',
  'GET /member/me/documents': 'mine',
  'GET /staff/me/document-queue': 'queue',
  'GET /hq/documents': 'listAll',
  'GET /hq/documents/analytics': 'analytics',

  // FAC
  'GET /fac-codes': 'listGenerations',
  'POST /fac-codes': 'issue',
  'GET /fac-code/{codeId}': 'getGeneration',
  'POST /fac-code/{codeId}/revoke': 'revoke',
  'GET /fac/attempts': 'attempts',
  'GET /fac/me/clearance': 'clearance',
  'POST /fac/verify': 'verify',
  'POST /fac/me/clearance/revoke': 'standDown',
  'POST /fac/reset-requests': 'requestReset',

  // Governance
  'GET /governance/tiers': 'tiers',
  'GET /governance/visibility-matrix': 'visibilityMatrix',
  'GET /governance/me/visibility': 'myVisibility',
  'GET /governance/health': 'health',
};

function methodName(method: string, path: string, collection: string, item: string): string {
  const key = `${method} ${path}`;
  if (NAME_OVERRIDES[key]) return NAME_OVERRIDES[key]!;

  const isCollection = path === `/${collection}`;
  const isItem = /^\/[^/]+\/\{[^}]+\}$/.test(path) && path.startsWith(`/${item}/`);
  const isMe = path === `/${item}/me`;

  if (isCollection && method === 'GET') return 'list';
  if (isCollection && method === 'POST') return 'create';
  if (isMe && method === 'GET') return 'me';
  if (isMe && method === 'PATCH') return 'updateMe';
  if (isItem && method === 'GET') return 'getById';
  if (isItem && method === 'PATCH') return 'update';
  if (isItem && method === 'DELETE') return 'delete';
  if (path.endsWith('/verify')) return 'verify';
  if (path.endsWith('/restore')) return 'restore';

  const tail = path
    .split('/')
    .filter((s) => s && !s.startsWith('{'))
    .slice(1)
    .join('-');
  return camel(tail || method.toLowerCase());
}

interface ModuleOp {
  method: string;
  path: string;
  op: Op;
  fn: string;
}

/**
 * OpenAPI encodes optional auth as an empty requirement object alongside the
 * real one. Read all three cases, or every anonymous endpoint looks required.
 */
function authOf(op: Op): 'none' | 'optional' | 'required' {
  const security = (op.security ?? []) as Record<string, unknown>[];
  if (security.length === 0) return 'none';
  if (security.some((s) => Object.keys(s).length === 0)) return 'optional';
  return 'required';
}

function requestTypeFor(op: Op, emittedInputs: Set<string>): string | null {
  const ref = op.requestBody?.content?.['application/json']?.schema?.$ref;
  if (!ref) return null;
  const name = refName(ref);
  return emittedInputs.has(name) ? `${name}Input` : name;
}

/**
 * A `$ref` to a component that is itself an array of another component.
 *
 * `LeaseList` is `Lease[]`, and a caller wants `Page<Lease>`, not `Page<Lease[]>`.
 * Named list schemas keep the spec readable; unwrapping them here keeps the
 * generated signatures honest.
 */
function arrayItemFor(name: string): string | null {
  const schema = spec.components.schemas[name] as JsonSchema | undefined;
  if (!schema || schema.type !== 'array') return null;
  const items = schema.items as JsonSchema | undefined;
  return items?.$ref ? refName(items.$ref) : null;
}

function responseTypeFor(op: Op): string {
  const success = Object.entries(op.responses).find(([code]) => code.startsWith('2'));
  if (!success) return 'void';
  const [code, response] = success;
  if (code === '204') return 'void';

  const schema = response.content?.['application/json']?.schema;
  if (!schema) return 'void';
  if (schema.$ref) return refName(schema.$ref);

  const data = schema.properties?.data as JsonSchema | undefined;
  if (!data) return 'void';
  if (data.$ref) {
    const name = refName(data.$ref);
    const item = arrayItemFor(name);
    return item ? `${item}[]` : name;
  }
  if (data.type === 'array' && data.items?.$ref) return `${refName(data.items.$ref)}[]`;
  return 'unknown';
}

function isPaginated(op: Op): boolean {
  const success = Object.entries(op.responses).find(([code]) => code.startsWith('2'));
  const schema = success?.[1]?.content?.['application/json']?.schema;
  return Boolean(schema?.properties?.meta);
}

function generateModules(emittedInputs: Set<string>): {
  modules: string[];
  operationCount: number;
} {
  const grouped = new Map<string, ModuleOp[]>();

  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      const mod = moduleFor(op.tags[0]!, path);
      const list = grouped.get(mod) ?? [];
      list.push({ method: method.toUpperCase(), path, op, fn: '' });
      grouped.set(mod, list);
    }
  }

  let operationCount = 0;
  const moduleNames = [...grouped.keys()].sort();

  for (const mod of moduleNames) {
    const ops = grouped.get(mod)!;

    // Derive the collection/item segment pair from the paths in this module.
    const collection = ops.map((o) => o.path.slice(1)).find((p) => !p.includes('/') && !p.includes('{')) ?? mod;
    const item =
      ops
        .map((o) => o.path.split('/')[1] ?? '')
        .find((s) => s && s !== collection && !s.startsWith('{')) ?? collection;

    const used = new Set<string>();
    for (const entry of ops) {
      let name = methodName(entry.method, entry.path, collection, item);
      let n = 2;
      while (used.has(name)) name = `${name}${n++}`;
      used.add(name);
      entry.fn = name;
    }

    ops.sort((a, b) => a.fn.localeCompare(b.fn));

    const typeImports = new Set<string>();
    const bodyLines: string[] = [];

    for (const { method, path, op, fn } of ops) {
      operationCount += 1;
      const reqType = requestTypeFor(op, emittedInputs);
      const resType = responseTypeFor(op);
      if (reqType) typeImports.add(reqType);
      const bare = resType.replace(/\[\]$/, '');
      if (bare !== 'void' && bare !== 'unknown') typeImports.add(bare);

      const pathParams = [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]!);
      const args: string[] = pathParams.map((p) => `${p}: string`);
      if (reqType) args.push(`body: ${reqType}`);
      const paginated = isPaginated(op);
      args.push(paginated ? 'options?: ListOptions' : 'options?: RequestOptions');

      const template = path.replace(/\{([^}]+)\}/g, (_m, p: string) => `\${seg(${p})}`);
      const target = template.includes('${') ? `\`${template}\`` : `'${path}'`;

      const metaLiteral =
        `{ operationId: '${op.operationId}', method: '${method}', pathTemplate: '${path}', ` +
        `zone: ${op['x-zone'] ? `'${op['x-zone']}'` : 'null'}, ` +
        `roles: ${JSON.stringify(op['x-roles'])}, ` +
        `permissions: ${JSON.stringify(op['x-permissions'])}, ` +
        `ownership: '${op['x-ownership']}', ` +
        `auth: '${authOf(op)}' }`;

      const call = paginated
        ? `client().list<${resType.replace(/\[\]$/, '')}>(${target}, withMeta(options, META.${fn}))`
        : method === 'GET'
          ? `client().get<${resType}>(${target}, withMeta(options, META.${fn}))`
          : method === 'DELETE'
            ? `client().delete<${resType}>(${target}, withMeta(options, META.${fn}))`
            : `client().${method.toLowerCase()}<${resType}>(${target}, ${reqType ? 'body' : 'undefined'}, withMeta(options, META.${fn}))`;

      const returnType = paginated
        ? `Promise<Page<${resType.replace(/\[\]$/, '')}>>`
        : `Promise<${resType}>`;

      const docLines = [
        op.summary ?? null,
        op.description ? `\n   * ${op.description}` : null,
        '',
        `\`${method} ${path}\``,
        `Zone: ${op['x-zone'] ?? '—'}`,
        `Roles: ${op['x-roles'].length ? op['x-roles'].join(', ') : 'anyone'}`,
        op['x-permissions'].length ? `Permission: ${op['x-permissions'].join(' | ')}` : null,
        `Ownership: ${op['x-ownership']}`,
      ]
        .filter((l) => l !== null)
        .map((l) => (l === '' ? '   *' : `   * ${l}`));

      bodyLines.push(
        `  /**\n${docLines.join('\n')}\n   */\n  ${fn}(${args.join(', ')}): ${returnType} {\n    return ${call};\n  },\n`,
      );
    }

    const metaEntries = ops
      .map(({ method, path, op, fn }) => {
        return (
          `  ${fn}: { operationId: '${op.operationId}', method: '${method}' as const, pathTemplate: '${path}', ` +
          `zone: ${op['x-zone'] ? `'${op['x-zone']}' as const` : 'null'}, ` +
          `roles: ${JSON.stringify(op['x-roles'])} as Role[], ` +
          `permissions: ${JSON.stringify(op['x-permissions'])}, ` +
          `ownership: '${op['x-ownership']}' as const, ` +
          `auth: '${authOf(op)}' as const },`
        );
      })
      .join('\n');

    const imports = [...typeImports].sort();
    const contents =
      banner(`\`${mod}\` — ${ops.length} operation${ops.length === 1 ? '' : 's'}.`) +
      `import { seg } from '../client/ApiClient.js';\n` +
      `import type { OperationMeta } from '../client/types.js';\n` +
      `import type { Page } from '../types/pagination.js';\n` +
      `import type { Role } from '../types/roles.js';\n` +
      (imports.length ? `import type {\n${imports.map((i) => `  ${i},`).join('\n')}\n} from '../types/index.js';\n` : '') +
      `import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';\n\n` +
      `/** Zone, roles and permissions for each operation, straight from the spec. */\n` +
      `export const META = {\n${metaEntries}\n} satisfies Record<string, OperationMeta>;\n\n` +
      `export const ${identFor(mod)} = {\n${bodyLines.join('\n')}};\n\n` +
      `export type ${mod[0]!.toUpperCase()}${mod.slice(1)}Api = typeof ${identFor(mod)};\n`;

    write(`modules/${mod}.ts`, contents);
  }

  // Shared plumbing for the generated modules.
  write(
    'modules/_runtime.ts',
    banner('Shared plumbing for the generated modules.') +
      `import type { ApiClient, RequestOptions as BaseRequestOptions } from '../client/ApiClient.js';\n` +
      `import type { OperationMeta, QueryParams } from '../client/types.js';\n` +
      `import type { ListQuery } from '../types/pagination.js';\n` +
      `import { LrmcApiError } from '../types/errors.js';\n\n` +
      `export type RequestOptions = BaseRequestOptions;\n` +
      `export interface ListOptions extends BaseRequestOptions {\n  query?: ListQuery & QueryParams;\n}\n\n` +
      `let current: ApiClient | null = null;\n\n` +
      `/** Set by \`configureApi()\`. Modules resolve it lazily, per call. */\n` +
      `export function setClient(instance: ApiClient | null): void {\n  current = instance;\n}\n\n` +
      `export function client(): ApiClient {\n` +
      `  if (!current) {\n` +
      `    throw new LrmcApiError({\n` +
      `      code: 'CONFIGURATION_ERROR',\n` +
      `      message:\n` +
      `        'SDK not configured. Call configureApi({ baseUrl, token }) before using any module.',\n` +
      `    });\n  }\n  return current;\n}\n\n` +
      `export function hasClient(): boolean {\n  return current !== null;\n}\n\n` +
      `/** Attach operation metadata so the optional RBAC guard can read it. */\n` +
      `export function withMeta(\n  options: BaseRequestOptions | undefined,\n  meta: OperationMeta,\n): BaseRequestOptions {\n  return { ...options, meta };\n}\n`,
  );

  // The barrel.
  write(
    'modules/index.ts',
    banner('Every module, and the aggregate `api` surface.') +
      moduleNames.map((m) => `import { ${identFor(m)} } from './${m}.js';`).join('\n') +
      '\n\n' +
      moduleNames
        .map(
          (m) =>
            `export { ${identFor(m)}, META as ${m}Meta, type ${m[0]!.toUpperCase()}${m.slice(1)}Api } from './${m}.js';`,
        )
        .join('\n') +
      '\n\n' +
      `/**\n * The whole API, grouped by module.\n *\n *   import { api } from '@lrmc/sdk';\n *   const page = await api.landlords.list();\n */\nexport const api = {\n` +
      moduleNames
        .map((m) => (identFor(m) === m ? `  ${m},` : `  ${m}: ${identFor(m)},`))
        .join('\n') +
      `\n} as const;\n\nexport type Api = typeof api;\n`,
  );

  return { modules: moduleNames, operationCount };
}

// ─────────────────────────────────────────────────────────────────────────────

const { emittedInputs } = generateTypes();
generateRolesAndZones();
const { modules, operationCount } = generateModules(emittedInputs);

const schemaCount = Object.keys(spec.components.schemas).length;
const pathCount = Object.keys(spec.paths).length;

console.log('Generated from backend/docs/openapi.json');
console.log(`  types/index.ts   ${schemaCount} schemas (+${emittedInputs.size} Input variants)`);
console.log(`  types/roles.ts   ${spec['x-roles-catalogue'].length} roles`);
console.log(`  types/zones.ts   ${spec['x-hq-zones'].length} HQ zones`);
console.log(`  modules/         ${modules.length} modules, ${operationCount} operations across ${pathCount} paths`);
console.log(`  ${modules.join(', ')}`);
