/**
 * Shared plumbing for the generated modules.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import type { ApiClient, RequestOptions as BaseRequestOptions } from '../client/ApiClient.js';
import type { OperationMeta, QueryParams } from '../client/types.js';
import type { ListQuery } from '../types/pagination.js';
import { LrmcApiError } from '../types/errors.js';

export type RequestOptions = BaseRequestOptions;
export interface ListOptions extends BaseRequestOptions {
  query?: ListQuery & QueryParams;
}

let current: ApiClient | null = null;

/** Set by `configureApi()`. Modules resolve it lazily, per call. */
export function setClient(instance: ApiClient | null): void {
  current = instance;
}

export function client(): ApiClient {
  if (!current) {
    throw new LrmcApiError({
      code: 'CONFIGURATION_ERROR',
      message:
        'SDK not configured. Call configureApi({ baseUrl, token }) before using any module.',
    });
  }
  return current;
}

export function hasClient(): boolean {
  return current !== null;
}

/** Attach operation metadata so the optional RBAC guard can read it. */
export function withMeta(
  options: BaseRequestOptions | undefined,
  meta: OperationMeta,
): BaseRequestOptions {
  return { ...options, meta };
}
