/**
 * `adPolicy` — 5 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AdPolicy,
  AdPolicyInput,
  Advertiser,
  AdvertiserTermsRequest,
  RotationPreview,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  current: { operationId: 'getAdPolicy', method: 'GET' as const, pathTemplate: '/ad-policy', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["adPolicy:read","policy:read"], ownership: 'none' as const, auth: 'required' as const },
  history: { operationId: 'getAdPolicyHistory', method: 'GET' as const, pathTemplate: '/ad-policy/history', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
  previewRotation: { operationId: 'getAdPolicyPreviewRotation', method: 'GET' as const, pathTemplate: '/ad-policy/preview-rotation', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["adPolicy:read","policy:read"], ownership: 'none' as const, auth: 'required' as const },
  publish: { operationId: 'postAdPolicy', method: 'POST' as const, pathTemplate: '/ad-policy', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
  setAdvertiserTerms: { operationId: 'patchAdPolicyAdvertiserByAdvertiserIdTerms', method: 'PATCH' as const, pathTemplate: '/ad-policy/advertiser/{advertiserId}/terms', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const adPolicy = {
  /**
   * The ad policy currently in force
   *
   * `GET /ad-policy`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: adPolicy:read | policy:read
   * Ownership: none
   */
  current(options?: RequestOptions): Promise<AdPolicy> {
    return client().get<AdPolicy>('/ad-policy', withMeta(options, META.current));
  },

  /**
   * Every ratified policy version, newest first
   * 
   * Founder-only.
   *
   * `GET /ad-policy/history`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Ownership: none
   */
  history(options?: RequestOptions): Promise<AdPolicy[]> {
    return client().get<AdPolicy[]>('/ad-policy/history', withMeta(options, META.history));
  },

  /**
   * Dry-run the rotation and show each ad with its effective weight
   *
   * `GET /ad-policy/preview-rotation`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: adPolicy:read | policy:read
   * Ownership: none
   */
  previewRotation(options?: RequestOptions): Promise<RotationPreview> {
    return client().get<RotationPreview>('/ad-policy/preview-rotation', withMeta(options, META.previewRotation));
  },

  /**
   * Ratify a new policy version
   * 
   * Founder-only. Creates a new version and deactivates the previous one — policy is versioned, never edited, so an ad served last Tuesday stays explicable by the policy in force last Tuesday.
   *
   * `POST /ad-policy`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Ownership: none
   */
  publish(body: AdPolicyInput, options?: RequestOptions): Promise<AdPolicy> {
    return client().post<AdPolicy>('/ad-policy', body, withMeta(options, META.publish));
  },

  /**
   * Set credit limit, agreed CPM/CPC and policy strikes
   * 
   * Founder-only. Commercial terms sit outside the advertiser’s own reach.
   *
   * `PATCH /ad-policy/advertiser/{advertiserId}/terms`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Ownership: none
   */
  setAdvertiserTerms(advertiserId: string, body: AdvertiserTermsRequest, options?: RequestOptions): Promise<Advertiser> {
    return client().patch<Advertiser>(`/ad-policy/advertiser/${seg(advertiserId)}/terms`, body, withMeta(options, META.setAdvertiserTerms));
  },
};

export type AdPolicyApi = typeof adPolicy;
