/**
 * `ads` — 12 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Ad,
  AdInput,
  AdReport,
  AdReviewRequest,
  AdStatusRequest,
  AdTrackRequest,
  ServeAdsResponse,
  TrackResult,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postAds', method: 'POST' as const, pathTemplate: '/ads', zone: 'MEMBER_PORTAL' as const, roles: ["founder","advertiser"] as Role[], permissions: ["ad:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteAdByAdId', method: 'DELETE' as const, pathTemplate: '/ad/{adId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","advertiser"] as Role[], permissions: ["ad:delete","ad:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  getById: { operationId: 'getAdByAdId', method: 'GET' as const, pathTemplate: '/ad/{adId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","advertiser"] as Role[], permissions: ["ad:read","ad:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getAds', method: 'GET' as const, pathTemplate: '/ads', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","advertiser"] as Role[], permissions: ["ad:read","ad:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  reports: { operationId: 'getAdsReports', method: 'GET' as const, pathTemplate: '/ads/reports', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","advertiser"] as Role[], permissions: ["adReport:read","adReport:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  review: { operationId: 'patchAdByAdIdReview', method: 'PATCH' as const, pathTemplate: '/ad/{adId}/review', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["ad:approve"], ownership: 'none' as const, auth: 'required' as const },
  serve: { operationId: 'getAdsServe', method: 'GET' as const, pathTemplate: '/ads/serve', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  setStatus: { operationId: 'patchAdByAdIdStatus', method: 'PATCH' as const, pathTemplate: '/ad/{adId}/status', zone: 'MEMBER_PORTAL' as const, roles: ["founder","advertiser"] as Role[], permissions: ["ad:updateOwn","ad:update"], ownership: 'scoped' as const, auth: 'required' as const },
  submitForReview: { operationId: 'postAdByAdIdSubmit', method: 'POST' as const, pathTemplate: '/ad/{adId}/submit', zone: 'MEMBER_PORTAL' as const, roles: ["founder","advertiser"] as Role[], permissions: ["ad:updateOwn","ad:update"], ownership: 'scoped' as const, auth: 'required' as const },
  trackClick: { operationId: 'postAdsTrackClick', method: 'POST' as const, pathTemplate: '/ads/track/click', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  trackImpression: { operationId: 'postAdsTrackImpression', method: 'POST' as const, pathTemplate: '/ads/track/impression', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  update: { operationId: 'patchAdByAdId', method: 'PATCH' as const, pathTemplate: '/ad/{adId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","advertiser"] as Role[], permissions: ["ad:update","ad:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const ads = {
  /**
   * Submit a creative (starts as draft)
   *
   * `POST /ads`
   * Zone: MEMBER_PORTAL
   * Roles: founder, advertiser
   * Permission: ad:create
   * Ownership: none
   */
  create(body: AdInput, options?: RequestOptions): Promise<Ad> {
    return client().post<Ad>('/ads', body, withMeta(options, META.create));
  },

  /**
   * Archive an ad
   *
   * `DELETE /ad/{adId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, advertiser
   * Permission: ad:delete | ad:updateOwn
   * Ownership: scoped
   */
  delete(adId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/ad/${seg(adId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one ad
   *
   * `GET /ad/{adId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, advertiser
   * Permission: ad:read | ad:readOwn
   * Ownership: scoped
   */
  getById(adId: string, options?: RequestOptions): Promise<Ad> {
    return client().get<Ad>(`/ad/${seg(adId)}`, withMeta(options, META.getById));
  },

  /**
   * List ads
   *
   * `GET /ads`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, advertiser
   * Permission: ad:read | ad:readOwn
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Ad>> {
    return client().list<Ad>('/ads', withMeta(options, META.list));
  },

  /**
   * Impressions, clicks and CTR by ad, zone and category
   * 
   * An advertiser's request is silently narrowed to their own campaigns regardless of the advertiserId they pass.
   *
   * `GET /ads/reports`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, advertiser
   * Permission: adReport:read | adReport:readOwn
   * Ownership: scoped
   */
  reports(options?: RequestOptions): Promise<AdReport> {
    return client().get<AdReport>('/ads/reports', withMeta(options, META.reports));
  },

  /**
   * Approve or reject a submitted ad
   * 
   * Approval is an HQ act, not a Member Portal one. A rejection must carry a reason.
   *
   * `PATCH /ad/{adId}/review`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: ad:approve
   * Ownership: none
   */
  review(adId: string, body: AdReviewRequest, options?: RequestOptions): Promise<Ad> {
    return client().patch<Ad>(`/ad/${seg(adId)}/review`, body, withMeta(options, META.review));
  },

  /**
   * Serve a rotated set of ads for a zone and placement
   * 
   * Anonymous visitor and signed-in member hit the same endpoint; the engine sees a different role and zone. Cache-Control: private, no-store.
   *
   * `GET /ads/serve`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  serve(options?: RequestOptions): Promise<ServeAdsResponse> {
    return client().get<ServeAdsResponse>('/ads/serve', withMeta(options, META.serve));
  },

  /**
   * Activate, pause or archive an ad
   * 
   * activate honours the Founder review requirement and refuses if the advertiser is not in good standing or the flight has ended.
   *
   * `PATCH /ad/{adId}/status`
   * Zone: MEMBER_PORTAL
   * Roles: founder, advertiser
   * Permission: ad:updateOwn | ad:update
   * Ownership: scoped
   */
  setStatus(adId: string, body: AdStatusRequest, options?: RequestOptions): Promise<Ad> {
    return client().patch<Ad>(`/ad/${seg(adId)}/status`, body, withMeta(options, META.setStatus));
  },

  /**
   * Submit an ad for HQ review
   *
   * `POST /ad/{adId}/submit`
   * Zone: MEMBER_PORTAL
   * Roles: founder, advertiser
   * Permission: ad:updateOwn | ad:update
   * Ownership: scoped
   */
  submitForReview(adId: string, options?: RequestOptions): Promise<Ad> {
    return client().post<Ad>(`/ad/${seg(adId)}/submit`, undefined, withMeta(options, META.submitForReview));
  },

  /**
   * Record a click
   *
   * `POST /ads/track/click`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  trackClick(body: AdTrackRequest, options?: RequestOptions): Promise<TrackResult> {
    return client().post<TrackResult>('/ads/track/click', body, withMeta(options, META.trackClick));
  },

  /**
   * Record an impression
   * 
   * Deduped per session inside AD_IMPRESSION_DEDUPE_WINDOW_SECONDS; a repeat returns counted:false.
   *
   * `POST /ads/track/impression`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  trackImpression(body: AdTrackRequest, options?: RequestOptions): Promise<TrackResult> {
    return client().post<TrackResult>('/ads/track/impression', body, withMeta(options, META.trackImpression));
  },

  /**
   * Edit an ad
   *
   * `PATCH /ad/{adId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, advertiser
   * Permission: ad:update | ad:updateOwn
   * Ownership: scoped
   */
  update(adId: string, body: AdInput, options?: RequestOptions): Promise<Ad> {
    return client().patch<Ad>(`/ad/${seg(adId)}`, body, withMeta(options, META.update));
  },
};

export type AdsApi = typeof ads;
