/**
 * `advertisers` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Advertiser,
  AdvertiserInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postAdvertisers', method: 'POST' as const, pathTemplate: '/advertisers', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["advertiserProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteAdvertiserByAdvertiserId', method: 'DELETE' as const, pathTemplate: '/advertiser/{advertiserId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["advertiserProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getAdvertiserByAdvertiserId', method: 'GET' as const, pathTemplate: '/advertiser/{advertiserId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["advertiserProfile:read","advertiserProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getAdvertisers', method: 'GET' as const, pathTemplate: '/advertisers', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["advertiserProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getAdvertiserMe', method: 'GET' as const, pathTemplate: '/advertiser/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","advertiser"] as Role[], permissions: ["advertiserProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postAdvertiserByAdvertiserIdRestore', method: 'POST' as const, pathTemplate: '/advertiser/{advertiserId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["advertiserProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchAdvertiserByAdvertiserId', method: 'PATCH' as const, pathTemplate: '/advertiser/{advertiserId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["advertiserProfile:update","advertiserProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchAdvertiserMe', method: 'PATCH' as const, pathTemplate: '/advertiser/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","advertiser"] as Role[], permissions: ["advertiserProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchAdvertiserByAdvertiserIdVerify', method: 'PATCH' as const, pathTemplate: '/advertiser/{advertiserId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["advertiserProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const advertisers = {
  /**
   * Create a advertiser profile
   *
   * `POST /advertisers`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: advertiserProfile:create
   * Ownership: none
   */
  create(body: AdvertiserInput, options?: RequestOptions): Promise<Advertiser> {
    return client().post<Advertiser>('/advertisers', body, withMeta(options, META.create));
  },

  /**
   * Archive a advertiser profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /advertiser/{advertiserId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: advertiserProfile:delete
   * Ownership: none
   */
  delete(advertiserId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/advertiser/${seg(advertiserId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one advertiser profile
   *
   * `GET /advertiser/{advertiserId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive
   * Permission: advertiserProfile:read | advertiserProfile:readOwn
   * Ownership: scoped
   */
  getById(advertiserId: string, options?: RequestOptions): Promise<Advertiser> {
    return client().get<Advertiser>(`/advertiser/${seg(advertiserId)}`, withMeta(options, META.getById));
  },

  /**
   * List advertiser profiles
   *
   * `GET /advertisers`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive
   * Permission: advertiserProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Advertiser>> {
    return client().list<Advertiser>('/advertisers', withMeta(options, META.list));
  },

  /**
   * Read the caller's own advertiser profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /advertiser/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, advertiser
   * Permission: advertiserProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Advertiser> {
    return client().get<Advertiser>('/advertiser/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived advertiser profile
   *
   * `POST /advertiser/{advertiserId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: advertiserProfile:update
   * Ownership: none
   */
  restore(advertiserId: string, options?: RequestOptions): Promise<Advertiser> {
    return client().post<Advertiser>(`/advertiser/${seg(advertiserId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one advertiser profile
   *
   * `PATCH /advertiser/{advertiserId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: advertiserProfile:update | advertiserProfile:updateOwn
   * Ownership: scoped
   */
  update(advertiserId: string, body: AdvertiserInput, options?: RequestOptions): Promise<Advertiser> {
    return client().patch<Advertiser>(`/advertiser/${seg(advertiserId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own advertiser profile
   *
   * `PATCH /advertiser/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, advertiser
   * Permission: advertiserProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: AdvertiserInput, options?: RequestOptions): Promise<Advertiser> {
    return client().patch<Advertiser>('/advertiser/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a advertiser profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /advertiser/{advertiserId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: advertiserProfile:verify
   * Ownership: none
   */
  verify(advertiserId: string, body: VerificationRequest, options?: RequestOptions): Promise<Advertiser> {
    return client().patch<Advertiser>(`/advertiser/${seg(advertiserId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type AdvertisersApi = typeof advertisers;
