/**
 * `airbnbHosts` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AirbnbHost,
  AirbnbHostInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postAirbnbHosts', method: 'POST' as const, pathTemplate: '/airbnb-hosts', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["airbnbHostProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteAirbnbHostByHostId', method: 'DELETE' as const, pathTemplate: '/airbnb-host/{hostId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["airbnbHostProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getAirbnbHostByHostId', method: 'GET' as const, pathTemplate: '/airbnb-host/{hostId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["airbnbHostProfile:read","airbnbHostProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getAirbnbHosts', method: 'GET' as const, pathTemplate: '/airbnb-hosts', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["airbnbHostProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getAirbnbHostMe', method: 'GET' as const, pathTemplate: '/airbnb-host/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","airbnbHost"] as Role[], permissions: ["airbnbHostProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postAirbnbHostByHostIdRestore', method: 'POST' as const, pathTemplate: '/airbnb-host/{hostId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["airbnbHostProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchAirbnbHostByHostId', method: 'PATCH' as const, pathTemplate: '/airbnb-host/{hostId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["airbnbHostProfile:update","airbnbHostProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchAirbnbHostMe', method: 'PATCH' as const, pathTemplate: '/airbnb-host/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","airbnbHost"] as Role[], permissions: ["airbnbHostProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchAirbnbHostByHostIdVerify', method: 'PATCH' as const, pathTemplate: '/airbnb-host/{hostId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["airbnbHostProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const airbnbHosts = {
  /**
   * Create a airbnb host profile
   *
   * `POST /airbnb-hosts`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: airbnbHostProfile:create
   * Ownership: none
   */
  create(body: AirbnbHostInput, options?: RequestOptions): Promise<AirbnbHost> {
    return client().post<AirbnbHost>('/airbnb-hosts', body, withMeta(options, META.create));
  },

  /**
   * Archive a airbnb host profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /airbnb-host/{hostId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: airbnbHostProfile:delete
   * Ownership: none
   */
  delete(hostId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/airbnb-host/${seg(hostId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one airbnb host profile
   *
   * `GET /airbnb-host/{hostId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: airbnbHostProfile:read | airbnbHostProfile:readOwn
   * Ownership: scoped
   */
  getById(hostId: string, options?: RequestOptions): Promise<AirbnbHost> {
    return client().get<AirbnbHost>(`/airbnb-host/${seg(hostId)}`, withMeta(options, META.getById));
  },

  /**
   * List airbnb host profiles
   *
   * `GET /airbnb-hosts`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: airbnbHostProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<AirbnbHost>> {
    return client().list<AirbnbHost>('/airbnb-hosts', withMeta(options, META.list));
  },

  /**
   * Read the caller's own airbnb host profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /airbnb-host/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, airbnbHost
   * Permission: airbnbHostProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<AirbnbHost> {
    return client().get<AirbnbHost>('/airbnb-host/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived airbnb host profile
   *
   * `POST /airbnb-host/{hostId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: airbnbHostProfile:update
   * Ownership: none
   */
  restore(hostId: string, options?: RequestOptions): Promise<AirbnbHost> {
    return client().post<AirbnbHost>(`/airbnb-host/${seg(hostId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one airbnb host profile
   *
   * `PATCH /airbnb-host/{hostId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: airbnbHostProfile:update | airbnbHostProfile:updateOwn
   * Ownership: scoped
   */
  update(hostId: string, body: AirbnbHostInput, options?: RequestOptions): Promise<AirbnbHost> {
    return client().patch<AirbnbHost>(`/airbnb-host/${seg(hostId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own airbnb host profile
   *
   * `PATCH /airbnb-host/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, airbnbHost
   * Permission: airbnbHostProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: AirbnbHostInput, options?: RequestOptions): Promise<AirbnbHost> {
    return client().patch<AirbnbHost>('/airbnb-host/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a airbnb host profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /airbnb-host/{hostId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: airbnbHostProfile:verify
   * Ownership: none
   */
  verify(hostId: string, body: VerificationRequest, options?: RequestOptions): Promise<AirbnbHost> {
    return client().patch<AirbnbHost>(`/airbnb-host/${seg(hostId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type AirbnbHostsApi = typeof airbnbHosts;
