/**
 * `application` — 11 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Application,
  ApplicationAssessment,
  CreateApplicationRequest,
  DecideApplicationRequest,
  RequestFromApplicantRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  approve: { operationId: 'postApplicationByApplicationIdApprove', method: 'POST' as const, pathTemplate: '/application/{applicationId}/approve', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["application:approve"], ownership: 'scoped' as const, auth: 'required' as const },
  assess: { operationId: 'postApplicationByApplicationIdAssess', method: 'POST' as const, pathTemplate: '/application/{applicationId}/assess', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["application:update"], ownership: 'scoped' as const, auth: 'required' as const },
  create: { operationId: 'postApplications', method: 'POST' as const, pathTemplate: '/applications', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","tenant"] as Role[], permissions: ["application:create"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getApplicationByApplicationId', method: 'GET' as const, pathTemplate: '/application/{applicationId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["application:readOwn","application:read"], ownership: 'scoped' as const, auth: 'required' as const },
  lease: { operationId: 'postApplicationByApplicationIdLease', method: 'POST' as const, pathTemplate: '/application/{applicationId}/lease', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","landlord"] as Role[], permissions: ["lease:create"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getApplications', method: 'GET' as const, pathTemplate: '/applications', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["application:readOwn","application:read"], ownership: 'scoped' as const, auth: 'required' as const },
  reject: { operationId: 'postApplicationByApplicationIdReject', method: 'POST' as const, pathTemplate: '/application/{applicationId}/reject', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["application:approve"], ownership: 'scoped' as const, auth: 'required' as const },
  requestInformation: { operationId: 'postApplicationByApplicationIdRequestInformation', method: 'POST' as const, pathTemplate: '/application/{applicationId}/request-information', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["application:update"], ownership: 'scoped' as const, auth: 'required' as const },
  review: { operationId: 'postApplicationByApplicationIdReview', method: 'POST' as const, pathTemplate: '/application/{applicationId}/review', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["application:update"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchApplicationByApplicationId', method: 'PATCH' as const, pathTemplate: '/application/{applicationId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["application:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  withdraw: { operationId: 'postApplicationByApplicationIdWithdraw', method: 'POST' as const, pathTemplate: '/application/{applicationId}/withdraw', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["application:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const application = {
  /**
   * Approve, with a name and a reason
   * 
   * A landlord cannot: LRMC carries the tenancy, holds the deposit and answers for the decision. A reason is required for an approval, not only for a refusal.
   *
   * `POST /application/{applicationId}/approve`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: application:approve
   * Ownership: scoped
   */
  approve(applicationId: string, body: DecideApplicationRequest, options?: RequestOptions): Promise<Application> {
    return client().post<Application>(`/application/${seg(applicationId)}/approve`, body, withMeta(options, META.approve));
  },

  /**
   * Re-score against current evidence
   * 
   * The stored assessment is a snapshot of what the decider saw, not a live view — this is how it is deliberately refreshed.
   *
   * `POST /application/{applicationId}/assess`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: application:update
   * Ownership: scoped
   */
  assess(applicationId: string, options?: RequestOptions): Promise<ApplicationAssessment> {
    return client().post<ApplicationAssessment>(`/application/${seg(applicationId)}/assess`, undefined, withMeta(options, META.assess));
  },

  /**
   * Apply for a tenancy
   * 
   * Scored on submission by `eligibility.assessApplication`, which recommends and never decides. One live application per person per property.
   *
   * `POST /applications`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, tenant
   * Permission: application:create
   * Ownership: none
   */
  create(body: CreateApplicationRequest, options?: RequestOptions): Promise<Application> {
    return client().post<Application>('/applications', body, withMeta(options, META.create));
  },

  /**
   * Read one application
   *
   * `GET /application/{applicationId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord, tenant
   * Permission: application:readOwn | application:read
   * Ownership: scoped
   */
  getById(applicationId: string, options?: RequestOptions): Promise<Application> {
    return client().get<Application>(`/application/${seg(applicationId)}`, withMeta(options, META.getById));
  },

  /**
   * Record the lease an approval produced
   * 
   * Only from `approved`. The lease itself is created through `POST /leases`.
   *
   * `POST /application/{applicationId}/lease`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, landlord
   * Permission: lease:create
   * Ownership: scoped
   */
  lease(applicationId: string, options?: RequestOptions): Promise<Application> {
    return client().post<Application>(`/application/${seg(applicationId)}/lease`, undefined, withMeta(options, META.lease));
  },

  /**
   * List applications you can see
   * 
   * A landlord sees who applied for their property and what LRMC made of them; they do not decide.
   *
   * `GET /applications`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord, tenant
   * Permission: application:readOwn | application:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Application>> {
    return client().list<Application>('/applications', withMeta(options, META.list));
  },

  /**
   * Reject, with a name and a reason
   *
   * `POST /application/{applicationId}/reject`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: application:approve
   * Ownership: scoped
   */
  reject(applicationId: string, body: DecideApplicationRequest, options?: RequestOptions): Promise<Application> {
    return client().post<Application>(`/application/${seg(applicationId)}/reject`, body, withMeta(options, META.reject));
  },

  /**
   * Ask the applicant for something
   *
   * `POST /application/{applicationId}/request-information`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: application:update
   * Ownership: scoped
   */
  requestInformation(applicationId: string, body: RequestFromApplicantRequest, options?: RequestOptions): Promise<Application> {
    return client().post<Application>(`/application/${seg(applicationId)}/request-information`, body, withMeta(options, META.requestInformation));
  },

  /**
   * Open an application
   *
   * `POST /application/{applicationId}/review`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: application:update
   * Ownership: scoped
   */
  review(applicationId: string, options?: RequestOptions): Promise<Application> {
    return client().post<Application>(`/application/${seg(applicationId)}/review`, undefined, withMeta(options, META.review));
  },

  /**
   * Improve your own application
   * 
   * Re-scored on change. Refused once the application has been decided.
   *
   * `PATCH /application/{applicationId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: application:updateOwn
   * Ownership: scoped
   */
  update(applicationId: string, body: CreateApplicationRequest, options?: RequestOptions): Promise<Application> {
    return client().patch<Application>(`/application/${seg(applicationId)}`, body, withMeta(options, META.update));
  },

  /**
   * Withdraw your own application
   * 
   * Only the applicant. LRMC does not withdraw on somebody’s behalf — it rejects, which is a different word with a different record.
   *
   * `POST /application/{applicationId}/withdraw`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord, tenant
   * Permission: application:readOwn
   * Ownership: scoped
   */
  withdraw(applicationId: string, options?: RequestOptions): Promise<Application> {
    return client().post<Application>(`/application/${seg(applicationId)}/withdraw`, undefined, withMeta(options, META.withdraw));
  },
};

export type ApplicationApi = typeof application;
