/**
 * `auth` — 5 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AuthTokens,
  ChangePasswordRequest,
  CurrentActor,
  LoginRequest,
  RefreshRequest,
  RegisterRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  changePassword: { operationId: 'postAuthChangePassword', method: 'POST' as const, pathTemplate: '/auth/change-password', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'self' as const, auth: 'required' as const },
  login: { operationId: 'postAuthLogin', method: 'POST' as const, pathTemplate: '/auth/login', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'none' as const },
  me: { operationId: 'getAuthMe', method: 'GET' as const, pathTemplate: '/auth/me', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'self' as const, auth: 'required' as const },
  refresh: { operationId: 'postAuthRefresh', method: 'POST' as const, pathTemplate: '/auth/refresh', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'none' as const },
  register: { operationId: 'postAuthRegister', method: 'POST' as const, pathTemplate: '/auth/register', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'none' as const },
} satisfies Record<string, OperationMeta>;

export const auth = {
  /**
   * Change own password
   *
   * `POST /auth/change-password`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: self
   */
  changePassword(body: ChangePasswordRequest, options?: RequestOptions): Promise<void> {
    return client().post<void>('/auth/change-password', body, withMeta(options, META.changePassword));
  },

  /**
   * Exchange credentials for tokens
   * 
   * Locks the account for 15 minutes after 8 consecutive failures.
   *
   * `POST /auth/login`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  login(body: LoginRequest, options?: RequestOptions): Promise<AuthTokens> {
    return client().post<AuthTokens>('/auth/login', body, withMeta(options, META.login));
  },

  /**
   * The caller: account, grants, zones, allowed actions, zone metadata
   * 
   * One call on app boot instead of a permission check per widget.
   *
   * `GET /auth/me`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<CurrentActor> {
    return client().get<CurrentActor>('/auth/me', withMeta(options, META.me));
  },

  /**
   * Mint a new access token from a refresh token
   *
   * `POST /auth/refresh`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  refresh(body: RefreshRequest, options?: RequestOptions): Promise<AuthTokens> {
    return client().post<AuthTokens>('/auth/refresh', body, withMeta(options, META.refresh));
  },

  /**
   * Self-registration; creates the User and its role profile atomically
   * 
   * Only the 11 self-registerable roles. Appointed roles (founder, hqExecutive, backOfficeStaff, coordinator) are granted in Zone A. Profile creation failure rolls the User back.
   *
   * `POST /auth/register`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  register(body: RegisterRequest, options?: RequestOptions): Promise<AuthTokens> {
    return client().post<AuthTokens>('/auth/register', body, withMeta(options, META.register));
  },
};

export type AuthApi = typeof auth;
