/**
 * `blueprint` — 3 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  BlueprintResponse,
  OpenApiDocument,
  PlatformIndex,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  contract: { operationId: 'get_blueprint', method: 'GET' as const, pathTemplate: '/_blueprint', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  index: { operationId: 'getRoot', method: 'GET' as const, pathTemplate: '/', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'none' as const },
  openapi: { operationId: 'getOpenapi.json', method: 'GET' as const, pathTemplate: '/openapi.json', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'none' as const },
} satisfies Record<string, OperationMeta>;

export const blueprint = {
  /**
   * Machine-readable API contract, filtered to what the caller can reach
   * 
   * What the PWA shells build their navigation and route guards from.
   *
   * `GET /_blueprint`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  contract(options?: RequestOptions): Promise<BlueprintResponse> {
    return client().get<BlueprintResponse>('/_blueprint', withMeta(options, META.contract));
  },

  /**
   * Platform index: roles, HQ zones, mounted endpoints
   *
   * `GET /`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  index(options?: RequestOptions): Promise<PlatformIndex> {
    return client().get<PlatformIndex>('/', withMeta(options, META.index));
  },

  /**
   * The OpenAPI 3.1 document for this API
   * 
   * Generated from the same declaration as the routers. Point Swagger UI, Redoc or a client generator at it.
   *
   * `GET /openapi.json`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  openapi(options?: RequestOptions): Promise<OpenApiDocument> {
    return client().get<OpenApiDocument>('/openapi.json', withMeta(options, META.openapi));
  },
};

export type BlueprintApi = typeof blueprint;
