/**
 * `commercialClients` — 8 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Ad,
  ClientFleetVehicle,
  CommercialClient,
  CommercialClientInput,
  PortfolioAnalytics,
  Property,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  ads: { operationId: 'getCommercialClientByClientIdAds', method: 'GET' as const, pathTemplate: '/commercial-client/{clientId}/ads', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["commercialClient:read","commercialClient:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  analytics: { operationId: 'getCommercialClientByClientIdAnalytics', method: 'GET' as const, pathTemplate: '/commercial-client/{clientId}/analytics', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["commercialClient:read","commercialClient:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  create: { operationId: 'postCommercialClients', method: 'POST' as const, pathTemplate: '/commercial-clients', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["commercialClient:create"], ownership: 'none' as const, auth: 'required' as const },
  fleet: { operationId: 'getCommercialClientByClientIdFleet', method: 'GET' as const, pathTemplate: '/commercial-client/{clientId}/fleet', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["commercialClient:read","commercialClient:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  getById: { operationId: 'getCommercialClientByClientId', method: 'GET' as const, pathTemplate: '/commercial-client/{clientId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["commercialClient:read","commercialClient:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getCommercialClients', method: 'GET' as const, pathTemplate: '/commercial-clients', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["commercialClient:read"], ownership: 'scoped' as const, auth: 'required' as const },
  properties: { operationId: 'getCommercialClientByClientIdProperties', method: 'GET' as const, pathTemplate: '/commercial-client/{clientId}/properties', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["commercialClient:read","commercialClient:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchCommercialClientByClientId', method: 'PATCH' as const, pathTemplate: '/commercial-client/{clientId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["commercialClient:update"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const commercialClients = {
  /**
   * Every campaign across this client's advertiser accounts
   *
   * `GET /commercial-client/{clientId}/ads`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: commercialClient:read | commercialClient:readOwn
   * Ownership: scoped
   */
  ads(clientId: string, options?: ListOptions): Promise<Page<Ad>> {
    return client().list<Ad>(`/commercial-client/${seg(clientId)}/ads`, withMeta(options, META.ads));
  },

  /**
   * Portfolio KPIs: occupancy, revenue, fleet and campaigns
   * 
   * The composite `healthScore` averages only the dimensions the client actually has — a landlord group with no vehicles is not marked down for a fleet it does not own.
   *
   * `GET /commercial-client/{clientId}/analytics`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: commercialClient:read | commercialClient:readOwn
   * Ownership: scoped
   */
  analytics(clientId: string, options?: RequestOptions): Promise<PortfolioAnalytics> {
    return client().get<PortfolioAnalytics>(`/commercial-client/${seg(clientId)}/analytics`, withMeta(options, META.analytics));
  },

  /**
   * Open a commercial client account
   * 
   * The contracting entity above the operational profiles: one hospitality group can hold several hotel, resort and advertiser profiles.
   *
   * `POST /commercial-clients`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: commercialClient:create
   * Ownership: none
   */
  create(body: CommercialClientInput, options?: RequestOptions): Promise<CommercialClient> {
    return client().post<CommercialClient>('/commercial-clients', body, withMeta(options, META.create));
  },

  /**
   * Every vehicle across this client's rental car companies
   *
   * `GET /commercial-client/{clientId}/fleet`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: commercialClient:read | commercialClient:readOwn
   * Ownership: scoped
   */
  fleet(clientId: string, options?: ListOptions): Promise<Page<ClientFleetVehicle>> {
    return client().list<ClientFleetVehicle>(`/commercial-client/${seg(clientId)}/fleet`, withMeta(options, META.fleet));
  },

  /**
   * Read one commercial client
   *
   * `GET /commercial-client/{clientId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: commercialClient:read | commercialClient:readOwn
   * Ownership: scoped
   */
  getById(clientId: string, options?: RequestOptions): Promise<CommercialClient> {
    return client().get<CommercialClient>(`/commercial-client/${seg(clientId)}`, withMeta(options, META.getById));
  },

  /**
   * List commercial client accounts
   *
   * `GET /commercial-clients`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: commercialClient:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<CommercialClient>> {
    return client().list<CommercialClient>('/commercial-clients', withMeta(options, META.list));
  },

  /**
   * Every property this client owns, across its profiles
   * 
   * Rolls up `linkedProperties` and everything owned by a linked profile, so the account manager sees one portfolio rather than nine.
   *
   * `GET /commercial-client/{clientId}/properties`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: commercialClient:read | commercialClient:readOwn
   * Ownership: scoped
   */
  properties(clientId: string, options?: ListOptions): Promise<Page<Property>> {
    return client().list<Property>(`/commercial-client/${seg(clientId)}/properties`, withMeta(options, META.properties));
  },

  /**
   * Update a commercial client
   *
   * `PATCH /commercial-client/{clientId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: commercialClient:update
   * Ownership: scoped
   */
  update(clientId: string, body: CommercialClientInput, options?: RequestOptions): Promise<CommercialClient> {
    return client().patch<CommercialClient>(`/commercial-client/${seg(clientId)}`, body, withMeta(options, META.update));
  },
};

export type CommercialClientsApi = typeof commercialClients;
