/**
 * `coordinators` — 10 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AssignPropertiesRequest,
  Coordinator,
  CoordinatorInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  assignProperties: { operationId: 'patchCoordinatorByCoordinatorIdAssignProperties', method: 'PATCH' as const, pathTemplate: '/coordinator/{coordinatorId}/assign-properties', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:assign","coordinatorProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  create: { operationId: 'postCoordinators', method: 'POST' as const, pathTemplate: '/coordinators', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteCoordinatorByCoordinatorId', method: 'DELETE' as const, pathTemplate: '/coordinator/{coordinatorId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getCoordinatorByCoordinatorId', method: 'GET' as const, pathTemplate: '/coordinator/{coordinatorId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:read","coordinatorProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getCoordinators', method: 'GET' as const, pathTemplate: '/coordinators', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getCoordinatorMe', method: 'GET' as const, pathTemplate: '/coordinator/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","airbnbHost","hotelManager","resortManager"] as Role[], permissions: ["coordinatorProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postCoordinatorByCoordinatorIdRestore', method: 'POST' as const, pathTemplate: '/coordinator/{coordinatorId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchCoordinatorByCoordinatorId', method: 'PATCH' as const, pathTemplate: '/coordinator/{coordinatorId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:update","coordinatorProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchCoordinatorMe', method: 'PATCH' as const, pathTemplate: '/coordinator/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["coordinatorProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchCoordinatorByCoordinatorIdVerify', method: 'PATCH' as const, pathTemplate: '/coordinator/{coordinatorId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["coordinatorProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const coordinators = {
  /**
   * Post a coordinator to a set of properties
   *
   * `PATCH /coordinator/{coordinatorId}/assign-properties`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: coordinatorProfile:assign | coordinatorProfile:update
   * Ownership: none
   */
  assignProperties(coordinatorId: string, body: AssignPropertiesRequest, options?: RequestOptions): Promise<Coordinator> {
    return client().patch<Coordinator>(`/coordinator/${seg(coordinatorId)}/assign-properties`, body, withMeta(options, META.assignProperties));
  },

  /**
   * Create a coordinator profile
   *
   * `POST /coordinators`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: coordinatorProfile:create
   * Ownership: none
   */
  create(body: CoordinatorInput, options?: RequestOptions): Promise<Coordinator> {
    return client().post<Coordinator>('/coordinators', body, withMeta(options, META.create));
  },

  /**
   * Archive a coordinator profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /coordinator/{coordinatorId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: coordinatorProfile:delete
   * Ownership: none
   */
  delete(coordinatorId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/coordinator/${seg(coordinatorId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one coordinator profile
   *
   * `GET /coordinator/{coordinatorId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: coordinatorProfile:read | coordinatorProfile:readOwn
   * Ownership: scoped
   */
  getById(coordinatorId: string, options?: RequestOptions): Promise<Coordinator> {
    return client().get<Coordinator>(`/coordinator/${seg(coordinatorId)}`, withMeta(options, META.getById));
  },

  /**
   * List coordinator profiles
   *
   * `GET /coordinators`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: coordinatorProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Coordinator>> {
    return client().list<Coordinator>('/coordinators', withMeta(options, META.list));
  },

  /**
   * Read the caller's own coordinator profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /coordinator/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, airbnbHost, hotelManager, resortManager
   * Permission: coordinatorProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Coordinator> {
    return client().get<Coordinator>('/coordinator/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived coordinator profile
   *
   * `POST /coordinator/{coordinatorId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: coordinatorProfile:update
   * Ownership: none
   */
  restore(coordinatorId: string, options?: RequestOptions): Promise<Coordinator> {
    return client().post<Coordinator>(`/coordinator/${seg(coordinatorId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one coordinator profile
   *
   * `PATCH /coordinator/{coordinatorId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: coordinatorProfile:update | coordinatorProfile:updateOwn
   * Ownership: scoped
   */
  update(coordinatorId: string, body: CoordinatorInput, options?: RequestOptions): Promise<Coordinator> {
    return client().patch<Coordinator>(`/coordinator/${seg(coordinatorId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own coordinator profile
   *
   * `PATCH /coordinator/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: coordinatorProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: CoordinatorInput, options?: RequestOptions): Promise<Coordinator> {
    return client().patch<Coordinator>('/coordinator/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a coordinator profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /coordinator/{coordinatorId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: coordinatorProfile:verify
   * Ownership: none
   */
  verify(coordinatorId: string, body: VerificationRequest, options?: RequestOptions): Promise<Coordinator> {
    return client().patch<Coordinator>(`/coordinator/${seg(coordinatorId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type CoordinatorsApi = typeof coordinators;
