/**
 * `customer` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Customer,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postCustomers', method: 'POST' as const, pathTemplate: '/customers', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["customerProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteCustomerByCustomerId', method: 'DELETE' as const, pathTemplate: '/customer/{customerId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["customerProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getCustomerByCustomerId', method: 'GET' as const, pathTemplate: '/customer/{customerId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["customerProfile:read","customerProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getCustomers', method: 'GET' as const, pathTemplate: '/customers', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["customerProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getCustomerMe', method: 'GET' as const, pathTemplate: '/customer/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","customer","buyer"] as Role[], permissions: ["customerProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postCustomerByCustomerIdRestore', method: 'POST' as const, pathTemplate: '/customer/{customerId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["customerProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchCustomerByCustomerId', method: 'PATCH' as const, pathTemplate: '/customer/{customerId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["customerProfile:update","customerProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchCustomerMe', method: 'PATCH' as const, pathTemplate: '/customer/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","customer"] as Role[], permissions: ["customerProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchCustomerByCustomerIdVerify', method: 'PATCH' as const, pathTemplate: '/customer/{customerId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["customerProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const customer = {
  /**
   * Create a customer profile
   *
   * `POST /customers`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: customerProfile:create
   * Ownership: none
   */
  create(body: Customer, options?: RequestOptions): Promise<Customer> {
    return client().post<Customer>('/customers', body, withMeta(options, META.create));
  },

  /**
   * Archive a customer profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /customer/{customerId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: customerProfile:delete
   * Ownership: none
   */
  delete(customerId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/customer/${seg(customerId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one customer profile
   *
   * `GET /customer/{customerId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: customerProfile:read | customerProfile:readOwn
   * Ownership: scoped
   */
  getById(customerId: string, options?: RequestOptions): Promise<Customer> {
    return client().get<Customer>(`/customer/${seg(customerId)}`, withMeta(options, META.getById));
  },

  /**
   * List customer profiles
   *
   * `GET /customers`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: customerProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Customer>> {
    return client().list<Customer>('/customers', withMeta(options, META.list));
  },

  /**
   * Read the caller's own customer profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /customer/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, customer, buyer
   * Permission: customerProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Customer> {
    return client().get<Customer>('/customer/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived customer profile
   *
   * `POST /customer/{customerId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: customerProfile:update
   * Ownership: none
   */
  restore(customerId: string, options?: RequestOptions): Promise<Customer> {
    return client().post<Customer>(`/customer/${seg(customerId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one customer profile
   *
   * `PATCH /customer/{customerId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: customerProfile:update | customerProfile:updateOwn
   * Ownership: scoped
   */
  update(customerId: string, body: Customer, options?: RequestOptions): Promise<Customer> {
    return client().patch<Customer>(`/customer/${seg(customerId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own customer profile
   *
   * `PATCH /customer/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, customer
   * Permission: customerProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: Customer, options?: RequestOptions): Promise<Customer> {
    return client().patch<Customer>('/customer/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a customer profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /customer/{customerId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: customerProfile:verify
   * Ownership: none
   */
  verify(customerId: string, body: VerificationRequest, options?: RequestOptions): Promise<Customer> {
    return client().patch<Customer>(`/customer/${seg(customerId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type CustomerApi = typeof customer;
