/**
 * `documents` — 17 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Document,
  DocumentAnalytics,
  DocumentInput,
  DocumentLifecycle,
  DocumentPatch,
  DocumentVerificationSummary,
  DocumentWithExpiry,
  ExpireDocumentRequest,
  RejectDocumentRequest,
  RequestInfoRequest,
  ReverifyDocumentRequest,
  ReviewDocumentRequest,
  SubmitDocumentRequest,
  VerifyDocumentRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  analytics: { operationId: 'getHqDocumentsAnalytics', method: 'GET' as const, pathTemplate: '/hq/documents/analytics', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["document:read"], ownership: 'none' as const, auth: 'required' as const },
  create: { operationId: 'postDocuments', method: 'POST' as const, pathTemplate: '/documents', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer"] as Role[], permissions: ["document:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteDocumentByDocumentId', method: 'DELETE' as const, pathTemplate: '/document/{documentId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder"] as Role[], permissions: ["document:delete"], ownership: 'scoped' as const, auth: 'required' as const },
  expire: { operationId: 'postDocumentByDocumentIdExpire', method: 'POST' as const, pathTemplate: '/document/{documentId}/expire', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:update","document:review"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getDocumentByDocumentId', method: 'GET' as const, pathTemplate: '/document/{documentId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer"] as Role[], permissions: ["document:read","document:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getDocuments', method: 'GET' as const, pathTemplate: '/documents', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:read"], ownership: 'scoped' as const, auth: 'required' as const },
  listAll: { operationId: 'getHqDocuments', method: 'GET' as const, pathTemplate: '/hq/documents', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["document:read"], ownership: 'none' as const, auth: 'required' as const },
  mine: { operationId: 'getMemberMeDocuments', method: 'GET' as const, pathTemplate: '/member/me/documents', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer"] as Role[], permissions: ["document:readOwn","document:read"], ownership: 'self' as const, auth: 'required' as const },
  queue: { operationId: 'getStaffMeDocumentQueue', method: 'GET' as const, pathTemplate: '/staff/me/document-queue', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:review","document:read"], ownership: 'self' as const, auth: 'required' as const },
  reject: { operationId: 'postDocumentByDocumentIdReject', method: 'POST' as const, pathTemplate: '/document/{documentId}/reject', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:review","document:update"], ownership: 'none' as const, auth: 'required' as const },
  requestInfo: { operationId: 'postDocumentByDocumentIdRequestInfo', method: 'POST' as const, pathTemplate: '/document/{documentId}/request-info', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:review","document:update"], ownership: 'none' as const, auth: 'required' as const },
  reverify: { operationId: 'postDocumentByDocumentIdReverify', method: 'POST' as const, pathTemplate: '/document/{documentId}/reverify', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:verify","document:review"], ownership: 'none' as const, auth: 'required' as const },
  review: { operationId: 'postDocumentByDocumentIdReview', method: 'POST' as const, pathTemplate: '/document/{documentId}/review', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:review","document:update"], ownership: 'none' as const, auth: 'required' as const },
  submit: { operationId: 'postDocumentByDocumentIdSubmit', method: 'POST' as const, pathTemplate: '/document/{documentId}/submit', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer"] as Role[], permissions: ["document:create","document:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchDocumentByDocumentId', method: 'PATCH' as const, pathTemplate: '/document/{documentId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant"] as Role[], permissions: ["document:update","document:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  verificationSummary: { operationId: 'getDocumentByDocumentIdVerificationSummary', method: 'GET' as const, pathTemplate: '/document/{documentId}/verification-summary', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:read","document:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  verify: { operationId: 'postDocumentByDocumentIdVerify', method: 'POST' as const, pathTemplate: '/document/{documentId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["document:verify","document:review"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const documents = {
  /**
   * Verification throughput and backlog
   * 
   * The four numbers HQ actually asks for: how much is waiting, how long it has waited, how much is lapsing, and how often the answer is no.
   *
   * `GET /hq/documents/analytics`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: document:read
   * Ownership: none
   */
  analytics(options?: RequestOptions): Promise<DocumentAnalytics> {
    return client().get<DocumentAnalytics>('/hq/documents/analytics', withMeta(options, META.analytics));
  },

  /**
   * Upload a piece of evidence
   * 
   * Fields are validated against the type's rules before anything is written; an unexpected field is rejected rather than dropped. The desk, the expiry date and the first score are all derived here, so a document is never queued without knowing who reviews it or when it lapses.
   *
   * `POST /documents`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer
   * Permission: document:create
   * Ownership: none
   */
  create(body: DocumentInput, options?: RequestOptions): Promise<Document> {
    return client().post<Document>('/documents', body, withMeta(options, META.create));
  },

  /**
   * Archive a document
   * 
   * Refused on a verified record: evidence somebody relied on is not the holder’s to remove. Withdrawing it is an HQ act through the audit trail.
   *
   * `DELETE /document/{documentId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder
   * Permission: document:delete
   * Ownership: scoped
   */
  delete(documentId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/document/${seg(documentId)}`, withMeta(options, META.delete));
  },

  /**
   * Mark a lapsed document expired
   * 
   * The clock's doing rather than a person's, so no reviewer is required — but still audited. Refused while the document is in date: expiring something early would be a policy decision dressed up as bookkeeping.
   *
   * `POST /document/{documentId}/expire`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:update | document:review
   * Ownership: none
   */
  expire(documentId: string, body: ExpireDocumentRequest, options?: RequestOptions): Promise<DocumentLifecycle> {
    return client().post<DocumentLifecycle>(`/document/${seg(documentId)}/expire`, body, withMeta(options, META.expire));
  },

  /**
   * Read one document
   * 
   * `storageKey` is `select: false` and never returned; a signed URL is minted on demand.
   *
   * `GET /document/{documentId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer
   * Permission: document:read | document:readOwn
   * Ownership: scoped
   */
  getById(documentId: string, options?: RequestOptions): Promise<Document> {
    return client().get<Document>(`/document/${seg(documentId)}`, withMeta(options, META.getById));
  },

  /**
   * List documents
   *
   * `GET /documents`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Document>> {
    return client().list<Document>('/documents', withMeta(options, META.list));
  },

  /**
   * Every document on the platform
   *
   * `GET /hq/documents`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: document:read
   * Ownership: none
   */
  listAll(options?: ListOptions): Promise<Page<Document>> {
    return client().list<Document>('/hq/documents', withMeta(options, META.listAll));
  },

  /**
   * The caller's own documents, with each one's clock
   *
   * `GET /member/me/documents`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer
   * Permission: document:readOwn | document:read
   * Ownership: self
   */
  mine(options?: ListOptions): Promise<Page<DocumentWithExpiry>> {
    return client().list<DocumentWithExpiry>('/member/me/documents', withMeta(options, META.mine));
  },

  /**
   * The reviewer's own queue, oldest first
   * 
   * Narrowed to the desks the caller’s role actually reviews — a coordinator should not be looking at criminal record checks — and ordered oldest first, because a verification queue sorted any other way starves its tail.
   *
   * `GET /staff/me/document-queue`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:review | document:read
   * Ownership: self
   */
  queue(options?: ListOptions): Promise<Page<Document>> {
    return client().list<Document>('/staff/me/document-queue', withMeta(options, META.queue));
  },

  /**
   * Refuse the document
   * 
   * The decision most likely to be challenged, so it is unusable without a stated reason and an audit entry naming who made it.
   *
   * `POST /document/{documentId}/reject`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:review | document:update
   * Ownership: none
   */
  reject(documentId: string, body: RejectDocumentRequest, options?: RequestOptions): Promise<DocumentLifecycle> {
    return client().post<DocumentLifecycle>(`/document/${seg(documentId)}/reject`, body, withMeta(options, META.reject));
  },

  /**
   * Ask the holder for what is missing
   * 
   * A reason is mandatory: asking for more without saying what is how a verification queue stalls. 422 without one.
   *
   * `POST /document/{documentId}/request-info`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:review | document:update
   * Ownership: none
   */
  requestInfo(documentId: string, body: RequestInfoRequest, options?: RequestOptions): Promise<DocumentLifecycle> {
    return client().post<DocumentLifecycle>(`/document/${seg(documentId)}/request-info`, body, withMeta(options, META.requestInfo));
  },

  /**
   * Reopen a document for re-verification
   * 
   * Where it lands depends on the type: one flagged `reverifyOnExpiry` re-enters review, because a lapsed criminal record check is not renewed by re-uploading the same PDF. Everything else goes back to the holder for a fresh copy.
   *
   * `POST /document/{documentId}/reverify`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:verify | document:review
   * Ownership: none
   */
  reverify(documentId: string, body: ReverifyDocumentRequest, options?: RequestOptions): Promise<DocumentLifecycle> {
    return client().post<DocumentLifecycle>(`/document/${seg(documentId)}/reverify`, body, withMeta(options, META.reverify));
  },

  /**
   * Take the document into review
   * 
   * Claims it for a desk so two reviewers do not both start on it.
   *
   * `POST /document/{documentId}/review`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:review | document:update
   * Ownership: none
   */
  review(documentId: string, body: ReviewDocumentRequest, options?: RequestOptions): Promise<DocumentLifecycle> {
    return client().post<DocumentLifecycle>(`/document/${seg(documentId)}/review`, body, withMeta(options, META.review));
  },

  /**
   * Submit or re-submit for review
   * 
   * The one transition the holder performs on their own document. A re-submission bumps the version so the new scan is a new storage key and the reviewer can still see what they turned down.
   *
   * `POST /document/{documentId}/submit`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer
   * Permission: document:create | document:updateOwn
   * Ownership: scoped
   */
  submit(documentId: string, body: SubmitDocumentRequest, options?: RequestOptions): Promise<DocumentLifecycle> {
    return client().post<DocumentLifecycle>(`/document/${seg(documentId)}/submit`, body, withMeta(options, META.submit));
  },

  /**
   * Amend a document
   * 
   * A verified document freezes its identity — type, holder, number, dates. Those are what somebody signed off on; letting them change afterwards would make "verified" mean only that something was verified once. Returns 409 on a locked field.
   *
   * `PATCH /document/{documentId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant
   * Permission: document:update | document:updateOwn
   * Ownership: scoped
   */
  update(documentId: string, body: DocumentPatch, options?: RequestOptions): Promise<Document> {
    return client().patch<Document>(`/document/${seg(documentId)}`, body, withMeta(options, META.update));
  },

  /**
   * Lifecycle, score, compliance and expiry in one read
   * 
   * What a reviewer’s verify button reads. `verifiable` is the AND of all four inputs, with each shown beside it.
   *
   * `GET /document/{documentId}/verification-summary`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:read | document:readOwn
   * Ownership: scoped
   */
  verificationSummary(documentId: string, options?: RequestOptions): Promise<DocumentVerificationSummary> {
    return client().get<DocumentVerificationSummary>(`/document/${seg(documentId)}/verification-summary`, withMeta(options, META.verificationSummary));
  },

  /**
   * Verify the document
   * 
   * The only gated transition, gated twice: compliance must be clear of blocking failures (an advisory one may be overridden by a reviewer who has read it, a blocking one never), and the score must clear the floor. Freezes the evidence in object storage on success. A reviewer may not verify their own submission.
   *
   * `POST /document/{documentId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: document:verify | document:review
   * Ownership: none
   */
  verify(documentId: string, body: VerifyDocumentRequest, options?: RequestOptions): Promise<DocumentLifecycle> {
    return client().post<DocumentLifecycle>(`/document/${seg(documentId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type DocumentsApi = typeof documents;
