/**
 * `drivers` — 11 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Driver,
  DriverInput,
  DriverOnlineRequest,
  DriverVerificationQueue,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postDrivers', method: 'POST' as const, pathTemplate: '/drivers', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["driverProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteDriverByDriverId', method: 'DELETE' as const, pathTemplate: '/driver/{driverId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["driverProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getDriverByDriverId', method: 'GET' as const, pathTemplate: '/driver/{driverId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["driverProfile:read","driverProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getDrivers', method: 'GET' as const, pathTemplate: '/drivers', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["driverProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getDriverMe', method: 'GET' as const, pathTemplate: '/driver/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","rentalCarCompany","driver","rider"] as Role[], permissions: ["driverProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postDriverByDriverIdRestore', method: 'POST' as const, pathTemplate: '/driver/{driverId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["driverProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  setOnline: { operationId: 'patchDriverMeOnline', method: 'PATCH' as const, pathTemplate: '/driver/me/online', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","driver"] as Role[], permissions: ["driverProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  update: { operationId: 'patchDriverByDriverId', method: 'PATCH' as const, pathTemplate: '/driver/{driverId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["driverProfile:update","driverProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchDriverMe', method: 'PATCH' as const, pathTemplate: '/driver/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","driver"] as Role[], permissions: ["driverProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verificationQueue: { operationId: 'getDriversVerificationQueue', method: 'GET' as const, pathTemplate: '/drivers/verification-queue', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["driverProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
  verify: { operationId: 'patchDriverByDriverIdVerify', method: 'PATCH' as const, pathTemplate: '/driver/{driverId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["driverProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const drivers = {
  /**
   * Create a driver profile
   *
   * `POST /drivers`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: driverProfile:create
   * Ownership: none
   */
  create(body: DriverInput, options?: RequestOptions): Promise<Driver> {
    return client().post<Driver>('/drivers', body, withMeta(options, META.create));
  },

  /**
   * Archive a driver profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /driver/{driverId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: driverProfile:delete
   * Ownership: none
   */
  delete(driverId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/driver/${seg(driverId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one driver profile
   *
   * `GET /driver/{driverId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: driverProfile:read | driverProfile:readOwn
   * Ownership: scoped
   */
  getById(driverId: string, options?: RequestOptions): Promise<Driver> {
    return client().get<Driver>(`/driver/${seg(driverId)}`, withMeta(options, META.getById));
  },

  /**
   * List driver profiles
   *
   * `GET /drivers`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: driverProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Driver>> {
    return client().list<Driver>('/drivers', withMeta(options, META.list));
  },

  /**
   * Read the caller's own driver profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /driver/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, rentalCarCompany, driver, rider
   * Permission: driverProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Driver> {
    return client().get<Driver>('/driver/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived driver profile
   *
   * `POST /driver/{driverId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: driverProfile:update
   * Ownership: none
   */
  restore(driverId: string, options?: RequestOptions): Promise<Driver> {
    return client().post<Driver>(`/driver/${seg(driverId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Driver goes online or offline, optionally with a position
   * 
   * Also gated by `requireAction("goOnline")`. Refuses unless verificationStatus is verified.
   *
   * `PATCH /driver/me/online`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, driver
   * Permission: driverProfile:updateOwn
   * Ownership: self
   */
  setOnline(body: DriverOnlineRequest, options?: RequestOptions): Promise<Driver> {
    return client().patch<Driver>('/driver/me/online', body, withMeta(options, META.setOnline));
  },

  /**
   * Update one driver profile
   *
   * `PATCH /driver/{driverId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: driverProfile:update | driverProfile:updateOwn
   * Ownership: scoped
   */
  update(driverId: string, body: DriverInput, options?: RequestOptions): Promise<Driver> {
    return client().patch<Driver>(`/driver/${seg(driverId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own driver profile
   *
   * `PATCH /driver/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, driver
   * Permission: driverProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: DriverInput, options?: RequestOptions): Promise<Driver> {
    return client().patch<Driver>('/driver/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Drivers pending verification or with documents expiring inside 30 days
   * 
   * Registered before /:id so the literal segment is not swallowed by the id route.
   *
   * `GET /drivers/verification-queue`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: driverProfile:verify
   * Ownership: none
   */
  verificationQueue(options?: RequestOptions): Promise<DriverVerificationQueue> {
    return client().get<DriverVerificationQueue>('/drivers/verification-queue', withMeta(options, META.verificationQueue));
  },

  /**
   * Advance verification on a driver profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /driver/{driverId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: driverProfile:verify
   * Ownership: none
   */
  verify(driverId: string, body: VerificationRequest, options?: RequestOptions): Promise<Driver> {
    return client().patch<Driver>(`/driver/${seg(driverId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type DriversApi = typeof drivers;
