/**
 * `evidence` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Dispute,
  DisputeEvidenceView,
  OpenDisputeRequest,
  Reference,
  ReferenceEvidenceView,
  RequestReferenceRequest,
  ResolveMemberDisputeRequest,
  RespondToReferenceRequest,
  UsusuContributionRequest,
  UsusuEntry,
  UsusuEvidenceView,
  UsusuMissRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  contribute: { operationId: 'postUsusuContribute', method: 'POST' as const, pathTemplate: '/ususu/contribute', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  get: { operationId: 'getDisputesBySubjectId', method: 'GET' as const, pathTemplate: '/disputes/{subjectId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["dispute:readOwn","dispute:read"], ownership: 'scoped' as const, auth: 'required' as const },
  get2: { operationId: 'getUsusuBySubjectId', method: 'GET' as const, pathTemplate: '/ususu/{subjectId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["ususuLedger:readOwn","ususuLedger:read"], ownership: 'scoped' as const, auth: 'required' as const },
  getById: { operationId: 'getReferencesBySubjectId', method: 'GET' as const, pathTemplate: '/references/{subjectId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["reference:readOwn","reference:read"], ownership: 'scoped' as const, auth: 'required' as const },
  miss: { operationId: 'postUsusuMiss', method: 'POST' as const, pathTemplate: '/ususu/miss', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  open: { operationId: 'postDisputesOpen', method: 'POST' as const, pathTemplate: '/disputes/open', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["dispute:create"], ownership: 'none' as const, auth: 'required' as const },
  request: { operationId: 'postReferencesRequest', method: 'POST' as const, pathTemplate: '/references/request', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["reference:create"], ownership: 'none' as const, auth: 'required' as const },
  resolve: { operationId: 'postDisputeByDisputeIdResolve', method: 'POST' as const, pathTemplate: '/dispute/{disputeId}/resolve', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["dispute:approve"], ownership: 'scoped' as const, auth: 'required' as const },
  respond: { operationId: 'postReferencesRespond', method: 'POST' as const, pathTemplate: '/references/respond', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["reference:update"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const evidence = {
  /**
   * Record an Ususu contribution
   * 
   * One line per person per period per kind. A month recorded twice would inflate a streak nobody earned.
   *
   * `POST /ususu/contribute`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  contribute(body: UsusuContributionRequest, options?: RequestOptions): Promise<UsusuEntry> {
    return client().post<UsusuEntry>('/ususu/contribute', body, withMeta(options, META.contribute));
  },

  /**
   * Disputes about one person
   *
   * `GET /disputes/{subjectId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: dispute:readOwn | dispute:read
   * Ownership: scoped
   */
  get(subjectId: string, options?: RequestOptions): Promise<DisputeEvidenceView> {
    return client().get<DisputeEvidenceView>(`/disputes/${seg(subjectId)}`, withMeta(options, META.get));
  },

  /**
   * The Ususu ledger for one person
   * 
   * Streak and group health are computed from the ledger on read, never stored — a running total is a number somebody can correct by hand.
   *
   * `GET /ususu/{subjectId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: ususuLedger:readOwn | ususuLedger:read
   * Ownership: scoped
   */
  get2(subjectId: string, options?: RequestOptions): Promise<UsusuEvidenceView> {
    return client().get<UsusuEvidenceView>(`/ususu/${seg(subjectId)}`, withMeta(options, META.get2));
  },

  /**
   * References about one person
   * 
   * Your own, or anybody’s if you are staff. A landlord sees the assessment, not the referee comments behind it.
   *
   * `GET /references/{subjectId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: reference:readOwn | reference:read
   * Ownership: scoped
   */
  getById(subjectId: string, options?: RequestOptions): Promise<ReferenceEvidenceView> {
    return client().get<ReferenceEvidenceView>(`/references/${seg(subjectId)}`, withMeta(options, META.getById));
  },

  /**
   * Record a missed Ususu contribution
   *
   * `POST /ususu/miss`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  miss(body: UsusuMissRequest, options?: RequestOptions): Promise<UsusuEntry> {
    return client().post<UsusuEntry>('/ususu/miss', body, withMeta(options, META.miss));
  },

  /**
   * Raise a dispute against somebody
   * 
   * Severity 1–3, set when opened. An open dispute blocks a tenancy recommendation whatever its grade.
   *
   * `POST /disputes/open`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: dispute:create
   * Ownership: none
   */
  open(body: OpenDisputeRequest, options?: RequestOptions): Promise<Dispute> {
    return client().post<Dispute>('/disputes/open', body, withMeta(options, META.open));
  },

  /**
   * Ask somebody for a reference
   * 
   * LRMC asks; the subject cannot request their own, because then they choose the referee.
   *
   * `POST /references/request`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: reference:create
   * Ownership: none
   */
  request(body: RequestReferenceRequest, options?: RequestOptions): Promise<Reference> {
    return client().post<Reference>('/references/request', body, withMeta(options, META.request));
  },

  /**
   * Close a dispute
   * 
   * Not by its subject: an open dispute blocks them, and closing your own block is not a thing.
   *
   * `POST /dispute/{disputeId}/resolve`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff
   * Permission: dispute:approve
   * Ownership: scoped
   */
  resolve(disputeId: string, body: ResolveMemberDisputeRequest, options?: RequestOptions): Promise<Dispute> {
    return client().post<Dispute>(`/dispute/${seg(disputeId)}/resolve`, body, withMeta(options, META.resolve));
  },

  /**
   * Answer a reference request
   * 
   * Nobody scores their own. A referee who will not score is a decline, not a zero.
   *
   * `POST /references/respond`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: reference:update
   * Ownership: none
   */
  respond(body: RespondToReferenceRequest, options?: RequestOptions): Promise<Reference> {
    return client().post<Reference>('/references/respond', body, withMeta(options, META.respond));
  },
};

export type EvidenceApi = typeof evidence;
