/**
 * `evidence` — 17 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  CreateUsusuGroupRequest,
  Dispute,
  DisputeEvidenceView,
  OpenDisputeRequest,
  Reference,
  ReferenceEvidenceView,
  RequestReferenceRequest,
  ResolveMemberDisputeRequest,
  RespondToReferenceRequest,
  UsusuContributionRequest,
  UsusuEntry,
  UsusuEvidenceView,
  UsusuGroup,
  UsusuGroupContributionRequest,
  UsusuGroupMemberRequest,
  UsusuGroupMissRequest,
  UsusuGroupSummary,
  UsusuMissRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  contribute: { operationId: 'postUsusuContribute', method: 'POST' as const, pathTemplate: '/ususu/contribute', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  createGroup: { operationId: 'postUsusuGroupCreate', method: 'POST' as const, pathTemplate: '/ususu/group/create', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  disputesFor: { operationId: 'getDisputesBySubjectId', method: 'GET' as const, pathTemplate: '/disputes/{subjectId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["dispute:readOwn","dispute:read"], ownership: 'scoped' as const, auth: 'required' as const },
  getById: { operationId: 'getReferencesBySubjectId', method: 'GET' as const, pathTemplate: '/references/{subjectId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["reference:readOwn","reference:read"], ownership: 'scoped' as const, auth: 'required' as const },
  groupAddMember: { operationId: 'postUsusuGroupAddMember', method: 'POST' as const, pathTemplate: '/ususu/group/add-member', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  groupContribute: { operationId: 'postUsusuGroupContribute', method: 'POST' as const, pathTemplate: '/ususu/group/contribute', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  groupMiss: { operationId: 'postUsusuGroupMiss', method: 'POST' as const, pathTemplate: '/ususu/group/miss', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  groupRemoveMember: { operationId: 'postUsusuGroupRemoveMember', method: 'POST' as const, pathTemplate: '/ususu/group/remove-member', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  groupsForUser: { operationId: 'getUsusuGroupUserByUserId', method: 'GET' as const, pathTemplate: '/ususu/group/user/{userId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer"] as Role[], permissions: [], ownership: 'scoped' as const, auth: 'required' as const },
  groupSummary: { operationId: 'getUsusuGroupByGroupIdSummary', method: 'GET' as const, pathTemplate: '/ususu/group/{groupId}/summary', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer"] as Role[], permissions: [], ownership: 'scoped' as const, auth: 'required' as const },
  miss: { operationId: 'postUsusuMiss', method: 'POST' as const, pathTemplate: '/ususu/miss', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["ususuLedger:create"], ownership: 'none' as const, auth: 'required' as const },
  open: { operationId: 'postDisputesOpen', method: 'POST' as const, pathTemplate: '/disputes/open', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["dispute:create"], ownership: 'none' as const, auth: 'required' as const },
  readGroup: { operationId: 'getUsusuGroupByGroupId', method: 'GET' as const, pathTemplate: '/ususu/group/{groupId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer"] as Role[], permissions: [], ownership: 'scoped' as const, auth: 'required' as const },
  request: { operationId: 'postReferencesRequest', method: 'POST' as const, pathTemplate: '/references/request', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["reference:create"], ownership: 'none' as const, auth: 'required' as const },
  resolve: { operationId: 'postDisputeByDisputeIdResolve', method: 'POST' as const, pathTemplate: '/dispute/{disputeId}/resolve', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["dispute:approve"], ownership: 'scoped' as const, auth: 'required' as const },
  respond: { operationId: 'postReferencesRespond', method: 'POST' as const, pathTemplate: '/references/respond', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["reference:update"], ownership: 'none' as const, auth: 'required' as const },
  ususuFor: { operationId: 'getUsusuBySubjectId', method: 'GET' as const, pathTemplate: '/ususu/{subjectId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["ususuLedger:readOwn","ususuLedger:read"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const evidence = {
  /**
   * Record an Ususu contribution
   * 
   * One line per person per period per kind. A month recorded twice would inflate a streak nobody earned.
   *
   * `POST /ususu/contribute`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  contribute(body: UsusuContributionRequest, options?: RequestOptions): Promise<UsusuEntry> {
    return client().post<UsusuEntry>('/ususu/contribute', body, withMeta(options, META.contribute));
  },

  /**
   * Open a rotating savings circle
   * 
   * Coordinators and LRMC only — an ordinary member cannot open a circle on the platform. Always lands in `forming`; a circle created already `active` would be a claim that people have agreed to put money in. The steward is added to their own register from the first second, so "who is in this" and "who is answerable for this" cannot drift apart. `status`, `groupHealth` and any streak are refused by the strict schema: all three are derived from the ledger and none is stored.
   *
   * `POST /ususu/group/create`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  createGroup(body: CreateUsusuGroupRequest, options?: RequestOptions): Promise<UsusuGroup> {
    return client().post<UsusuGroup>('/ususu/group/create', body, withMeta(options, META.createGroup));
  },

  /**
   * Disputes about one person
   *
   * `GET /disputes/{subjectId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: dispute:readOwn | dispute:read
   * Ownership: scoped
   */
  disputesFor(subjectId: string, options?: RequestOptions): Promise<DisputeEvidenceView> {
    return client().get<DisputeEvidenceView>(`/disputes/${seg(subjectId)}`, withMeta(options, META.disputesFor));
  },

  /**
   * References about one person
   * 
   * Your own, or anybody’s if you are staff. A landlord sees the assessment, not the referee comments behind it.
   *
   * `GET /references/{subjectId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: reference:readOwn | reference:read
   * Ownership: scoped
   */
  getById(subjectId: string, options?: RequestOptions): Promise<ReferenceEvidenceView> {
    return client().get<ReferenceEvidenceView>(`/references/${seg(subjectId)}`, withMeta(options, META.getById));
  },

  /**
   * Add somebody to a circle
   * 
   * The steward who runs the circle, or LRMC. Not an ordinary member: a circle where anybody can add anybody is one where a disagreement is settled by whoever reaches their phone first. A closed circle refuses — its register is history, and adding somebody to a finished round would credit them with contributions they never made.
   *
   * `POST /ususu/group/add-member`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  groupAddMember(body: UsusuGroupMemberRequest, options?: RequestOptions): Promise<UsusuGroup> {
    return client().post<UsusuGroup>('/ususu/group/add-member', body, withMeta(options, META.groupAddMember));
  },

  /**
   * Record a contribution to a circle
   * 
   * NOBODY RECORDS THEIR OWN CONTRIBUTION. Same rule as every other kind of evidence: a contribution somebody wrote down about themselves is a claim, not a record, and it is the one claim nobody else can check. Without it the fastest route to a high Ususu score is to open a circle and pay yourself on paper. `period` is required and shaped YYYY-MM — it is what a streak is counted over and what makes a duplicate detectable. A second entry for the same member, circle and period is a 409 for a person to resolve, never silently accepted. Recording the first contribution moves a `forming` circle to `active`.
   *
   * `POST /ususu/group/contribute`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  groupContribute(body: UsusuGroupContributionRequest, options?: RequestOptions): Promise<UsusuEntry> {
    return client().post<UsusuEntry>('/ususu/group/contribute', body, withMeta(options, META.groupContribute));
  },

  /**
   * Record a missed contribution
   * 
   * Resets that member's streak, because a streak is consecutive contributions counting back from the latest period and a miss ends the run. Costs the circle 5 points of group health. Same self-recording rule as a contribution — and it matters more here, because a member who could record their own misses could also decline to.
   *
   * `POST /ususu/group/miss`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  groupMiss(body: UsusuGroupMissRequest, options?: RequestOptions): Promise<UsusuEntry> {
    return client().post<UsusuEntry>('/ususu/group/miss', body, withMeta(options, META.groupMiss));
  },

  /**
   * Remove somebody from a circle
   * 
   * REMOVING A MEMBER NEVER DELETES THEIR CONTRIBUTIONS. Somebody who paid into a circle for a year and then left has a year of evidence; the register changes and the append-only ledger does not. The steward cannot be removed from their own circle — close it instead, because there is no succession and a circle with no keeper is a register nobody can manage.
   *
   * `POST /ususu/group/remove-member`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  groupRemoveMember(body: UsusuGroupMemberRequest, options?: RequestOptions): Promise<UsusuGroup> {
    return client().post<UsusuGroup>('/ususu/group/remove-member', body, withMeta(options, META.groupRemoveMember));
  },

  /**
   * The circles one person is in
   * 
   * A person reads their own; Back Office, HQ and the founder read anyone's. A COORDINATOR READS NOBODY ELSE'S — this is narrower than a coordinator's reach anywhere else on the platform, deliberately. A savings circle is a private financial arrangement between named people, and stewarding one in Serrekunda is no reason to read the register of one in Basse.
   *
   * `GET /ususu/group/user/{userId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer
   * Ownership: scoped
   */
  groupsForUser(userId: string, options?: RequestOptions): Promise<UsusuGroup[]> {
    return client().get<UsusuGroup[]>(`/ususu/group/user/${seg(userId)}`, withMeta(options, META.groupsForUser));
  },

  /**
   * A circle's health, streaks and contribution history
   * 
   * Computed over the whole ledger, never a page — a group health over twenty rows reads as a group health over a history. `groupHealth` is 100 minus five per miss, floored at zero, and is NULL when nobody has contributed yet: a circle formed on Tuesday is not in perfect health and is not in bad health, it has no health to report. Streaks are counted BACKWARDS from the latest period; counting forwards returns the length of somebody's first good run, so a member who missed once in month seven and has paid for two years since would be reported with a streak of six. Money is grouped by currency and never summed.
   *
   * `GET /ususu/group/{groupId}/summary`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer
   * Ownership: scoped
   */
  groupSummary(groupId: string, options?: RequestOptions): Promise<UsusuGroupSummary> {
    return client().get<UsusuGroupSummary>(`/ususu/group/${seg(groupId)}/summary`, withMeta(options, META.groupSummary));
  },

  /**
   * Record a missed Ususu contribution
   *
   * `POST /ususu/miss`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: ususuLedger:create
   * Ownership: none
   */
  miss(body: UsusuMissRequest, options?: RequestOptions): Promise<UsusuEntry> {
    return client().post<UsusuEntry>('/ususu/miss', body, withMeta(options, META.miss));
  },

  /**
   * Raise a dispute against somebody
   * 
   * Severity 1–3, set when opened. An open dispute blocks a tenancy recommendation whatever its grade.
   *
   * `POST /disputes/open`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: dispute:create
   * Ownership: none
   */
  open(body: OpenDisputeRequest, options?: RequestOptions): Promise<Dispute> {
    return client().post<Dispute>('/disputes/open', body, withMeta(options, META.open));
  },

  /**
   * One circle's register
   * 
   * The steward, the members, and LRMC. Anybody else is refused rather than answered with an empty object.
   *
   * `GET /ususu/group/{groupId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer
   * Ownership: scoped
   */
  readGroup(groupId: string, options?: RequestOptions): Promise<UsusuGroup> {
    return client().get<UsusuGroup>(`/ususu/group/${seg(groupId)}`, withMeta(options, META.readGroup));
  },

  /**
   * Ask somebody for a reference
   * 
   * LRMC asks; the subject cannot request their own, because then they choose the referee.
   *
   * `POST /references/request`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: reference:create
   * Ownership: none
   */
  request(body: RequestReferenceRequest, options?: RequestOptions): Promise<Reference> {
    return client().post<Reference>('/references/request', body, withMeta(options, META.request));
  },

  /**
   * Close a dispute
   * 
   * Not by its subject: an open dispute blocks them, and closing your own block is not a thing.
   *
   * `POST /dispute/{disputeId}/resolve`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff
   * Permission: dispute:approve
   * Ownership: scoped
   */
  resolve(disputeId: string, body: ResolveMemberDisputeRequest, options?: RequestOptions): Promise<Dispute> {
    return client().post<Dispute>(`/dispute/${seg(disputeId)}/resolve`, body, withMeta(options, META.resolve));
  },

  /**
   * Answer a reference request
   * 
   * Nobody scores their own. A referee who will not score is a decline, not a zero.
   *
   * `POST /references/respond`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: reference:update
   * Ownership: none
   */
  respond(body: RespondToReferenceRequest, options?: RequestOptions): Promise<Reference> {
    return client().post<Reference>('/references/respond', body, withMeta(options, META.respond));
  },

  /**
   * The Ususu ledger for one person
   * 
   * Streak and group health are computed from the ledger on read, never stored — a running total is a number somebody can correct by hand.
   *
   * `GET /ususu/{subjectId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: ususuLedger:readOwn | ususuLedger:read
   * Ownership: scoped
   */
  ususuFor(subjectId: string, options?: RequestOptions): Promise<UsusuEvidenceView> {
    return client().get<UsusuEvidenceView>(`/ususu/${seg(subjectId)}`, withMeta(options, META.ususuFor));
  },
};

export type EvidenceApi = typeof evidence;
