/**
 * `fac` — 11 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  ClearLockoutRequest,
  FacAttempt,
  FacClearanceRevocation,
  FacClearanceState,
  FacCode,
  FacIssuance,
  FacLockoutClear,
  FacLockoutList,
  FacResetRequest,
  FacResetRequestBody,
  FacRevocation,
  FacVerification,
  IssueFacCodeRequest,
  RevokeFacCodeRequest,
  VerifyFacCodeRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  attempts: { operationId: 'getFacAttempts', method: 'GET' as const, pathTemplate: '/fac/attempts', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["fac:read"], ownership: 'none' as const, auth: 'required' as const },
  clearance: { operationId: 'getFacMeClearance', method: 'GET' as const, pathTemplate: '/fac/me/clearance', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["fac:verify","fac:read"], ownership: 'self' as const, auth: 'required' as const },
  getGeneration: { operationId: 'getFacCodeByCodeId', method: 'GET' as const, pathTemplate: '/fac-code/{codeId}', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["fac:read"], ownership: 'none' as const, auth: 'required' as const },
  issue: { operationId: 'postFacCodes', method: 'POST' as const, pathTemplate: '/fac-codes', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["fac:create"], ownership: 'none' as const, auth: 'required' as const },
  listGenerations: { operationId: 'getFacCodes', method: 'GET' as const, pathTemplate: '/fac-codes', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["fac:read"], ownership: 'none' as const, auth: 'required' as const },
  lockoutClear: { operationId: 'postFacLockoutByActorIdClear', method: 'POST' as const, pathTemplate: '/fac/lockout/{actorId}/clear', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["fac:update","fac:create"], ownership: 'none' as const, auth: 'required' as const },
  lockouts: { operationId: 'getFacLockouts', method: 'GET' as const, pathTemplate: '/fac/lockouts', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["fac:read"], ownership: 'none' as const, auth: 'required' as const },
  requestReset: { operationId: 'postFacResetRequests', method: 'POST' as const, pathTemplate: '/fac/reset-requests', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["fac:verify","fac:read"], ownership: 'none' as const, auth: 'required' as const },
  revoke: { operationId: 'postFacCodeByCodeIdRevoke', method: 'POST' as const, pathTemplate: '/fac-code/{codeId}/revoke', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["fac:revoke"], ownership: 'none' as const, auth: 'required' as const },
  standDown: { operationId: 'postFacMeClearanceRevoke', method: 'POST' as const, pathTemplate: '/fac/me/clearance/revoke', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["fac:verify"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'postFacVerify', method: 'POST' as const, pathTemplate: '/fac/verify', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["fac:verify"], ownership: 'self' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const fac = {
  /**
   * The append-only attempt ledger
   * 
   * Zone A: it names who tried and when. `blocked` rows record that somebody kept trying after a lockout began.
   *
   * `GET /fac/attempts`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: fac:read
   * Ownership: none
   */
  attempts(options?: ListOptions): Promise<Page<FacAttempt>> {
    return client().list<FacAttempt>('/fac/attempts', withMeta(options, META.attempts));
  },

  /**
   * Code status and the caller's own attempt and clearance state
   * 
   * What the console polls to decide whether to enable the form, and what to print in "attempts remaining".
   *
   * `GET /fac/me/clearance`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: fac:verify | fac:read
   * Ownership: self
   */
  clearance(options?: RequestOptions): Promise<FacClearanceState> {
    return client().get<FacClearanceState>('/fac/me/clearance', withMeta(options, META.clearance));
  },

  /**
   * Read one code generation
   *
   * `GET /fac-code/{codeId}`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: fac:read
   * Ownership: none
   */
  getGeneration(codeId: string, options?: RequestOptions): Promise<FacCode> {
    return client().get<FacCode>(`/fac-code/${seg(codeId)}`, withMeta(options, META.getGeneration));
  },

  /**
   * Issue a new code generation
   * 
   * Founder-only. The plaintext is returned exactly once and is not recoverable. The body cannot supply a code — the server generates it from a CSPRNG and rejection-samples against the weakness rules. The previous generation is superseded in the same operation, and an immediate trigger (compromise, roleChange) also closes every live clearance.
   *
   * `POST /fac-codes`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: fac:create
   * Ownership: none
   */
  issue(body: IssueFacCodeRequest, options?: RequestOptions): Promise<FacIssuance> {
    return client().post<FacIssuance>('/fac-codes', body, withMeta(options, META.issue));
  },

  /**
   * List code generations
   * 
   * Metadata only. The digest is `select: false` and stripped from every serialised body.
   *
   * `GET /fac-codes`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: fac:read
   * Ownership: none
   */
  listGenerations(options?: ListOptions): Promise<Page<FacCode>> {
    return client().list<FacCode>('/fac-codes', withMeta(options, META.listGenerations));
  },

  /**
   * Lift another founder's lockout
   * 
   * Founder-only, and the caller must already hold a live clearance — so the override costs a second person and a second code, never less than the thing it bypasses. Nobody can clear their own lockout. Writes a `cleared` row naming who lifted it and why; the failures stay in the ledger.
   *
   * `POST /fac/lockout/{actorId}/clear`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: fac:update | fac:create
   * Ownership: none
   */
  lockoutClear(actorId: string, body: ClearLockoutRequest, options?: RequestOptions): Promise<FacLockoutClear> {
    return client().post<FacLockoutClear>(`/fac/lockout/${seg(actorId)}/clear`, body, withMeta(options, META.lockoutClear));
  },

  /**
   * Founders currently locked out of Zone A
   * 
   * Makes the override discoverable. A recovery path that requires already knowing a user id is a puzzle, not a recovery path.
   *
   * `GET /fac/lockouts`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: fac:read
   * Ownership: none
   */
  lockouts(options?: RequestOptions): Promise<FacLockoutList> {
    return client().get<FacLockoutList>('/fac/lockouts', withMeta(options, META.lockouts));
  },

  /**
   * Ask a founder for a rotation
   * 
   * Notifies every founder. Does not rotate anything — only a founder can issue a generation.
   *
   * `POST /fac/reset-requests`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: fac:verify | fac:read
   * Ownership: none
   */
  requestReset(body: FacResetRequestBody, options?: RequestOptions): Promise<FacResetRequest> {
    return client().post<FacResetRequest>('/fac/reset-requests', body, withMeta(options, META.requestReset));
  },

  /**
   * Revoke a generation without replacing it
   * 
   * Founder-only. Leaves no code in force, which closes Zone A to everyone and caps governance health at 40 — the intended outcome for a suspected compromise.
   *
   * `POST /fac-code/{codeId}/revoke`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: fac:revoke
   * Ownership: none
   */
  revoke(codeId: string, body: RevokeFacCodeRequest, options?: RequestOptions): Promise<FacRevocation> {
    return client().post<FacRevocation>(`/fac-code/${seg(codeId)}/revoke`, body, withMeta(options, META.revoke));
  },

  /**
   * Stand down early
   * 
   * A founder leaving a console should not leave it open.
   *
   * `POST /fac/me/clearance/revoke`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: fac:verify
   * Ownership: self
   */
  standDown(options?: RequestOptions): Promise<FacClearanceRevocation> {
    return client().post<FacClearanceRevocation>('/fac/me/clearance/revoke', undefined, withMeta(options, META.standDown));
  },

  /**
   * Submit the code
   * 
   * Zone B, not Zone A — the code is what opens Zone A, so gating this behind it would be a locked door with the key inside. A failure is 422 and never says why. A lockout is 423 with the instant it lifts, not 403: the caller is entitled and the door will open by itself.
   *
   * `POST /fac/verify`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: fac:verify
   * Ownership: self
   */
  verify(body: VerifyFacCodeRequest, options?: RequestOptions): Promise<FacVerification> {
    return client().post<FacVerification>('/fac/verify', body, withMeta(options, META.verify));
  },
};

export type FacApi = typeof fac;
