/**
 * `founders` — 8 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Founder,
  FounderInput,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postFounders', method: 'POST' as const, pathTemplate: '/founders', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteFounderByFounderId', method: 'DELETE' as const, pathTemplate: '/founder/{founderId}', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getFounderByFounderId', method: 'GET' as const, pathTemplate: '/founder/{founderId}', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:read","founderProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getFounders', method: 'GET' as const, pathTemplate: '/founders', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getFounderMe', method: 'GET' as const, pathTemplate: '/founder/me', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postFounderByFounderIdRestore', method: 'POST' as const, pathTemplate: '/founder/{founderId}/restore', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchFounderByFounderId', method: 'PATCH' as const, pathTemplate: '/founder/{founderId}', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:update","founderProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchFounderMe', method: 'PATCH' as const, pathTemplate: '/founder/me', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["founderProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const founders = {
  /**
   * Create a founder profile
   *
   * `POST /founders`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:create
   * Ownership: none
   */
  create(body: FounderInput, options?: RequestOptions): Promise<Founder> {
    return client().post<Founder>('/founders', body, withMeta(options, META.create));
  },

  /**
   * Archive a founder profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /founder/{founderId}`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:delete
   * Ownership: none
   */
  delete(founderId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/founder/${seg(founderId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one founder profile
   *
   * `GET /founder/{founderId}`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:read | founderProfile:readOwn
   * Ownership: scoped
   */
  getById(founderId: string, options?: RequestOptions): Promise<Founder> {
    return client().get<Founder>(`/founder/${seg(founderId)}`, withMeta(options, META.getById));
  },

  /**
   * List founder profiles
   *
   * `GET /founders`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Founder>> {
    return client().list<Founder>('/founders', withMeta(options, META.list));
  },

  /**
   * Read the caller's own founder profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /founder/me`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Founder> {
    return client().get<Founder>('/founder/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived founder profile
   *
   * `POST /founder/{founderId}/restore`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:update
   * Ownership: none
   */
  restore(founderId: string, options?: RequestOptions): Promise<Founder> {
    return client().post<Founder>(`/founder/${seg(founderId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one founder profile
   *
   * `PATCH /founder/{founderId}`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:update | founderProfile:updateOwn
   * Ownership: scoped
   */
  update(founderId: string, body: FounderInput, options?: RequestOptions): Promise<Founder> {
    return client().patch<Founder>(`/founder/${seg(founderId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own founder profile
   *
   * `PATCH /founder/me`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: founderProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: FounderInput, options?: RequestOptions): Promise<Founder> {
    return client().patch<Founder>('/founder/me', body, withMeta(options, META.updateMe));
  },
};

export type FoundersApi = typeof founders;
