/**
 * `governance` — 4 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  GovernanceHealth,
  GovernanceTiers,
  GovernanceVisibility,
  VisibilityMatrix,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  health: { operationId: 'getGovernanceHealth', method: 'GET' as const, pathTemplate: '/governance/health', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["governance:read","analytics:read"], ownership: 'none' as const, auth: 'required' as const },
  myVisibility: { operationId: 'getGovernanceMeVisibility', method: 'GET' as const, pathTemplate: '/governance/me/visibility', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser"] as Role[], permissions: [], ownership: 'self' as const, auth: 'required' as const },
  tiers: { operationId: 'getGovernanceTiers', method: 'GET' as const, pathTemplate: '/governance/tiers', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["governance:read"], ownership: 'none' as const, auth: 'required' as const },
  visibilityMatrix: { operationId: 'getGovernanceVisibilityMatrix', method: 'GET' as const, pathTemplate: '/governance/visibility-matrix', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["governance:read"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const governance = {
  /**
   * Governance health and its components
   * 
   * Every component is computed from something the platform measures. One with no data is excluded rather than scored zero, and a missing or expired code caps the composite at 40.
   *
   * `GET /governance/health`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: governance:read | analytics:read
   * Ownership: none
   */
  health(options?: RequestOptions): Promise<GovernanceHealth> {
    return client().get<GovernanceHealth>('/governance/health', withMeta(options, META.health));
  },

  /**
   * What this caller may see right now
   * 
   * The one call the console needs to decide whether to render the seal, show Tier 1, or draw the locked overlay. `sealEligible` and `sealVisible` are separate: a founder without a live clearance is the first and not the second.
   *
   * `GET /governance/me/visibility`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser
   * Ownership: self
   */
  myVisibility(options?: RequestOptions): Promise<GovernanceVisibility> {
    return client().get<GovernanceVisibility>('/governance/me/visibility', withMeta(options, META.myVisibility));
  },

  /**
   * The four tiers, with live headcounts
   * 
   * Filtered to what the caller's own tier may see — a coordinator gets staff and membership and does not learn how many founders there are. `withheld` is reported rather than the list silently coming back short.
   *
   * `GET /governance/tiers`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: governance:read
   * Ownership: none
   */
  tiers(options?: RequestOptions): Promise<GovernanceTiers> {
    return client().get<GovernanceTiers>('/governance/tiers', withMeta(options, META.tiers));
  },

  /**
   * The seal and clearance matrix, as data
   * 
   * The console renders the same rule the server enforces, rather than a hand-copied duplicate that drifts.
   *
   * `GET /governance/visibility-matrix`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: governance:read
   * Ownership: none
   */
  visibilityMatrix(options?: RequestOptions): Promise<VisibilityMatrix> {
    return client().get<VisibilityMatrix>('/governance/visibility-matrix', withMeta(options, META.visibilityMatrix));
  },
};

export type GovernanceApi = typeof governance;
