/**
 * `hotels` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Hotel,
  HotelInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postHotels', method: 'POST' as const, pathTemplate: '/hotels', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["hotelProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteHotelByHotelId', method: 'DELETE' as const, pathTemplate: '/hotel/{hotelId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["hotelProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getHotelByHotelId', method: 'GET' as const, pathTemplate: '/hotel/{hotelId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["hotelProfile:read","hotelProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getHotels', method: 'GET' as const, pathTemplate: '/hotels', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["hotelProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getHotelMe', method: 'GET' as const, pathTemplate: '/hotel/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","hotelManager"] as Role[], permissions: ["hotelProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postHotelByHotelIdRestore', method: 'POST' as const, pathTemplate: '/hotel/{hotelId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["hotelProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchHotelByHotelId', method: 'PATCH' as const, pathTemplate: '/hotel/{hotelId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["hotelProfile:update","hotelProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchHotelMe', method: 'PATCH' as const, pathTemplate: '/hotel/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","hotelManager"] as Role[], permissions: ["hotelProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchHotelByHotelIdVerify', method: 'PATCH' as const, pathTemplate: '/hotel/{hotelId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["hotelProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const hotels = {
  /**
   * Create a hotel profile
   *
   * `POST /hotels`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: hotelProfile:create
   * Ownership: none
   */
  create(body: HotelInput, options?: RequestOptions): Promise<Hotel> {
    return client().post<Hotel>('/hotels', body, withMeta(options, META.create));
  },

  /**
   * Archive a hotel profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /hotel/{hotelId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: hotelProfile:delete
   * Ownership: none
   */
  delete(hotelId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/hotel/${seg(hotelId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one hotel profile
   *
   * `GET /hotel/{hotelId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: hotelProfile:read | hotelProfile:readOwn
   * Ownership: scoped
   */
  getById(hotelId: string, options?: RequestOptions): Promise<Hotel> {
    return client().get<Hotel>(`/hotel/${seg(hotelId)}`, withMeta(options, META.getById));
  },

  /**
   * List hotel profiles
   *
   * `GET /hotels`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: hotelProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Hotel>> {
    return client().list<Hotel>('/hotels', withMeta(options, META.list));
  },

  /**
   * Read the caller's own hotel profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /hotel/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, hotelManager
   * Permission: hotelProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Hotel> {
    return client().get<Hotel>('/hotel/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived hotel profile
   *
   * `POST /hotel/{hotelId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: hotelProfile:update
   * Ownership: none
   */
  restore(hotelId: string, options?: RequestOptions): Promise<Hotel> {
    return client().post<Hotel>(`/hotel/${seg(hotelId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one hotel profile
   *
   * `PATCH /hotel/{hotelId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: hotelProfile:update | hotelProfile:updateOwn
   * Ownership: scoped
   */
  update(hotelId: string, body: HotelInput, options?: RequestOptions): Promise<Hotel> {
    return client().patch<Hotel>(`/hotel/${seg(hotelId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own hotel profile
   *
   * `PATCH /hotel/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, hotelManager
   * Permission: hotelProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: HotelInput, options?: RequestOptions): Promise<Hotel> {
    return client().patch<Hotel>('/hotel/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a hotel profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /hotel/{hotelId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: hotelProfile:verify
   * Ownership: none
   */
  verify(hotelId: string, body: VerificationRequest, options?: RequestOptions): Promise<Hotel> {
    return client().patch<Hotel>(`/hotel/${seg(hotelId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type HotelsApi = typeof hotels;
