/**
 * `hq` — 8 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AuditLogEntry,
  CommandCenter,
  ExecutiveDashboard,
  HQZoneDetail,
  KPISnapshot,
  RegionalPerformance,
  SystemHealth,
  ZoneDirectory,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  auditLog: { operationId: 'getHqAuditLog', method: 'GET' as const, pathTemplate: '/hq/audit-log', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["auditLog:read"], ownership: 'none' as const, auth: 'required' as const },
  commandCenter: { operationId: 'getHqCommandCenter', method: 'GET' as const, pathTemplate: '/hq/command-center', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
  dashboard: { operationId: 'getHqDashboard', method: 'GET' as const, pathTemplate: '/hq/dashboard', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["analytics:read"], ownership: 'none' as const, auth: 'required' as const },
  kpis: { operationId: 'getHqKpis', method: 'GET' as const, pathTemplate: '/hq/kpis', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["analytics:read"], ownership: 'none' as const, auth: 'required' as const },
  regions: { operationId: 'getHqRegions', method: 'GET' as const, pathTemplate: '/hq/regions', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["analytics:read"], ownership: 'none' as const, auth: 'required' as const },
  systemHealth: { operationId: 'getHqSystemHealth', method: 'GET' as const, pathTemplate: '/hq/system-health', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["analytics:read"], ownership: 'none' as const, auth: 'required' as const },
  zone: { operationId: 'getHqZonesByZone', method: 'GET' as const, pathTemplate: '/hq/zones/{zone}', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
  zones: { operationId: 'getHqZones', method: 'GET' as const, pathTemplate: '/hq/zones', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const hq = {
  /**
   * The append-only mutation trail
   * 
   * Zone A alone. AuditLog blocks updates and deletes at the schema level.
   *
   * `GET /hq/audit-log`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: auditLog:read
   * Ownership: none
   */
  auditLog(options?: RequestOptions): Promise<AuditLogEntry[]> {
    return client().get<AuditLogEntry[]>('/hq/audit-log', withMeta(options, META.auditLog));
  },

  /**
   * Zone A console: all zones, KPIs, health, regions, recent audit trail
   * 
   * Founder-only.
   *
   * `GET /hq/command-center`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Ownership: none
   */
  commandCenter(options?: RequestOptions): Promise<CommandCenter> {
    return client().get<CommandCenter>('/hq/command-center', withMeta(options, META.commandCenter));
  },

  /**
   * Executive dashboard: KPIs, system health, regional roll-up, role matrix
   *
   * `GET /hq/dashboard`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: analytics:read
   * Ownership: none
   */
  dashboard(options?: RequestOptions): Promise<ExecutiveDashboard> {
    return client().get<ExecutiveDashboard>('/hq/dashboard', withMeta(options, META.dashboard));
  },

  /**
   * Members, commercial clients, portfolio, verification queue, ad revenue
   *
   * `GET /hq/kpis`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: analytics:read
   * Ownership: none
   */
  kpis(options?: RequestOptions): Promise<KPISnapshot> {
    return client().get<KPISnapshot>('/hq/kpis', withMeta(options, META.kpis));
  },

  /**
   * Per-region properties, occupancy, coordinators, vendors, drivers
   *
   * `GET /hq/regions`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: analytics:read
   * Ownership: none
   */
  regions(options?: RequestOptions): Promise<RegionalPerformance[]> {
    return client().get<RegionalPerformance[]>('/hq/regions', withMeta(options, META.regions));
  },

  /**
   * Database state, uptime, memory, collection count
   *
   * `GET /hq/system-health`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: analytics:read
   * Ownership: none
   */
  systemHealth(options?: RequestOptions): Promise<SystemHealth> {
    return client().get<SystemHealth>('/hq/system-health', withMeta(options, META.systemHealth));
  },

  /**
   * One zone: purpose, capabilities, surfaces, data firewall, line of sight
   * 
   * Returns 403 ZONE_RESTRICTED if the caller may not enter the requested zone.
   *
   * `GET /hq/zones/{zone}`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, publicUser
   * Ownership: none
   */
  zone(zone: string, options?: RequestOptions): Promise<HQZoneDetail> {
    return client().get<HQZoneDetail>(`/hq/zones/${seg(zone)}`, withMeta(options, META.zone));
  },

  /**
   * All five zones with an `accessible` flag for the caller
   *
   * `GET /hq/zones`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, publicUser
   * Ownership: none
   */
  zones(options?: RequestOptions): Promise<ZoneDirectory> {
    return client().get<ZoneDirectory>('/hq/zones', withMeta(options, META.zones));
  },
};

export type HqApi = typeof hq;
