/**
 * `hqExecutives` — 8 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  HQExecutive,
  HQExecutiveInput,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postHqExecutives', method: 'POST' as const, pathTemplate: '/hq-executives', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["hqExecutiveProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteHqExecutiveByExecutiveId', method: 'DELETE' as const, pathTemplate: '/hq-executive/{executiveId}', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["hqExecutiveProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getHqExecutiveByExecutiveId', method: 'GET' as const, pathTemplate: '/hq-executive/{executiveId}', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["hqExecutiveProfile:read","hqExecutiveProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getHqExecutives', method: 'GET' as const, pathTemplate: '/hq-executives', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["hqExecutiveProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getHqExecutiveMe', method: 'GET' as const, pathTemplate: '/hq-executive/me', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["hqExecutiveProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postHqExecutiveByExecutiveIdRestore', method: 'POST' as const, pathTemplate: '/hq-executive/{executiveId}/restore', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["hqExecutiveProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchHqExecutiveByExecutiveId', method: 'PATCH' as const, pathTemplate: '/hq-executive/{executiveId}', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["hqExecutiveProfile:update","hqExecutiveProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchHqExecutiveMe', method: 'PATCH' as const, pathTemplate: '/hq-executive/me', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["hqExecutiveProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const hqExecutives = {
  /**
   * Create a hq executive profile
   *
   * `POST /hq-executives`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: hqExecutiveProfile:create
   * Ownership: none
   */
  create(body: HQExecutiveInput, options?: RequestOptions): Promise<HQExecutive> {
    return client().post<HQExecutive>('/hq-executives', body, withMeta(options, META.create));
  },

  /**
   * Archive a hq executive profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /hq-executive/{executiveId}`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: hqExecutiveProfile:delete
   * Ownership: none
   */
  delete(executiveId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/hq-executive/${seg(executiveId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one hq executive profile
   *
   * `GET /hq-executive/{executiveId}`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: hqExecutiveProfile:read | hqExecutiveProfile:readOwn
   * Ownership: scoped
   */
  getById(executiveId: string, options?: RequestOptions): Promise<HQExecutive> {
    return client().get<HQExecutive>(`/hq-executive/${seg(executiveId)}`, withMeta(options, META.getById));
  },

  /**
   * List hq executive profiles
   *
   * `GET /hq-executives`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: hqExecutiveProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<HQExecutive>> {
    return client().list<HQExecutive>('/hq-executives', withMeta(options, META.list));
  },

  /**
   * Read the caller's own hq executive profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /hq-executive/me`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: hqExecutiveProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<HQExecutive> {
    return client().get<HQExecutive>('/hq-executive/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived hq executive profile
   *
   * `POST /hq-executive/{executiveId}/restore`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: hqExecutiveProfile:update
   * Ownership: none
   */
  restore(executiveId: string, options?: RequestOptions): Promise<HQExecutive> {
    return client().post<HQExecutive>(`/hq-executive/${seg(executiveId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one hq executive profile
   *
   * `PATCH /hq-executive/{executiveId}`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: hqExecutiveProfile:update | hqExecutiveProfile:updateOwn
   * Ownership: scoped
   */
  update(executiveId: string, body: HQExecutiveInput, options?: RequestOptions): Promise<HQExecutive> {
    return client().patch<HQExecutive>(`/hq-executive/${seg(executiveId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own hq executive profile
   *
   * `PATCH /hq-executive/me`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: hqExecutiveProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: HQExecutiveInput, options?: RequestOptions): Promise<HQExecutive> {
    return client().patch<HQExecutive>('/hq-executive/me', body, withMeta(options, META.updateMe));
  },
};

export type HqExecutivesApi = typeof hqExecutives;
