/**
 * Every module, and the aggregate `api` surface.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { adPolicy } from './adPolicy.js';
import { ads } from './ads.js';
import { advertisers } from './advertisers.js';
import { airbnbHosts } from './airbnbHosts.js';
import { auth } from './auth.js';
import { blueprint } from './blueprint.js';
import { commercialClients } from './commercialClients.js';
import { coordinators } from './coordinators.js';
import { documents } from './documents.js';
import { drivers } from './drivers.js';
import { fac } from './fac.js';
import { founders } from './founders.js';
import { governance } from './governance.js';
import { hotels } from './hotels.js';
import { hq } from './hq.js';
import { hqExecutives } from './hqExecutives.js';
import { landlords } from './landlords.js';
import { leases } from './leases.js';
import { maintenanceRequests } from './maintenanceRequests.js';
import { notifications } from './notifications.js';
import { payments } from './payments.js';
import { payoutBatches } from './payoutBatches.js';
import { properties } from './properties.js';
import { publicApi } from './public.js';
import { rbac } from './rbac.js';
import { rentalCarCompanies } from './rentalCarCompanies.js';
import { resorts } from './resorts.js';
import { riders } from './riders.js';
import { rides } from './rides.js';
import { staff } from './staff.js';
import { tenants } from './tenants.js';
import { vendors } from './vendors.js';

export { adPolicy, META as adPolicyMeta, type AdPolicyApi } from './adPolicy.js';
export { ads, META as adsMeta, type AdsApi } from './ads.js';
export { advertisers, META as advertisersMeta, type AdvertisersApi } from './advertisers.js';
export { airbnbHosts, META as airbnbHostsMeta, type AirbnbHostsApi } from './airbnbHosts.js';
export { auth, META as authMeta, type AuthApi } from './auth.js';
export { blueprint, META as blueprintMeta, type BlueprintApi } from './blueprint.js';
export { commercialClients, META as commercialClientsMeta, type CommercialClientsApi } from './commercialClients.js';
export { coordinators, META as coordinatorsMeta, type CoordinatorsApi } from './coordinators.js';
export { documents, META as documentsMeta, type DocumentsApi } from './documents.js';
export { drivers, META as driversMeta, type DriversApi } from './drivers.js';
export { fac, META as facMeta, type FacApi } from './fac.js';
export { founders, META as foundersMeta, type FoundersApi } from './founders.js';
export { governance, META as governanceMeta, type GovernanceApi } from './governance.js';
export { hotels, META as hotelsMeta, type HotelsApi } from './hotels.js';
export { hq, META as hqMeta, type HqApi } from './hq.js';
export { hqExecutives, META as hqExecutivesMeta, type HqExecutivesApi } from './hqExecutives.js';
export { landlords, META as landlordsMeta, type LandlordsApi } from './landlords.js';
export { leases, META as leasesMeta, type LeasesApi } from './leases.js';
export { maintenanceRequests, META as maintenanceRequestsMeta, type MaintenanceRequestsApi } from './maintenanceRequests.js';
export { notifications, META as notificationsMeta, type NotificationsApi } from './notifications.js';
export { payments, META as paymentsMeta, type PaymentsApi } from './payments.js';
export { payoutBatches, META as payoutBatchesMeta, type PayoutBatchesApi } from './payoutBatches.js';
export { properties, META as propertiesMeta, type PropertiesApi } from './properties.js';
export { publicApi, META as publicMeta, type PublicApi } from './public.js';
export { rbac, META as rbacMeta, type RbacApi } from './rbac.js';
export { rentalCarCompanies, META as rentalCarCompaniesMeta, type RentalCarCompaniesApi } from './rentalCarCompanies.js';
export { resorts, META as resortsMeta, type ResortsApi } from './resorts.js';
export { riders, META as ridersMeta, type RidersApi } from './riders.js';
export { rides, META as ridesMeta, type RidesApi } from './rides.js';
export { staff, META as staffMeta, type StaffApi } from './staff.js';
export { tenants, META as tenantsMeta, type TenantsApi } from './tenants.js';
export { vendors, META as vendorsMeta, type VendorsApi } from './vendors.js';

/**
 * The whole API, grouped by module.
 *
 *   import { api } from '@lrmc/sdk';
 *   const page = await api.landlords.list();
 */
export const api = {
  adPolicy,
  ads,
  advertisers,
  airbnbHosts,
  auth,
  blueprint,
  commercialClients,
  coordinators,
  documents,
  drivers,
  fac,
  founders,
  governance,
  hotels,
  hq,
  hqExecutives,
  landlords,
  leases,
  maintenanceRequests,
  notifications,
  payments,
  payoutBatches,
  properties,
  public: publicApi,
  rbac,
  rentalCarCompanies,
  resorts,
  riders,
  rides,
  staff,
  tenants,
  vendors,
} as const;

export type Api = typeof api;
