/**
 * `landlords` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Landlord,
  LandlordInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postLandlords', method: 'POST' as const, pathTemplate: '/landlords', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["landlordProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteLandlordByLandlordId', method: 'DELETE' as const, pathTemplate: '/landlord/{landlordId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["landlordProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getLandlordByLandlordId', method: 'GET' as const, pathTemplate: '/landlord/{landlordId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["landlordProfile:read","landlordProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getLandlords', method: 'GET' as const, pathTemplate: '/landlords', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["landlordProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getLandlordMe', method: 'GET' as const, pathTemplate: '/landlord/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord"] as Role[], permissions: ["landlordProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postLandlordByLandlordIdRestore', method: 'POST' as const, pathTemplate: '/landlord/{landlordId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["landlordProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchLandlordByLandlordId', method: 'PATCH' as const, pathTemplate: '/landlord/{landlordId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["landlordProfile:update","landlordProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchLandlordMe', method: 'PATCH' as const, pathTemplate: '/landlord/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","landlord"] as Role[], permissions: ["landlordProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchLandlordByLandlordIdVerify', method: 'PATCH' as const, pathTemplate: '/landlord/{landlordId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["landlordProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const landlords = {
  /**
   * Create a landlord profile
   *
   * `POST /landlords`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: landlordProfile:create
   * Ownership: none
   */
  create(body: LandlordInput, options?: RequestOptions): Promise<Landlord> {
    return client().post<Landlord>('/landlords', body, withMeta(options, META.create));
  },

  /**
   * Archive a landlord profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /landlord/{landlordId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: landlordProfile:delete
   * Ownership: none
   */
  delete(landlordId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/landlord/${seg(landlordId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one landlord profile
   *
   * `GET /landlord/{landlordId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: landlordProfile:read | landlordProfile:readOwn
   * Ownership: scoped
   */
  getById(landlordId: string, options?: RequestOptions): Promise<Landlord> {
    return client().get<Landlord>(`/landlord/${seg(landlordId)}`, withMeta(options, META.getById));
  },

  /**
   * List landlord profiles
   *
   * `GET /landlords`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: landlordProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Landlord>> {
    return client().list<Landlord>('/landlords', withMeta(options, META.list));
  },

  /**
   * Read the caller's own landlord profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /landlord/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord
   * Permission: landlordProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Landlord> {
    return client().get<Landlord>('/landlord/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived landlord profile
   *
   * `POST /landlord/{landlordId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: landlordProfile:update
   * Ownership: none
   */
  restore(landlordId: string, options?: RequestOptions): Promise<Landlord> {
    return client().post<Landlord>(`/landlord/${seg(landlordId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one landlord profile
   *
   * `PATCH /landlord/{landlordId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: landlordProfile:update | landlordProfile:updateOwn
   * Ownership: scoped
   */
  update(landlordId: string, body: LandlordInput, options?: RequestOptions): Promise<Landlord> {
    return client().patch<Landlord>(`/landlord/${seg(landlordId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own landlord profile
   *
   * `PATCH /landlord/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, landlord
   * Permission: landlordProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: LandlordInput, options?: RequestOptions): Promise<Landlord> {
    return client().patch<Landlord>('/landlord/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a landlord profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /landlord/{landlordId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: landlordProfile:verify
   * Ownership: none
   */
  verify(landlordId: string, body: VerificationRequest, options?: RequestOptions): Promise<Landlord> {
    return client().patch<Landlord>(`/landlord/${seg(landlordId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type LandlordsApi = typeof landlords;
