/**
 * `leases` — 15 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Lease,
  LeaseActionRequest,
  LeaseInput,
  LeaseSchedule,
  LeaseTerminateRequest,
  MemberCreateLeaseRequest,
  RecordRentPaymentRequest,
  RentPaymentReceipt,
  RentReminderRun,
  RunRentRemindersRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  activate: { operationId: 'postLeasesActivate', method: 'POST' as const, pathTemplate: '/leases/activate', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord"] as Role[], permissions: ["lease:update","lease:updateOwn"], ownership: 'none' as const, auth: 'required' as const },
  complete: { operationId: 'postLeasesComplete', method: 'POST' as const, pathTemplate: '/leases/complete', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord"] as Role[], permissions: ["lease:update","lease:updateOwn"], ownership: 'none' as const, auth: 'required' as const },
  create: { operationId: 'postLeases', method: 'POST' as const, pathTemplate: '/leases', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["lease:create"], ownership: 'none' as const, auth: 'required' as const },
  draftForMember: { operationId: 'postLeasesCreate', method: 'POST' as const, pathTemplate: '/leases/create', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord"] as Role[], permissions: ["lease:create"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getLeaseByLeaseId', method: 'GET' as const, pathTemplate: '/lease/{leaseId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["lease:read","lease:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getLeases', method: 'GET' as const, pathTemplate: '/leases', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["lease:read"], ownership: 'scoped' as const, auth: 'required' as const },
  listForProperty: { operationId: 'getLeasesPropertyByPropertyId', method: 'GET' as const, pathTemplate: '/leases/property/{propertyId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:read","lease:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  listForUser: { operationId: 'getLeasesUserByUserId', method: 'GET' as const, pathTemplate: '/leases/user/{userId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:read","lease:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  mineAsLandlord: { operationId: 'getLandlordMeLeases', method: 'GET' as const, pathTemplate: '/landlord/me/leases', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:readOwn","lease:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsTenant: { operationId: 'getTenantMeLeases', method: 'GET' as const, pathTemplate: '/tenant/me/leases', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:readOwn","lease:read"], ownership: 'self' as const, auth: 'required' as const },
  recordPayment: { operationId: 'postLeaseByLeaseIdPayments', method: 'POST' as const, pathTemplate: '/lease/{leaseId}/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["payment:create","rentPayment:create"], ownership: 'scoped' as const, auth: 'required' as const },
  runRentReminders: { operationId: 'postLeasesRunRentReminders', method: 'POST' as const, pathTemplate: '/leases/run-rent-reminders', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["lease:update","lease:read"], ownership: 'none' as const, auth: 'required' as const },
  schedule: { operationId: 'getLeaseByLeaseIdSchedule', method: 'GET' as const, pathTemplate: '/lease/{leaseId}/schedule', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:read","lease:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  terminate: { operationId: 'postLeasesTerminate', method: 'POST' as const, pathTemplate: '/leases/terminate', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord"] as Role[], permissions: ["lease:update","lease:updateOwn"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchLeaseByLeaseId', method: 'PATCH' as const, pathTemplate: '/lease/{leaseId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["lease:update"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const leases = {
  /**
   * Put a drafted tenancy into force
   * 
   * The landlord's act: it is their property and their commitment. A coordinator is refused with a message saying so rather than a bare 403. The actor's party is resolved from the loaded lease, never from anything the caller asserted.
   *
   * `POST /leases/activate`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord
   * Permission: lease:update | lease:updateOwn
   * Ownership: none
   */
  activate(body: LeaseActionRequest, options?: RequestOptions): Promise<Lease> {
    return client().post<Lease>('/leases/activate', body, withMeta(options, META.activate));
  },

  /**
   * Close a tenancy that ran its term
   * 
   * Terminal. A renewal is a NEW lease, not a resurrection of this one — reopening would silently rewrite the tenancy length that feeds an applicant's stability score. Stamps `closedAt`, which is when the tenancy actually stopped, as distinct from `leaseEnd`, which is when the term was meant to run out. A tenancy in arrears is still completable: refusing to close a lease because the tenant owes money would trap both parties in it.
   *
   * `POST /leases/complete`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord
   * Permission: lease:update | lease:updateOwn
   * Ownership: none
   */
  complete(body: LeaseActionRequest, options?: RequestOptions): Promise<Lease> {
    return client().post<Lease>('/leases/complete', body, withMeta(options, META.complete));
  },

  /**
   * Open a lease between a landlord and a tenant
   * 
   * leaseEnd must be after leaseStart. `reference` (LSE-xxxxxx) is server-assigned.
   *
   * `POST /leases`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: lease:create
   * Ownership: none
   */
  create(body: LeaseInput, options?: RequestOptions): Promise<Lease> {
    return client().post<Lease>('/leases', body, withMeta(options, META.create));
  },

  /**
   * Draw up a tenancy from inside the portal
   * 
   * Always lands in `draft`; a create that could go straight to `active` would skip the one moment either party gets to look at it. The landlord is taken from the property, never from the body — a body that could name the landlord would let somebody draw up a lease over a building they have nothing to do with. `leaseEnd` is OPTIONAL: month-to-month is ordinary in The Gambia, and a required end date forces whoever writes the lease to invent one that then looks like a commitment. Nobody may name themselves as the tenant, and a landlord cannot be their own tenant — the same principle as nobody producing evidence about themselves.
   *
   * `POST /leases/create`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord
   * Permission: lease:create
   * Ownership: none
   */
  draftForMember(body: MemberCreateLeaseRequest, options?: RequestOptions): Promise<Lease> {
    return client().post<Lease>('/leases/create', body, withMeta(options, META.draftForMember));
  },

  /**
   * Read one lease
   *
   * `GET /lease/{leaseId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: lease:read | lease:readOwn
   * Ownership: scoped
   */
  getById(leaseId: string, options?: RequestOptions): Promise<Lease> {
    return client().get<Lease>(`/lease/${seg(leaseId)}`, withMeta(options, META.getById));
  },

  /**
   * List leases
   *
   * `GET /leases`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: lease:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>('/leases', withMeta(options, META.list));
  },

  /**
   * A property's succession of tenancies
   * 
   * The landlord who owns it, coordinators and staff. A tenant may read their own lease at /leases/user/:userId but NOT the succession of everybody who lived there before them — that is the previous tenants' business, not the current one's.
   *
   * `GET /leases/property/{propertyId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:read | lease:readOwn
   * Ownership: scoped
   */
  listForProperty(propertyId: string, options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>(`/leases/property/${seg(propertyId)}`, withMeta(options, META.listForProperty));
  },

  /**
   * One person's tenancies, as tenant or as landlord
   * 
   * Both sides at once, because the same account can be a tenant of one property and the landlord of another and that is one screen. A person always sees their own; coordinators and staff see anyone's; everybody else is REFUSED rather than answered with an empty list — "you may not see this" and "there is nothing here" are different facts.
   *
   * `GET /leases/user/{userId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:read | lease:readOwn
   * Ownership: scoped
   */
  listForUser(userId: string, options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>(`/leases/user/${seg(userId)}`, withMeta(options, META.listForUser));
  },

  /**
   * The signed-in landlord's own leases
   *
   * `GET /landlord/me/leases`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:readOwn | lease:read
   * Ownership: self
   */
  mineAsLandlord(options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>('/landlord/me/leases', withMeta(options, META.mineAsLandlord));
  },

  /**
   * The signed-in tenant's own leases
   *
   * `GET /tenant/me/leases`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:readOwn | lease:read
   * Ownership: self
   */
  mineAsTenant(options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>('/tenant/me/leases', withMeta(options, META.mineAsTenant));
  },

  /**
   * Record a rent payment against a lease
   * 
   * Writes the ledger row and rolls the lease's totalPaid, arrearsAmount and lastPaymentAt forward in the same request; clears `inArrears` when the balance reaches zero.
   *
   * `POST /lease/{leaseId}/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: payment:create | rentPayment:create
   * Ownership: scoped
   */
  recordPayment(leaseId: string, body: RecordRentPaymentRequest, options?: RequestOptions): Promise<RentPaymentReceipt> {
    return client().post<RentPaymentReceipt>(`/lease/${seg(leaseId)}/payments`, body, withMeta(options, META.recordPayment));
  },

  /**
   * Run the rent reminder and arrears sweep
   * 
   * Idempotent, and the scheduling is external: a platform cron calls this. `asOf` replays a day the job missed; `dryRun` reports without sending or writing. Doubles as the arrears sweep, so a lease that fell behind overnight is relabelled before anyone looks at it.
   *
   * `POST /leases/run-rent-reminders`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: lease:update | lease:read
   * Ownership: none
   */
  runRentReminders(body: RunRentRemindersRequest, options?: RequestOptions): Promise<RentReminderRun> {
    return client().post<RentReminderRun>('/leases/run-rent-reminders', body, withMeta(options, META.runRentReminders));
  },

  /**
   * Instalment schedule, arrears and next due date
   * 
   * Computed from the term and the running total — no schedule rows are stored, so a corrected rent or start date reshapes the statement rather than leaving stale instalments behind.
   *
   * `GET /lease/{leaseId}/schedule`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:read | lease:readOwn
   * Ownership: scoped
   */
  schedule(leaseId: string, options?: RequestOptions): Promise<LeaseSchedule> {
    return client().get<LeaseSchedule>(`/lease/${seg(leaseId)}/schedule`, withMeta(options, META.schedule));
  },

  /**
   * End a tenancy early, with a reason
   * 
   * A COORDINATOR'S ACT, NOT A LANDLORD'S. Ending a tenancy early is eviction by another name, and LRMC carries the tenancy, holds the deposit and answers for the outcome — the same principle as a landlord not approving their own applicant. A landlord attempting it is told to ask their coordinator rather than given a bare refusal. A reason is required by both the schema and the lifecycle rules: a terminated lease with no stated reason is a fact about somebody's housing that nobody has to defend.
   *
   * `POST /leases/terminate`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord
   * Permission: lease:update | lease:updateOwn
   * Ownership: none
   */
  terminate(body: LeaseTerminateRequest, options?: RequestOptions): Promise<Lease> {
    return client().post<Lease>('/leases/terminate', body, withMeta(options, META.terminate));
  },

  /**
   * Amend a lease
   *
   * `PATCH /lease/{leaseId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: lease:update
   * Ownership: scoped
   */
  update(leaseId: string, body: LeaseInput, options?: RequestOptions): Promise<Lease> {
    return client().patch<Lease>(`/lease/${seg(leaseId)}`, body, withMeta(options, META.update));
  },
};

export type LeasesApi = typeof leases;
