/**
 * `leases` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Lease,
  LeaseInput,
  LeaseSchedule,
  RecordRentPaymentRequest,
  RentPaymentReceipt,
  RentReminderRun,
  RunRentRemindersRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postLeases', method: 'POST' as const, pathTemplate: '/leases', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["lease:create"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getLeaseByLeaseId', method: 'GET' as const, pathTemplate: '/lease/{leaseId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["lease:read","lease:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getLeases', method: 'GET' as const, pathTemplate: '/leases', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["lease:read"], ownership: 'scoped' as const, auth: 'required' as const },
  mineAsLandlord: { operationId: 'getLandlordMeLeases', method: 'GET' as const, pathTemplate: '/landlord/me/leases', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:readOwn","lease:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsTenant: { operationId: 'getTenantMeLeases', method: 'GET' as const, pathTemplate: '/tenant/me/leases', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:readOwn","lease:read"], ownership: 'self' as const, auth: 'required' as const },
  recordPayment: { operationId: 'postLeaseByLeaseIdPayments', method: 'POST' as const, pathTemplate: '/lease/{leaseId}/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["payment:create","rentPayment:create"], ownership: 'scoped' as const, auth: 'required' as const },
  runRentReminders: { operationId: 'postLeasesRunRentReminders', method: 'POST' as const, pathTemplate: '/leases/run-rent-reminders', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["lease:update","lease:read"], ownership: 'none' as const, auth: 'required' as const },
  schedule: { operationId: 'getLeaseByLeaseIdSchedule', method: 'GET' as const, pathTemplate: '/lease/{leaseId}/schedule', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["lease:read","lease:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchLeaseByLeaseId', method: 'PATCH' as const, pathTemplate: '/lease/{leaseId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["lease:update"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const leases = {
  /**
   * Open a lease between a landlord and a tenant
   * 
   * leaseEnd must be after leaseStart. `reference` (LSE-xxxxxx) is server-assigned.
   *
   * `POST /leases`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: lease:create
   * Ownership: none
   */
  create(body: LeaseInput, options?: RequestOptions): Promise<Lease> {
    return client().post<Lease>('/leases', body, withMeta(options, META.create));
  },

  /**
   * Read one lease
   *
   * `GET /lease/{leaseId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: lease:read | lease:readOwn
   * Ownership: scoped
   */
  getById(leaseId: string, options?: RequestOptions): Promise<Lease> {
    return client().get<Lease>(`/lease/${seg(leaseId)}`, withMeta(options, META.getById));
  },

  /**
   * List leases
   *
   * `GET /leases`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: lease:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>('/leases', withMeta(options, META.list));
  },

  /**
   * The signed-in landlord's own leases
   *
   * `GET /landlord/me/leases`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:readOwn | lease:read
   * Ownership: self
   */
  mineAsLandlord(options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>('/landlord/me/leases', withMeta(options, META.mineAsLandlord));
  },

  /**
   * The signed-in tenant's own leases
   *
   * `GET /tenant/me/leases`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:readOwn | lease:read
   * Ownership: self
   */
  mineAsTenant(options?: ListOptions): Promise<Page<Lease>> {
    return client().list<Lease>('/tenant/me/leases', withMeta(options, META.mineAsTenant));
  },

  /**
   * Record a rent payment against a lease
   * 
   * Writes the ledger row and rolls the lease's totalPaid, arrearsAmount and lastPaymentAt forward in the same request; clears `inArrears` when the balance reaches zero.
   *
   * `POST /lease/{leaseId}/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: payment:create | rentPayment:create
   * Ownership: scoped
   */
  recordPayment(leaseId: string, body: RecordRentPaymentRequest, options?: RequestOptions): Promise<RentPaymentReceipt> {
    return client().post<RentPaymentReceipt>(`/lease/${seg(leaseId)}/payments`, body, withMeta(options, META.recordPayment));
  },

  /**
   * Run the rent reminder and arrears sweep
   * 
   * Idempotent, and the scheduling is external: a platform cron calls this. `asOf` replays a day the job missed; `dryRun` reports without sending or writing. Doubles as the arrears sweep, so a lease that fell behind overnight is relabelled before anyone looks at it.
   *
   * `POST /leases/run-rent-reminders`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: lease:update | lease:read
   * Ownership: none
   */
  runRentReminders(body: RunRentRemindersRequest, options?: RequestOptions): Promise<RentReminderRun> {
    return client().post<RentReminderRun>('/leases/run-rent-reminders', body, withMeta(options, META.runRentReminders));
  },

  /**
   * Instalment schedule, arrears and next due date
   * 
   * Computed from the term and the running total — no schedule rows are stored, so a corrected rent or start date reshapes the statement rather than leaving stale instalments behind.
   *
   * `GET /lease/{leaseId}/schedule`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: lease:read | lease:readOwn
   * Ownership: scoped
   */
  schedule(leaseId: string, options?: RequestOptions): Promise<LeaseSchedule> {
    return client().get<LeaseSchedule>(`/lease/${seg(leaseId)}/schedule`, withMeta(options, META.schedule));
  },

  /**
   * Amend a lease
   *
   * `PATCH /lease/{leaseId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: lease:update
   * Ownership: scoped
   */
  update(leaseId: string, body: LeaseInput, options?: RequestOptions): Promise<Lease> {
    return client().patch<Lease>(`/lease/${seg(leaseId)}`, body, withMeta(options, META.update));
  },
};

export type LeasesApi = typeof leases;
