/**
 * `maintenanceRequests` — 13 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AssignVendorRequest,
  MaintenanceRequest,
  MaintenanceRequestInput,
  MaintenanceSla,
  MaintenanceSummary,
  RaiseMaintenanceRequest,
  RunSlaEscalationRequest,
  SlaEscalationRun,
  UpdateMaintenanceStatusRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  assignVendor: { operationId: 'postMaintenanceRequestByRequestIdAssignVendor', method: 'POST' as const, pathTemplate: '/maintenance-request/{requestId}/assign-vendor', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["maintenanceRequest:assign","maintenanceRequest:update"], ownership: 'none' as const, auth: 'required' as const },
  create: { operationId: 'postMaintenanceRequests', method: 'POST' as const, pathTemplate: '/maintenance-requests', zone: 'MEMBER_PORTAL' as const, roles: ["founder","coordinator","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:create"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getMaintenanceRequestByRequestId', method: 'GET' as const, pathTemplate: '/maintenance-request/{requestId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  historyForProperty: { operationId: 'getPropertyByPropertyIdMaintenanceHistory', method: 'GET' as const, pathTemplate: '/property/{propertyId}/maintenance-history', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getMaintenanceRequests', method: 'GET' as const, pathTemplate: '/maintenance-requests', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  listForUser: { operationId: 'getMaintenanceByUserIdList', method: 'GET' as const, pathTemplate: '/maintenance/{userId}/list', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  myQueue: { operationId: 'getVendorMeMaintenanceQueue', method: 'GET' as const, pathTemplate: '/vendor/me/maintenance-queue', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:readOwn","maintenanceRequest:read"], ownership: 'self' as const, auth: 'required' as const },
  request: { operationId: 'postMaintenanceRequest', method: 'POST' as const, pathTemplate: '/maintenance/request', zone: 'MEMBER_PORTAL' as const, roles: ["founder","coordinator","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:create"], ownership: 'none' as const, auth: 'required' as const },
  runSlaEscalation: { operationId: 'postMaintenanceRequestsRunSlaEscalation', method: 'POST' as const, pathTemplate: '/maintenance-requests/run-sla-escalation', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["maintenanceRequest:update","maintenanceRequest:read"], ownership: 'none' as const, auth: 'required' as const },
  sla: { operationId: 'getMaintenanceRequestByRequestIdSla', method: 'GET' as const, pathTemplate: '/maintenance-request/{requestId}/sla', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  summaryForUser: { operationId: 'getMaintenanceByUserIdSummary', method: 'GET' as const, pathTemplate: '/maintenance/{userId}/summary', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchMaintenanceRequestByRequestId', method: 'PATCH' as const, pathTemplate: '/maintenance-request/{requestId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","vendor"] as Role[], permissions: ["maintenanceRequest:update"], ownership: 'scoped' as const, auth: 'required' as const },
  updateStatus: { operationId: 'postMaintenanceUpdate', method: 'POST' as const, pathTemplate: '/maintenance/update', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","vendor"] as Role[], permissions: ["maintenanceRequest:update","maintenanceRequest:updateOwn"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const maintenanceRequests = {
  /**
   * Put a vendor on the job
   * 
   * Refuses a vendor whose verificationStatus is not `verified`, and appends to `statusHistory` so the assignment is answerable after a disputed invoice.
   *
   * `POST /maintenance-request/{requestId}/assign-vendor`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: maintenanceRequest:assign | maintenanceRequest:update
   * Ownership: none
   */
  assignVendor(requestId: string, body: AssignVendorRequest, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().post<MaintenanceRequest>(`/maintenance-request/${seg(requestId)}/assign-vendor`, body, withMeta(options, META.assignVendor));
  },

  /**
   * Raise a work order against a property
   *
   * `POST /maintenance-requests`
   * Zone: MEMBER_PORTAL
   * Roles: founder, coordinator, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:create
   * Ownership: none
   */
  create(body: MaintenanceRequestInput, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().post<MaintenanceRequest>('/maintenance-requests', body, withMeta(options, META.create));
  },

  /**
   * Read one maintenance request
   *
   * `GET /maintenance-request/{requestId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  getById(requestId: string, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().get<MaintenanceRequest>(`/maintenance-request/${seg(requestId)}`, withMeta(options, META.getById));
  },

  /**
   * Everything ever raised against one property
   *
   * `GET /property/{propertyId}/maintenance-history`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  historyForProperty(propertyId: string, options?: ListOptions): Promise<Page<MaintenanceRequest>> {
    return client().list<MaintenanceRequest>(`/property/${seg(propertyId)}/maintenance-history`, withMeta(options, META.historyForProperty));
  },

  /**
   * List maintenance requests
   *
   * `GET /maintenance-requests`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<MaintenanceRequest>> {
    return client().list<MaintenanceRequest>('/maintenance-requests', withMeta(options, META.list));
  },

  /**
   * One person's work orders
   * 
   * Covers three relationships at once: raised by them, assigned to them as a vendor, and against a property they own. A landlord's maintenance is the maintenance on their buildings, which is a different question from what they personally reported, so ownership is resolved through the property collection rather than assumed. Reading somebody else's needs a staff role and is refused rather than answered empty.
   *
   * `GET /maintenance/{userId}/list`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  listForUser(userId: string, options?: ListOptions): Promise<Page<MaintenanceRequest>> {
    return client().list<MaintenanceRequest>(`/maintenance/${seg(userId)}/list`, withMeta(options, META.listForUser));
  },

  /**
   * The signed-in vendor's open work, most urgent first
   * 
   * Completed, verified and cancelled work is filtered out — this is a queue, not a history.
   *
   * `GET /vendor/me/maintenance-queue`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:readOwn | maintenanceRequest:read
   * Ownership: self
   */
  myQueue(options?: ListOptions): Promise<Page<MaintenanceRequest>> {
    return client().list<MaintenanceRequest>('/vendor/me/maintenance-queue', withMeta(options, META.myQueue));
  },

  /**
   * Raise a work order from inside a tenancy
   * 
   * Accepts only what a person standing in front of a broken thing can supply — where, what, how bad. The SLA clock is derived from the priority and the property's standing coordinator is attached, so the request has an owner from the first second rather than waiting for triage to notice it. `slaHours`, `assignedVendor` and every cost field are refused by the strict schema rather than silently dropped: a field ignored and a field honoured look identical from a client. Photographs are storage keys, never URLs.
   *
   * `POST /maintenance/request`
   * Zone: MEMBER_PORTAL
   * Roles: founder, coordinator, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:create
   * Ownership: none
   */
  request(body: RaiseMaintenanceRequest, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().post<MaintenanceRequest>('/maintenance/request', body, withMeta(options, META.request));
  },

  /**
   * Run the SLA escalation sweep
   * 
   * Notifies only — it never changes a request's status, because "nobody has done this work" is not a state the work order should claim on its own behalf.
   *
   * `POST /maintenance-requests/run-sla-escalation`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: maintenanceRequest:update | maintenanceRequest:read
   * Ownership: none
   */
  runSlaEscalation(body: RunSlaEscalationRequest, options?: RequestOptions): Promise<SlaEscalationRun> {
    return client().post<SlaEscalationRun>('/maintenance-requests/run-sla-escalation', body, withMeta(options, META.runSlaEscalation));
  },

  /**
   * The SLA clock for one work order
   * 
   * `dueAt` is the target; `overdueAt` adds a grace period, after which it escalates to a human. A finished request is judged against when it finished, not against now.
   *
   * `GET /maintenance-request/{requestId}/sla`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  sla(requestId: string, options?: RequestOptions): Promise<MaintenanceSla> {
    return client().get<MaintenanceSla>(`/maintenance-request/${seg(requestId)}/sla`, withMeta(options, META.sla));
  },

  /**
   * Counts by stage, escalations, and average turnaround
   * 
   * Uses the same buckets as /stats/maintenance, so a tile and a summary can never disagree about what "open" means. `stalled` is reported rather than hidden so the parts sum to the total. `needsEscalation` is computed from the current state on every read and never stored — a request does not become escalated, it becomes somebody's, and a stored flag would go stale the moment a vendor picked the job up. `averageResolutionHours` is null over nothing resolved, never 0: a landlord whose first request is still open has not achieved a nought-hour turnaround.
   *
   * `GET /maintenance/{userId}/summary`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  summaryForUser(userId: string, options?: RequestOptions): Promise<MaintenanceSummary> {
    return client().get<MaintenanceSummary>(`/maintenance/${seg(userId)}/summary`, withMeta(options, META.summaryForUser));
  },

  /**
   * Update a maintenance request
   *
   * `PATCH /maintenance-request/{requestId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, vendor
   * Permission: maintenanceRequest:update
   * Ownership: scoped
   */
  update(requestId: string, body: MaintenanceRequestInput, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().patch<MaintenanceRequest>(`/maintenance-request/${seg(requestId)}`, body, withMeta(options, META.update));
  },

  /**
   * Move a request along the lifecycle
   * 
   * The request id is in the body rather than the path, which is a departure from this platform's convention and costs a readable audit trail — every update shares one route, so a reader of the log must open the entry to see which request moved. PATCH /maintenance-request/:requestId is the better route for anything programmatic. Safety does not depend on the route shape: the actor's party (raiser, vendor, staff) is resolved from the loaded row, never from anything the caller asserted. A vendor may start, pause and finish; only LRMC may cancel or verify; and the vendor who did the work can never be the one who verifies it. Cancelling or parking a request requires a reason, because whoever raised it is told what happened.
   *
   * `POST /maintenance/update`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, vendor
   * Permission: maintenanceRequest:update | maintenanceRequest:updateOwn
   * Ownership: none
   */
  updateStatus(body: UpdateMaintenanceStatusRequest, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().post<MaintenanceRequest>('/maintenance/update', body, withMeta(options, META.updateStatus));
  },
};

export type MaintenanceRequestsApi = typeof maintenanceRequests;
