/**
 * `maintenanceRequests` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AssignVendorRequest,
  MaintenanceRequest,
  MaintenanceRequestInput,
  MaintenanceSla,
  RunSlaEscalationRequest,
  SlaEscalationRun,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  assignVendor: { operationId: 'postMaintenanceRequestByRequestIdAssignVendor', method: 'POST' as const, pathTemplate: '/maintenance-request/{requestId}/assign-vendor', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["maintenanceRequest:assign","maintenanceRequest:update"], ownership: 'none' as const, auth: 'required' as const },
  create: { operationId: 'postMaintenanceRequests', method: 'POST' as const, pathTemplate: '/maintenance-requests', zone: 'MEMBER_PORTAL' as const, roles: ["founder","coordinator","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:create"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getMaintenanceRequestByRequestId', method: 'GET' as const, pathTemplate: '/maintenance-request/{requestId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  historyForProperty: { operationId: 'getPropertyByPropertyIdMaintenanceHistory', method: 'GET' as const, pathTemplate: '/property/{propertyId}/maintenance-history', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getMaintenanceRequests', method: 'GET' as const, pathTemplate: '/maintenance-requests', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  myQueue: { operationId: 'getVendorMeMaintenanceQueue', method: 'GET' as const, pathTemplate: '/vendor/me/maintenance-queue', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:readOwn","maintenanceRequest:read"], ownership: 'self' as const, auth: 'required' as const },
  runSlaEscalation: { operationId: 'postMaintenanceRequestsRunSlaEscalation', method: 'POST' as const, pathTemplate: '/maintenance-requests/run-sla-escalation', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["maintenanceRequest:update","maintenanceRequest:read"], ownership: 'none' as const, auth: 'required' as const },
  sla: { operationId: 'getMaintenanceRequestByRequestIdSla', method: 'GET' as const, pathTemplate: '/maintenance-request/{requestId}/sla', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["maintenanceRequest:read","maintenanceRequest:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchMaintenanceRequestByRequestId', method: 'PATCH' as const, pathTemplate: '/maintenance-request/{requestId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","vendor"] as Role[], permissions: ["maintenanceRequest:update"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const maintenanceRequests = {
  /**
   * Put a vendor on the job
   * 
   * Refuses a vendor whose verificationStatus is not `verified`, and appends to `statusHistory` so the assignment is answerable after a disputed invoice.
   *
   * `POST /maintenance-request/{requestId}/assign-vendor`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: maintenanceRequest:assign | maintenanceRequest:update
   * Ownership: none
   */
  assignVendor(requestId: string, body: AssignVendorRequest, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().post<MaintenanceRequest>(`/maintenance-request/${seg(requestId)}/assign-vendor`, body, withMeta(options, META.assignVendor));
  },

  /**
   * Raise a work order against a property
   *
   * `POST /maintenance-requests`
   * Zone: MEMBER_PORTAL
   * Roles: founder, coordinator, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:create
   * Ownership: none
   */
  create(body: MaintenanceRequestInput, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().post<MaintenanceRequest>('/maintenance-requests', body, withMeta(options, META.create));
  },

  /**
   * Read one maintenance request
   *
   * `GET /maintenance-request/{requestId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  getById(requestId: string, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().get<MaintenanceRequest>(`/maintenance-request/${seg(requestId)}`, withMeta(options, META.getById));
  },

  /**
   * Everything ever raised against one property
   *
   * `GET /property/{propertyId}/maintenance-history`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  historyForProperty(propertyId: string, options?: ListOptions): Promise<Page<MaintenanceRequest>> {
    return client().list<MaintenanceRequest>(`/property/${seg(propertyId)}/maintenance-history`, withMeta(options, META.historyForProperty));
  },

  /**
   * List maintenance requests
   *
   * `GET /maintenance-requests`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<MaintenanceRequest>> {
    return client().list<MaintenanceRequest>('/maintenance-requests', withMeta(options, META.list));
  },

  /**
   * The signed-in vendor's open work, most urgent first
   * 
   * Completed, verified and cancelled work is filtered out — this is a queue, not a history.
   *
   * `GET /vendor/me/maintenance-queue`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:readOwn | maintenanceRequest:read
   * Ownership: self
   */
  myQueue(options?: ListOptions): Promise<Page<MaintenanceRequest>> {
    return client().list<MaintenanceRequest>('/vendor/me/maintenance-queue', withMeta(options, META.myQueue));
  },

  /**
   * Run the SLA escalation sweep
   * 
   * Notifies only — it never changes a request's status, because "nobody has done this work" is not a state the work order should claim on its own behalf.
   *
   * `POST /maintenance-requests/run-sla-escalation`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: maintenanceRequest:update | maintenanceRequest:read
   * Ownership: none
   */
  runSlaEscalation(body: RunSlaEscalationRequest, options?: RequestOptions): Promise<SlaEscalationRun> {
    return client().post<SlaEscalationRun>('/maintenance-requests/run-sla-escalation', body, withMeta(options, META.runSlaEscalation));
  },

  /**
   * The SLA clock for one work order
   * 
   * `dueAt` is the target; `overdueAt` adds a grace period, after which it escalates to a human. A finished request is judged against when it finished, not against now.
   *
   * `GET /maintenance-request/{requestId}/sla`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: maintenanceRequest:read | maintenanceRequest:readOwn
   * Ownership: scoped
   */
  sla(requestId: string, options?: RequestOptions): Promise<MaintenanceSla> {
    return client().get<MaintenanceSla>(`/maintenance-request/${seg(requestId)}/sla`, withMeta(options, META.sla));
  },

  /**
   * Update a maintenance request
   *
   * `PATCH /maintenance-request/{requestId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, vendor
   * Permission: maintenanceRequest:update
   * Ownership: scoped
   */
  update(requestId: string, body: MaintenanceRequestInput, options?: RequestOptions): Promise<MaintenanceRequest> {
    return client().patch<MaintenanceRequest>(`/maintenance-request/${seg(requestId)}`, body, withMeta(options, META.update));
  },
};

export type MaintenanceRequestsApi = typeof maintenanceRequests;
