/**
 * `marketplace` — 19 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  CancelOrderRequest,
  DisputeOrderRequest,
  FulfilOrderRequest,
  Listing,
  MarketplaceOverview,
  MerchantCatalogue,
  Order,
  OrderDetail,
  OrderSettlement,
  PayOrderRequest,
  PlaceOrderRequest,
  ResolveDisputeRequest,
  SuspendListingRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  accept: { operationId: 'postOrderByOrderIdAccept', method: 'POST' as const, pathTemplate: '/order/{orderId}/accept', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller"] as Role[], permissions: ["order:update"], ownership: 'scoped' as const, auth: 'required' as const },
  cancel: { operationId: 'postOrderByOrderIdCancel', method: 'POST' as const, pathTemplate: '/order/{orderId}/cancel', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["order:updateOwn","order:update"], ownership: 'scoped' as const, auth: 'required' as const },
  confirm: { operationId: 'postOrderByOrderIdConfirm', method: 'POST' as const, pathTemplate: '/order/{orderId}/confirm', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["order:updateOwn","order:update"], ownership: 'scoped' as const, auth: 'required' as const },
  create: { operationId: 'postListings', method: 'POST' as const, pathTemplate: '/listings', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller"] as Role[], permissions: ["listing:create"], ownership: 'none' as const, auth: 'required' as const },
  dispute: { operationId: 'postOrderByOrderIdDispute', method: 'POST' as const, pathTemplate: '/order/{orderId}/dispute', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["order:updateOwn","order:update"], ownership: 'scoped' as const, auth: 'required' as const },
  fulfil: { operationId: 'postOrderByOrderIdFulfil', method: 'POST' as const, pathTemplate: '/order/{orderId}/fulfil', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller"] as Role[], permissions: ["order:update"], ownership: 'scoped' as const, auth: 'required' as const },
  get: { operationId: 'getOrders', method: 'GET' as const, pathTemplate: '/orders', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["order:read"], ownership: 'scoped' as const, auth: 'required' as const },
  get2: { operationId: 'getOrderByOrderId', method: 'GET' as const, pathTemplate: '/order/{orderId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["order:read"], ownership: 'scoped' as const, auth: 'required' as const },
  getById: { operationId: 'getListingByListingId', method: 'GET' as const, pathTemplate: '/listing/{listingId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["listing:read"], ownership: 'none' as const, auth: 'required' as const },
  list: { operationId: 'getListings', method: 'GET' as const, pathTemplate: '/listings', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["listing:read"], ownership: 'none' as const, auth: 'required' as const },
  me: { operationId: 'getListingsMe', method: 'GET' as const, pathTemplate: '/listings/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["listing:read"], ownership: 'self' as const, auth: 'required' as const },
  overview: { operationId: 'getMarketplaceOverview', method: 'GET' as const, pathTemplate: '/marketplace/overview', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["marketplace:read"], ownership: 'self' as const, auth: 'required' as const },
  pay: { operationId: 'postOrderByOrderIdPay', method: 'POST' as const, pathTemplate: '/order/{orderId}/pay', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller","customer","buyer"] as Role[], permissions: ["order:updateOwn","order:update"], ownership: 'scoped' as const, auth: 'required' as const },
  post: { operationId: 'postOrders', method: 'POST' as const, pathTemplate: '/orders', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","customer","buyer"] as Role[], permissions: ["order:create"], ownership: 'none' as const, auth: 'required' as const },
  publish: { operationId: 'postListingByListingIdPublish', method: 'POST' as const, pathTemplate: '/listing/{listingId}/publish', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller"] as Role[], permissions: ["listing:update"], ownership: 'scoped' as const, auth: 'required' as const },
  resolve: { operationId: 'postOrderByOrderIdResolve', method: 'POST' as const, pathTemplate: '/order/{orderId}/resolve', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["order:update"], ownership: 'none' as const, auth: 'required' as const },
  suspend: { operationId: 'postListingByListingIdSuspend', method: 'POST' as const, pathTemplate: '/listing/{listingId}/suspend', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["listing:review","listing:update"], ownership: 'none' as const, auth: 'required' as const },
  unpublish: { operationId: 'postListingByListingIdUnpublish', method: 'POST' as const, pathTemplate: '/listing/{listingId}/unpublish', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller"] as Role[], permissions: ["listing:update"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchListingByListingId', method: 'PATCH' as const, pathTemplate: '/listing/{listingId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant","seller"] as Role[], permissions: ["listing:update"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const marketplace = {
  /**
   * Merchant takes the order on
   *
   * `POST /order/{orderId}/accept`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller
   * Permission: order:update
   * Ownership: scoped
   */
  accept(orderId: string, options?: RequestOptions): Promise<OrderDetail> {
    return client().post<OrderDetail>(`/order/${seg(orderId)}/accept`, undefined, withMeta(options, META.accept));
  },

  /**
   * Cancel an order
   * 
   * A buyer may cancel freely for 24 hours. After that the merchant may have bought materials or turned down other work, so it needs them or Back Office.
   *
   * `POST /order/{orderId}/cancel`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: order:updateOwn | order:update
   * Ownership: scoped
   */
  cancel(orderId: string, body: CancelOrderRequest, options?: RequestOptions): Promise<OrderDetail> {
    return client().post<OrderDetail>(`/order/${seg(orderId)}/cancel`, body, withMeta(options, META.cancel));
  },

  /**
   * Buyer confirms receipt; escrow releases
   * 
   * The buyer confirms; the *platform* releases. No transition anywhere lets a merchant release their own escrow.
   *
   * `POST /order/{orderId}/confirm`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: order:updateOwn | order:update
   * Ownership: scoped
   */
  confirm(orderId: string, options?: RequestOptions): Promise<OrderSettlement> {
    return client().post<OrderSettlement>(`/order/${seg(orderId)}/confirm`, undefined, withMeta(options, META.confirm));
  },

  /**
   * Create a listing
   * 
   * Merchants and their sellers only. Always created as a draft — a listing goes live when `canPublish` agrees, which is a separate call.
   *
   * `POST /listings`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller
   * Permission: listing:create
   * Ownership: none
   */
  create(body: Listing, options?: RequestOptions): Promise<Listing> {
    return client().post<Listing>('/listings', body, withMeta(options, META.create));
  },

  /**
   * Raise a dispute; funds freeze
   * 
   * Clears `autoReleaseAt`, so a disputed order cannot quietly pay out while Back Office is reading it.
   *
   * `POST /order/{orderId}/dispute`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: order:updateOwn | order:update
   * Ownership: scoped
   */
  dispute(orderId: string, body: DisputeOrderRequest, options?: RequestOptions): Promise<OrderDetail> {
    return client().post<OrderDetail>(`/order/${seg(orderId)}/dispute`, body, withMeta(options, META.dispute));
  },

  /**
   * Merchant reports delivery; the release clock starts
   * 
   * Stamps `autoReleaseAt`. Escrow with no time limit does not protect the buyer — it strips the merchant, since a buyer holding their goods has no reason ever to confirm.
   *
   * `POST /order/{orderId}/fulfil`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller
   * Permission: order:update
   * Ownership: scoped
   */
  fulfil(orderId: string, body: FulfilOrderRequest, options?: RequestOptions): Promise<OrderDetail> {
    return client().post<OrderDetail>(`/order/${seg(orderId)}/fulfil`, body, withMeta(options, META.fulfil));
  },

  /**
   * Orders visible to the caller
   * 
   * Scoped in the data layer. A merchant asking for another merchant's orders gets an empty page, not a 403 that confirms the order exists.
   *
   * `GET /orders`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: order:read
   * Ownership: scoped
   */
  get(options?: ListOptions): Promise<Page<Order>> {
    return client().list<Order>('/orders', withMeta(options, META.get));
  },

  /**
   * One order, with what this caller may do next
   * 
   * `availableActions` is derived from the lifecycle table for this caller's side, so the client never reimplements the rules to decide which buttons to draw.
   *
   * `GET /order/{orderId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: order:read
   * Ownership: scoped
   */
  get2(orderId: string, options?: RequestOptions): Promise<OrderDetail> {
    return client().get<OrderDetail>(`/order/${seg(orderId)}`, withMeta(options, META.get2));
  },

  /**
   * One listing
   *
   * `GET /listing/{listingId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: listing:read
   * Ownership: none
   */
  getById(listingId: string, options?: RequestOptions): Promise<Listing> {
    return client().get<Listing>(`/listing/${seg(listingId)}`, withMeta(options, META.getById));
  },

  /**
   * Browse the marketplace catalogue
   * 
   * Defaults to published listings. A draft cannot leak into the catalogue because somebody forgot a filter.
   *
   * `GET /listings`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: listing:read
   * Ownership: none
   */
  list(options?: ListOptions): Promise<Page<Listing>> {
    return client().list<Listing>('/listings', withMeta(options, META.list));
  },

  /**
   * The merchant account's own catalogue, in every state
   *
   * `GET /listings/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: listing:read
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<MerchantCatalogue> {
    return client().get<MerchantCatalogue>('/listings/me', withMeta(options, META.me));
  },

  /**
   * Marketplace dashboard figures for the caller
   * 
   * Answers as merchant or as customer depending on which account the caller holds.
   *
   * `GET /marketplace/overview`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: marketplace:read
   * Ownership: self
   */
  overview(options?: RequestOptions): Promise<MarketplaceOverview> {
    return client().get<MarketplaceOverview>('/marketplace/overview', withMeta(options, META.overview));
  },

  /**
   * Pay — funds move to LRMC, not to the merchant
   * 
   * Stock comes down here, not at draft — an unpaid order holding stock empties a catalogue without a single sale.
   *
   * `POST /order/{orderId}/pay`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller, customer, buyer
   * Permission: order:updateOwn | order:update
   * Ownership: scoped
   */
  pay(orderId: string, body: PayOrderRequest, options?: RequestOptions): Promise<OrderDetail> {
    return client().post<OrderDetail>(`/order/${seg(orderId)}/pay`, body, withMeta(options, META.pay));
  },

  /**
   * Place an order
   * 
   * The client sends listing ids and quantities only. Prices are read from the listings and copied onto the lines — a client that could name its own prices would name zero.
   *
   * `POST /orders`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, customer, buyer
   * Permission: order:create
   * Ownership: none
   */
  post(body: PlaceOrderRequest, options?: RequestOptions): Promise<Order> {
    return client().post<Order>('/orders', body, withMeta(options, META.post));
  },

  /**
   * Put a listing live
   * 
   * Refuses with **every** problem at once rather than the first. An unverified merchant cannot publish at all — a marketplace listing unverified merchants owns its first fraud.
   *
   * `POST /listing/{listingId}/publish`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller
   * Permission: listing:update
   * Ownership: scoped
   */
  publish(listingId: string, options?: RequestOptions): Promise<Listing> {
    return client().post<Listing>(`/listing/${seg(listingId)}/publish`, undefined, withMeta(options, META.publish));
  },

  /**
   * Back Office rules on a dispute
   * 
   * The only human step in the marketplace. Commission is returned pro rata on a partial refund — keeping it in full would mean LRMC profits proportionally more the worse the service was.
   *
   * `POST /order/{orderId}/resolve`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: order:update
   * Ownership: none
   */
  resolve(orderId: string, body: ResolveDisputeRequest, options?: RequestOptions): Promise<OrderSettlement> {
    return client().post<OrderSettlement>(`/order/${seg(orderId)}/resolve`, body, withMeta(options, META.resolve));
  },

  /**
   * Back Office pulls a listing down
   *
   * `POST /listing/{listingId}/suspend`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: listing:review | listing:update
   * Ownership: none
   */
  suspend(listingId: string, body: SuspendListingRequest, options?: RequestOptions): Promise<Listing> {
    return client().post<Listing>(`/listing/${seg(listingId)}/suspend`, body, withMeta(options, META.suspend));
  },

  /**
   * Withdraw a listing to draft
   *
   * `POST /listing/{listingId}/unpublish`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller
   * Permission: listing:update
   * Ownership: scoped
   */
  unpublish(listingId: string, options?: RequestOptions): Promise<Listing> {
    return client().post<Listing>(`/listing/${seg(listingId)}/unpublish`, undefined, withMeta(options, META.unpublish));
  },

  /**
   * Amend a listing
   *
   * `PATCH /listing/{listingId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant, seller
   * Permission: listing:update
   * Ownership: scoped
   */
  update(listingId: string, body: Listing, options?: RequestOptions): Promise<Listing> {
    return client().patch<Listing>(`/listing/${seg(listingId)}`, body, withMeta(options, META.update));
  },
};

export type MarketplaceApi = typeof marketplace;
