/**
 * `merchant` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Merchant,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postMerchants', method: 'POST' as const, pathTemplate: '/merchants', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["merchantProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteMerchantByMerchantId', method: 'DELETE' as const, pathTemplate: '/merchant/{merchantId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["merchantProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getMerchantByMerchantId', method: 'GET' as const, pathTemplate: '/merchant/{merchantId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["merchantProfile:read","merchantProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getMerchants', method: 'GET' as const, pathTemplate: '/merchants', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["merchantProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getMerchantMe', method: 'GET' as const, pathTemplate: '/merchant/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","merchant","seller"] as Role[], permissions: ["merchantProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postMerchantByMerchantIdRestore', method: 'POST' as const, pathTemplate: '/merchant/{merchantId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["merchantProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchMerchantByMerchantId', method: 'PATCH' as const, pathTemplate: '/merchant/{merchantId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["merchantProfile:update","merchantProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchMerchantMe', method: 'PATCH' as const, pathTemplate: '/merchant/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","merchant"] as Role[], permissions: ["merchantProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchMerchantByMerchantIdVerify', method: 'PATCH' as const, pathTemplate: '/merchant/{merchantId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["merchantProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const merchant = {
  /**
   * Create a merchant profile
   *
   * `POST /merchants`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: merchantProfile:create
   * Ownership: none
   */
  create(body: Merchant, options?: RequestOptions): Promise<Merchant> {
    return client().post<Merchant>('/merchants', body, withMeta(options, META.create));
  },

  /**
   * Archive a merchant profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /merchant/{merchantId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: merchantProfile:delete
   * Ownership: none
   */
  delete(merchantId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/merchant/${seg(merchantId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one merchant profile
   *
   * `GET /merchant/{merchantId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: merchantProfile:read | merchantProfile:readOwn
   * Ownership: scoped
   */
  getById(merchantId: string, options?: RequestOptions): Promise<Merchant> {
    return client().get<Merchant>(`/merchant/${seg(merchantId)}`, withMeta(options, META.getById));
  },

  /**
   * List merchant profiles
   *
   * `GET /merchants`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: merchantProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Merchant>> {
    return client().list<Merchant>('/merchants', withMeta(options, META.list));
  },

  /**
   * Read the caller's own merchant profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /merchant/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, merchant, seller
   * Permission: merchantProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Merchant> {
    return client().get<Merchant>('/merchant/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived merchant profile
   *
   * `POST /merchant/{merchantId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: merchantProfile:update
   * Ownership: none
   */
  restore(merchantId: string, options?: RequestOptions): Promise<Merchant> {
    return client().post<Merchant>(`/merchant/${seg(merchantId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one merchant profile
   *
   * `PATCH /merchant/{merchantId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: merchantProfile:update | merchantProfile:updateOwn
   * Ownership: scoped
   */
  update(merchantId: string, body: Merchant, options?: RequestOptions): Promise<Merchant> {
    return client().patch<Merchant>(`/merchant/${seg(merchantId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own merchant profile
   *
   * `PATCH /merchant/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, merchant
   * Permission: merchantProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: Merchant, options?: RequestOptions): Promise<Merchant> {
    return client().patch<Merchant>('/merchant/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a merchant profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /merchant/{merchantId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: merchantProfile:verify
   * Ownership: none
   */
  verify(merchantId: string, body: VerificationRequest, options?: RequestOptions): Promise<Merchant> {
    return client().patch<Merchant>(`/merchant/${seg(merchantId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type MerchantApi = typeof merchant;
