/**
 * `notifications` — 5 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  BroadcastNotificationRequest,
  BroadcastResult,
  MarkNotificationRequest,
  Notification,
  NotificationDispatch,
  PushTokenRegistration,
  PushTokenRegistrationInput,
  SendTestNotificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  broadcast: { operationId: 'postNotificationsBroadcast', method: 'POST' as const, pathTemplate: '/notifications/broadcast', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["notification:create"], ownership: 'none' as const, auth: 'required' as const },
  inbox: { operationId: 'getNotificationsMe', method: 'GET' as const, pathTemplate: '/notifications/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser"] as Role[], permissions: ["notification:readOwn","notification:read"], ownership: 'self' as const, auth: 'required' as const },
  mark: { operationId: 'patchNotificationByNotificationId', method: 'PATCH' as const, pathTemplate: '/notification/{notificationId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser"] as Role[], permissions: ["notification:updateOwn","notification:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  registerToken: { operationId: 'postNotificationsRegisterToken', method: 'POST' as const, pathTemplate: '/notifications/register-token', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser"] as Role[], permissions: [], ownership: 'self' as const, auth: 'required' as const },
  sendTest: { operationId: 'postNotificationsTest', method: 'POST' as const, pathTemplate: '/notifications/test', zone: 'HQ_EXECUTIVE' as const, roles: ["founder","hqExecutive"] as Role[], permissions: ["notification:create"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const notifications = {
  /**
   * Broadcast to everyone holding a role
   * 
   * Founder and HQ executive only. Aimed at a role, never at a client-supplied recipient list. Capped, and the cap is reported rather than silently applied.
   *
   * `POST /notifications/broadcast`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: notification:create
   * Ownership: none
   */
  broadcast(body: BroadcastNotificationRequest, options?: RequestOptions): Promise<BroadcastResult> {
    return client().post<BroadcastResult>('/notifications/broadcast', body, withMeta(options, META.broadcast));
  },

  /**
   * The caller's own inbox
   *
   * `GET /notifications/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser
   * Permission: notification:readOwn | notification:read
   * Ownership: self
   */
  inbox(options?: ListOptions): Promise<Page<Notification>> {
    return client().list<Notification>('/notifications/me', withMeta(options, META.inbox));
  },

  /**
   * Mark one notification read or unread
   * 
   * Matched on recipient as well as id, so one member cannot mark another member's mail read.
   *
   * `PATCH /notification/{notificationId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser
   * Permission: notification:updateOwn | notification:readOwn
   * Ownership: self
   */
  mark(notificationId: string, body: MarkNotificationRequest, options?: RequestOptions): Promise<Notification> {
    return client().patch<Notification>(`/notification/${seg(notificationId)}`, body, withMeta(options, META.mark));
  },

  /**
   * Register this device for push
   * 
   * Upserts on the token, not on (user, device): a handset can change hands. The token is `select: false` and is stripped from the response — it is a capability to reach a phone.
   *
   * `POST /notifications/register-token`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser
   * Ownership: self
   */
  registerToken(body: PushTokenRegistrationInput, options?: RequestOptions): Promise<PushTokenRegistration> {
    return client().post<PushTokenRegistration>('/notifications/register-token', body, withMeta(options, META.registerToken));
  },

  /**
   * Send a test notification
   * 
   * Founder and HQ executive only. Exists so an operator can prove the pipe works without waiting for a real rent reminder to fall due.
   *
   * `POST /notifications/test`
   * Zone: HQ_EXECUTIVE
   * Roles: founder, hqExecutive
   * Permission: notification:create
   * Ownership: none
   */
  sendTest(body: SendTestNotificationRequest, options?: RequestOptions): Promise<NotificationDispatch> {
    return client().post<NotificationDispatch>('/notifications/test', body, withMeta(options, META.sendTest));
  },
};

export type NotificationsApi = typeof notifications;
