/**
 * `payments` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Payment,
  PaymentSummary,
  RecordPaymentRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  getById: { operationId: 'getPaymentByPaymentId', method: 'GET' as const, pathTemplate: '/payment/{paymentId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["payment:read","payment:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  history: { operationId: 'getPaymentsByUserIdHistory', method: 'GET' as const, pathTemplate: '/payments/{userId}/history', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getPayments', method: 'GET' as const, pathTemplate: '/payments', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["payment:read"], ownership: 'scoped' as const, auth: 'required' as const },
  mineAsAdvertiser: { operationId: 'getAdvertiserMePayments', method: 'GET' as const, pathTemplate: '/advertiser/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsDriver: { operationId: 'getDriverMePayments', method: 'GET' as const, pathTemplate: '/driver/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsLandlord: { operationId: 'getLandlordMePayments', method: 'GET' as const, pathTemplate: '/landlord/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsTenant: { operationId: 'getTenantMePayments', method: 'GET' as const, pathTemplate: '/tenant/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
  record: { operationId: 'postPaymentsRecord', method: 'POST' as const, pathTemplate: '/payments/record', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator"] as Role[], permissions: ["payment:record"], ownership: 'none' as const, auth: 'required' as const },
  summary: { operationId: 'getPaymentsByUserIdSummary', method: 'GET' as const, pathTemplate: '/payments/{userId}/summary', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const payments = {
  /**
   * Read one ledger row
   * 
   * `providerReference` is `select: false` and never leaves the server on a read.
   *
   * `GET /payment/{paymentId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: payment:read | payment:readOwn
   * Ownership: scoped
   */
  getById(paymentId: string, options?: RequestOptions): Promise<Payment> {
    return client().get<Payment>(`/payment/${seg(paymentId)}`, withMeta(options, META.getById));
  },

  /**
   * One person's ledger, narrowed to what the caller may see
   * 
   * A person always sees their own. Back Office, HQ and the founder see anyone's. A COORDINATOR SEES ONLY THE RECEIPTS THEY WROTE THEMSELVES — recording a payment and reading a year of somebody's finances are different powers, and holding the first does not grant the second. Anyone else is refused rather than answered with an empty list: "you may not see this" and "there is nothing here" are different facts.
   *
   * `GET /payments/{userId}/history`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: scoped
   */
  history(userId: string, options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>(`/payments/${seg(userId)}/history`, withMeta(options, META.history));
  },

  /**
   * The money ledger
   * 
   * One collection for every kind of money movement — rent, deposits, fares, payouts, ad spend, vendor invoices, fees, refunds.
   *
   * `GET /payments`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: payment:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/payments', withMeta(options, META.list));
  },

  /**
   * Ad spend billed to the signed-in advertiser
   *
   * `GET /advertiser/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsAdvertiser(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/advertiser/me/payments', withMeta(options, META.mineAsAdvertiser));
  },

  /**
   * Fares and payouts the signed-in driver has earned
   *
   * `GET /driver/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsDriver(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/driver/me/payments', withMeta(options, META.mineAsDriver));
  },

  /**
   * Rent and payouts the signed-in landlord has received
   *
   * `GET /landlord/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsLandlord(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/landlord/me/payments', withMeta(options, META.mineAsLandlord));
  },

  /**
   * Rent and deposits the signed-in tenant has paid
   *
   * `GET /tenant/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsTenant(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/tenant/me/payments', withMeta(options, META.mineAsTenant));
  },

  /**
   * Write down money that changed hands in person
   * 
   * The ledger is otherwise written only by the flows that cause it. This exists because The Gambia runs on cash and mobile money, and refusing to record a cash rent payment would leave a tenant who has paid on time for two years with `hasRecord: false` in their evidence — pushing the informal economy out of the scoring engine entirely. Fenced accordingly: ONLY rent and deposits (never a payout, which would mark money as sent that was never sent); NOBODY may record a payment they are party to as payer or payee; `recordedBy` comes from the token and can not be supplied; `status` is always succeeded and can not be supplied; the reference is derived from payer, subject, kind, amount and day so a double tap on a bad connection collides instead of doubling a tenant's rent — the collision is returned as a 409 for a person to resolve, never swallowed.
   *
   * `POST /payments/record`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator
   * Permission: payment:record
   * Ownership: none
   */
  record(body: RecordPaymentRequest, options?: RequestOptions): Promise<Payment> {
    return client().post<Payment>('/payments/record', body, withMeta(options, META.record));
  },

  /**
   * On-time record and settled totals for one person
   * 
   * Computed over the whole history, never a page. `onTimeRate` is (onTime / (onTime + late)) * 100 and is NULL when nothing has settled — never 0, which would tell somebody on their first day that none of their payments were on time. NOTE this is not the same figure as `paymentReliability` in an application assessment, which also counts missed instalments in the denominator; the two are labelled differently on purpose and must not be reconciled by relabelling one. `scope` and `partial` say whose rows the totals cover, so a coordinator reading their own receipts does not mistake them for the whole.
   *
   * `GET /payments/{userId}/summary`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: scoped
   */
  summary(userId: string, options?: RequestOptions): Promise<PaymentSummary> {
    return client().get<PaymentSummary>(`/payments/${seg(userId)}/summary`, withMeta(options, META.summary));
  },
};

export type PaymentsApi = typeof payments;
