/**
 * `payments` — 6 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Payment,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  getById: { operationId: 'getPaymentByPaymentId', method: 'GET' as const, pathTemplate: '/payment/{paymentId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["payment:read","payment:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getPayments', method: 'GET' as const, pathTemplate: '/payments', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["payment:read"], ownership: 'scoped' as const, auth: 'required' as const },
  mineAsAdvertiser: { operationId: 'getAdvertiserMePayments', method: 'GET' as const, pathTemplate: '/advertiser/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsDriver: { operationId: 'getDriverMePayments', method: 'GET' as const, pathTemplate: '/driver/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsLandlord: { operationId: 'getLandlordMePayments', method: 'GET' as const, pathTemplate: '/landlord/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsTenant: { operationId: 'getTenantMePayments', method: 'GET' as const, pathTemplate: '/tenant/me/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["payment:readOwn","payment:read"], ownership: 'self' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const payments = {
  /**
   * Read one ledger row
   * 
   * `providerReference` is `select: false` and never leaves the server on a read.
   *
   * `GET /payment/{paymentId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: payment:read | payment:readOwn
   * Ownership: scoped
   */
  getById(paymentId: string, options?: RequestOptions): Promise<Payment> {
    return client().get<Payment>(`/payment/${seg(paymentId)}`, withMeta(options, META.getById));
  },

  /**
   * The money ledger
   * 
   * One collection for every kind of money movement — rent, deposits, fares, payouts, ad spend, vendor invoices, fees, refunds.
   *
   * `GET /payments`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: payment:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/payments', withMeta(options, META.list));
  },

  /**
   * Ad spend billed to the signed-in advertiser
   *
   * `GET /advertiser/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsAdvertiser(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/advertiser/me/payments', withMeta(options, META.mineAsAdvertiser));
  },

  /**
   * Fares and payouts the signed-in driver has earned
   *
   * `GET /driver/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsDriver(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/driver/me/payments', withMeta(options, META.mineAsDriver));
  },

  /**
   * Rent and payouts the signed-in landlord has received
   *
   * `GET /landlord/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsLandlord(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/landlord/me/payments', withMeta(options, META.mineAsLandlord));
  },

  /**
   * Rent and deposits the signed-in tenant has paid
   *
   * `GET /tenant/me/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: payment:readOwn | payment:read
   * Ownership: self
   */
  mineAsTenant(options?: ListOptions): Promise<Page<Payment>> {
    return client().list<Payment>('/tenant/me/payments', withMeta(options, META.mineAsTenant));
  },
};

export type PaymentsApi = typeof payments;
