/**
 * `payoutBatches` — 6 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  BuildPayoutBatchRequest,
  CancelPayoutBatchRequest,
  PayoutBatch,
  PayoutLine,
  PayoutSettlement,
  SettlePayoutBatchRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  build: { operationId: 'postPayoutBatches', method: 'POST' as const, pathTemplate: '/payout-batches', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["payout:create"], ownership: 'none' as const, auth: 'required' as const },
  cancel: { operationId: 'postPayoutBatchByBatchIdCancel', method: 'POST' as const, pathTemplate: '/payout-batch/{batchId}/cancel', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["payout:update"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getPayoutBatchByBatchId', method: 'GET' as const, pathTemplate: '/payout-batch/{batchId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["payout:read"], ownership: 'none' as const, auth: 'required' as const },
  lines: { operationId: 'getPayoutBatchByBatchIdLines', method: 'GET' as const, pathTemplate: '/payout-batch/{batchId}/lines', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["payout:read"], ownership: 'none' as const, auth: 'required' as const },
  list: { operationId: 'getPayoutBatches', method: 'GET' as const, pathTemplate: '/payout-batches', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["payout:read"], ownership: 'none' as const, auth: 'required' as const },
  settle: { operationId: 'postPayoutBatchByBatchIdSettle', method: 'POST' as const, pathTemplate: '/payout-batch/{batchId}/settle', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: ["payout:settle"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const payoutBatches = {
  /**
   * Build a payout batch from the ledger
   * 
   * The request is a query — kind, currency, window — and the server computes the lines. Nothing a client sends becomes an amount. Rows already claimed by a live batch are excluded, so nobody is paid twice.
   *
   * `POST /payout-batches`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: payout:create
   * Ownership: none
   */
  build(body: BuildPayoutBatchRequest, options?: RequestOptions): Promise<PayoutBatch> {
    return client().post<PayoutBatch>('/payout-batches', body, withMeta(options, META.build));
  },

  /**
   * Cancel a batch before it settles
   * 
   * Only from `draft` or `approved`. A batch already with the rail cannot be recalled here.
   *
   * `POST /payout-batch/{batchId}/cancel`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: payout:update
   * Ownership: none
   */
  cancel(batchId: string, body: CancelPayoutBatchRequest, options?: RequestOptions): Promise<PayoutBatch> {
    return client().post<PayoutBatch>(`/payout-batch/${seg(batchId)}/cancel`, body, withMeta(options, META.cancel));
  },

  /**
   * Read one payout batch
   *
   * `GET /payout-batch/{batchId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: payout:read
   * Ownership: none
   */
  getById(batchId: string, options?: RequestOptions): Promise<PayoutBatch> {
    return client().get<PayoutBatch>(`/payout-batch/${seg(batchId)}`, withMeta(options, META.getById));
  },

  /**
   * The lines of a batch, paged
   *
   * `GET /payout-batch/{batchId}/lines`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: payout:read
   * Ownership: none
   */
  lines(batchId: string, options?: ListOptions): Promise<Page<PayoutLine>> {
    return client().list<PayoutLine>(`/payout-batch/${seg(batchId)}/lines`, withMeta(options, META.lines));
  },

  /**
   * List payout batches
   * 
   * A batch is an instruction to move money; `Payment` records money that has moved. Keeping them apart is what lets the ledger stay read-only over HTTP while payouts still have a create route.
   *
   * `GET /payout-batches`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: payout:read
   * Ownership: none
   */
  list(options?: ListOptions): Promise<Page<PayoutBatch>> {
    return client().list<PayoutBatch>('/payout-batches', withMeta(options, META.list));
  },

  /**
   * Release the money
   * 
   * Founder-only. Back Office assembles, a principal releases. The caller must echo the net total, and each transfer carries the line id as its idempotency key so a retried settle does not pay twice. Never reports `settled`: the rail returns `pending` and the batch moves to `settling`.
   *
   * `POST /payout-batch/{batchId}/settle`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Permission: payout:settle
   * Ownership: none
   */
  settle(batchId: string, body: SettlePayoutBatchRequest, options?: RequestOptions): Promise<PayoutSettlement> {
    return client().post<PayoutSettlement>(`/payout-batch/${seg(batchId)}/settle`, body, withMeta(options, META.settle));
  },
};

export type PayoutBatchesApi = typeof payoutBatches;
