/**
 * `properties` — 6 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Property,
  PropertyInput,
  PublicListing,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postProperties', method: 'POST' as const, pathTemplate: '/properties', zone: 'MEMBER_PORTAL' as const, roles: ["founder","landlord","airbnbHost","hotelManager","resortManager"] as Role[], permissions: ["property:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deletePropertyByPropertyId', method: 'DELETE' as const, pathTemplate: '/property/{propertyId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder"] as Role[], permissions: ["property:delete"], ownership: 'scoped' as const, auth: 'required' as const },
  getById: { operationId: 'getPropertyByPropertyId', method: 'GET' as const, pathTemplate: '/property/{propertyId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager"] as Role[], permissions: ["property:read","property:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getProperties', method: 'GET' as const, pathTemplate: '/properties', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager"] as Role[], permissions: ["property:read","property:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  searchPublic: { operationId: 'getPropertiesPublic', method: 'GET' as const, pathTemplate: '/properties/public', zone: 'PUBLIC_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  update: { operationId: 'patchPropertyByPropertyId', method: 'PATCH' as const, pathTemplate: '/property/{propertyId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord","airbnbHost","hotelManager","resortManager"] as Role[], permissions: ["property:update","property:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const properties = {
  /**
   * Add a property, unit, room or villa
   * 
   * Polymorphic owner: ownerKind ∈ {LandlordProfile, AirbnbHostProfile, HotelProfile, ResortProfile}.
   *
   * `POST /properties`
   * Zone: MEMBER_PORTAL
   * Roles: founder, landlord, airbnbHost, hotelManager, resortManager
   * Permission: property:create
   * Ownership: none
   */
  create(body: PropertyInput, options?: RequestOptions): Promise<Property> {
    return client().post<Property>('/properties', body, withMeta(options, META.create));
  },

  /**
   * Archive a property
   *
   * `DELETE /property/{propertyId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder
   * Permission: property:delete
   * Ownership: scoped
   */
  delete(propertyId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/property/${seg(propertyId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one property
   *
   * `GET /property/{propertyId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager
   * Permission: property:read | property:readOwn
   * Ownership: scoped
   */
  getById(propertyId: string, options?: RequestOptions): Promise<Property> {
    return client().get<Property>(`/property/${seg(propertyId)}`, withMeta(options, META.getById));
  },

  /**
   * List properties
   *
   * `GET /properties`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager
   * Permission: property:read | property:readOwn
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Property>> {
    return client().list<Property>('/properties', withMeta(options, META.list));
  },

  /**
   * Public listing search
   * 
   * Explicit projection, not a select:false blacklist — a public endpoint should name what it reveals. Only listedPublicly && active && not occupied.
   *
   * `GET /properties/public`
   * Zone: PUBLIC_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, publicUser
   * Ownership: none
   */
  searchPublic(options?: ListOptions): Promise<Page<PublicListing>> {
    return client().list<PublicListing>('/properties/public', withMeta(options, META.searchPublic));
  },

  /**
   * Update one property
   *
   * `PATCH /property/{propertyId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord, airbnbHost, hotelManager, resortManager
   * Permission: property:update | property:updateOwn
   * Ownership: scoped
   */
  update(propertyId: string, body: PropertyInput, options?: RequestOptions): Promise<Property> {
    return client().patch<Property>(`/property/${seg(propertyId)}`, body, withMeta(options, META.update));
  },
};

export type PropertiesApi = typeof properties;
