/**
 * `public` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  PublicContent,
  PublicContentInput,
  TrackAccepted,
  TrafficEventRequest,
  TrafficMetrics,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  archiveContent: { operationId: 'deletePublicAdminContentByContentId', method: 'DELETE' as const, pathTemplate: '/public/admin/content/{contentId}', zone: 'PUBLIC_PORTAL' as const, roles: ["founder"] as Role[], permissions: ["publicContent:delete"], ownership: 'none' as const, auth: 'required' as const },
  createContent: { operationId: 'postPublicAdminContent', method: 'POST' as const, pathTemplate: '/public/admin/content', zone: 'PUBLIC_PORTAL' as const, roles: ["founder"] as Role[], permissions: ["publicContent:create"], ownership: 'none' as const, auth: 'required' as const },
  getContent: { operationId: 'getPublicContentBySlug', method: 'GET' as const, pathTemplate: '/public/content/{slug}', zone: 'PUBLIC_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  listAllContent: { operationId: 'getPublicAdminContent', method: 'GET' as const, pathTemplate: '/public/admin/content', zone: 'PUBLIC_PORTAL' as const, roles: ["founder","publicUser"] as Role[], permissions: ["publicContent:read"], ownership: 'none' as const, auth: 'required' as const },
  listContent: { operationId: 'getPublicContent', method: 'GET' as const, pathTemplate: '/public/content', zone: 'PUBLIC_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  metrics: { operationId: 'getPublicMetrics', method: 'GET' as const, pathTemplate: '/public/metrics', zone: 'PUBLIC_PORTAL' as const, roles: ["founder","hqExecutive","publicUser"] as Role[], permissions: ["publicMetrics:read"], ownership: 'none' as const, auth: 'required' as const },
  publishContent: { operationId: 'postPublicAdminContentByContentIdPublish', method: 'POST' as const, pathTemplate: '/public/admin/content/{contentId}/publish', zone: 'PUBLIC_PORTAL' as const, roles: ["founder"] as Role[], permissions: ["publicContent:publish"], ownership: 'none' as const, auth: 'required' as const },
  track: { operationId: 'postPublicTrack', method: 'POST' as const, pathTemplate: '/public/track', zone: 'PUBLIC_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  updateContent: { operationId: 'patchPublicAdminContentByContentId', method: 'PATCH' as const, pathTemplate: '/public/admin/content/{contentId}', zone: 'PUBLIC_PORTAL' as const, roles: ["founder"] as Role[], permissions: ["publicContent:update"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const publicApi = {
  /**
   * Archive content
   *
   * `DELETE /public/admin/content/{contentId}`
   * Zone: PUBLIC_PORTAL
   * Roles: founder
   * Permission: publicContent:delete
   * Ownership: none
   */
  archiveContent(contentId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/public/admin/content/${seg(contentId)}`, withMeta(options, META.archiveContent));
  },

  /**
   * Create content
   *
   * `POST /public/admin/content`
   * Zone: PUBLIC_PORTAL
   * Roles: founder
   * Permission: publicContent:create
   * Ownership: none
   */
  createContent(body: PublicContentInput, options?: RequestOptions): Promise<PublicContent> {
    return client().post<PublicContent>('/public/admin/content', body, withMeta(options, META.createContent));
  },

  /**
   * One published page; increments its view counter
   *
   * `GET /public/content/{slug}`
   * Zone: PUBLIC_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  getContent(slug: string, options?: RequestOptions): Promise<PublicContent> {
    return client().get<PublicContent>(`/public/content/${seg(slug)}`, withMeta(options, META.getContent));
  },

  /**
   * List all content including drafts
   *
   * `GET /public/admin/content`
   * Zone: PUBLIC_PORTAL
   * Roles: founder, publicUser
   * Permission: publicContent:read
   * Ownership: none
   */
  listAllContent(options?: ListOptions): Promise<Page<PublicContent>> {
    return client().list<PublicContent>('/public/admin/content', withMeta(options, META.listAllContent));
  },

  /**
   * Published content, filterable by type, domain and locale
   *
   * `GET /public/content`
   * Zone: PUBLIC_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  listContent(options?: ListOptions): Promise<Page<PublicContent>> {
    return client().list<PublicContent>('/public/content', withMeta(options, META.listContent));
  },

  /**
   * Page views, sessions, conversion rate, top paths, device split
   *
   * `GET /public/metrics`
   * Zone: PUBLIC_PORTAL
   * Roles: founder, hqExecutive, publicUser
   * Permission: publicMetrics:read
   * Ownership: none
   */
  metrics(options?: RequestOptions): Promise<TrafficMetrics> {
    return client().get<TrafficMetrics>('/public/metrics', withMeta(options, META.metrics));
  },

  /**
   * Publish content
   *
   * `POST /public/admin/content/{contentId}/publish`
   * Zone: PUBLIC_PORTAL
   * Roles: founder
   * Permission: publicContent:publish
   * Ownership: none
   */
  publishContent(contentId: string, options?: RequestOptions): Promise<PublicContent> {
    return client().post<PublicContent>(`/public/admin/content/${seg(contentId)}/publish`, undefined, withMeta(options, META.publishContent));
  },

  /**
   * Record a page view or conversion
   *
   * `POST /public/track`
   * Zone: PUBLIC_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  track(body: TrafficEventRequest, options?: RequestOptions): Promise<TrackAccepted> {
    return client().post<TrackAccepted>('/public/track', body, withMeta(options, META.track));
  },

  /**
   * Update content
   *
   * `PATCH /public/admin/content/{contentId}`
   * Zone: PUBLIC_PORTAL
   * Roles: founder
   * Permission: publicContent:update
   * Ownership: none
   */
  updateContent(contentId: string, body: PublicContentInput, options?: RequestOptions): Promise<PublicContent> {
    return client().patch<PublicContent>(`/public/admin/content/${seg(contentId)}`, body, withMeta(options, META.updateContent));
  },
};

export type PublicApi = typeof publicApi;
