/**
 * `rbac` — 3 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AssignRolesRequest,
  ResolvedRoles,
  RoleCatalogue,
  User,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  assignRoles: { operationId: 'patchAuthUserByUserIdRoles', method: 'PATCH' as const, pathTemplate: '/auth/user/{userId}/roles', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
  catalogue: { operationId: 'getAuthRoles', method: 'GET' as const, pathTemplate: '/auth/roles', zone: null, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'none' as const },
  resolve: { operationId: 'getAuthResolve', method: 'GET' as const, pathTemplate: '/auth/resolve', zone: 'FOUNDER_COMMAND_CENTER' as const, roles: ["founder"] as Role[], permissions: [], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const rbac = {
  /**
   * Appoint roles and regions to a user
   * 
   * Founder-only via `requireFounder`. Appointment is a constitutional act.
   *
   * `PATCH /auth/user/{userId}/roles`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Ownership: none
   */
  assignRoles(userId: string, body: AssignRolesRequest, options?: RequestOptions): Promise<User> {
    return client().patch<User>(`/auth/user/${seg(userId)}/roles`, body, withMeta(options, META.assignRoles));
  },

  /**
   * The public RBAC contract: every role, scope, permission, zone, action
   *
   * `GET /auth/roles`
   * Zone: —
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, publicUser
   * Ownership: none
   */
  catalogue(options?: RequestOptions): Promise<RoleCatalogue> {
    return client().get<RoleCatalogue>('/auth/roles', withMeta(options, META.catalogue));
  },

  /**
   * Debug: resolve a hypothetical role combination to grants and actions
   * 
   * Founder-only.
   *
   * `GET /auth/resolve`
   * Zone: FOUNDER_COMMAND_CENTER
   * Roles: founder
   * Ownership: none
   */
  resolve(options?: RequestOptions): Promise<ResolvedRoles> {
    return client().get<ResolvedRoles>('/auth/resolve', withMeta(options, META.resolve));
  },
};

export type RbacApi = typeof rbac;
