/**
 * `rentalCarCompanies` — 11 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  FleetUtilization,
  FleetVehicle,
  RentalCarCompany,
  RentalCarCompanyInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  addVehicle: { operationId: 'postRentalCarCompanyByCompanyIdFleet', method: 'POST' as const, pathTemplate: '/rental-car-company/{companyId}/fleet', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","rentalCarCompany"] as Role[], permissions: ["rentalCarCompanyProfile:updateOwn","rentalCarCompanyProfile:update"], ownership: 'scoped' as const, auth: 'required' as const },
  create: { operationId: 'postRentalCarCompanies', method: 'POST' as const, pathTemplate: '/rental-car-companies', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["rentalCarCompanyProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteRentalCarCompanyByCompanyId', method: 'DELETE' as const, pathTemplate: '/rental-car-company/{companyId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["rentalCarCompanyProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getRentalCarCompanyByCompanyId', method: 'GET' as const, pathTemplate: '/rental-car-company/{companyId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["rentalCarCompanyProfile:read","rentalCarCompanyProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getRentalCarCompanies', method: 'GET' as const, pathTemplate: '/rental-car-companies', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["rentalCarCompanyProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getRentalCarCompanyMe', method: 'GET' as const, pathTemplate: '/rental-car-company/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","rentalCarCompany"] as Role[], permissions: ["rentalCarCompanyProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postRentalCarCompanyByCompanyIdRestore', method: 'POST' as const, pathTemplate: '/rental-car-company/{companyId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["rentalCarCompanyProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchRentalCarCompanyByCompanyId', method: 'PATCH' as const, pathTemplate: '/rental-car-company/{companyId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["rentalCarCompanyProfile:update","rentalCarCompanyProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchRentalCarCompanyMe', method: 'PATCH' as const, pathTemplate: '/rental-car-company/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","rentalCarCompany"] as Role[], permissions: ["rentalCarCompanyProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  utilization: { operationId: 'getRentalCarCompanyByCompanyIdUtilization', method: 'GET' as const, pathTemplate: '/rental-car-company/{companyId}/utilization', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","rentalCarCompany"] as Role[], permissions: ["rentalCarCompanyProfile:readOwn","rentalCarCompanyProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  verify: { operationId: 'patchRentalCarCompanyByCompanyIdVerify', method: 'PATCH' as const, pathTemplate: '/rental-car-company/{companyId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["rentalCarCompanyProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const rentalCarCompanies = {
  /**
   * Append a vehicle to the fleet
   * 
   * $push, so two concurrent additions do not clobber each other.
   *
   * `POST /rental-car-company/{companyId}/fleet`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, rentalCarCompany
   * Permission: rentalCarCompanyProfile:updateOwn | rentalCarCompanyProfile:update
   * Ownership: scoped
   */
  addVehicle(companyId: string, body: FleetVehicle, options?: RequestOptions): Promise<RentalCarCompany> {
    return client().post<RentalCarCompany>(`/rental-car-company/${seg(companyId)}/fleet`, body, withMeta(options, META.addVehicle));
  },

  /**
   * Create a rental car company profile
   *
   * `POST /rental-car-companies`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: rentalCarCompanyProfile:create
   * Ownership: none
   */
  create(body: RentalCarCompanyInput, options?: RequestOptions): Promise<RentalCarCompany> {
    return client().post<RentalCarCompany>('/rental-car-companies', body, withMeta(options, META.create));
  },

  /**
   * Archive a rental car company profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /rental-car-company/{companyId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: rentalCarCompanyProfile:delete
   * Ownership: none
   */
  delete(companyId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/rental-car-company/${seg(companyId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one rental car company profile
   *
   * `GET /rental-car-company/{companyId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: rentalCarCompanyProfile:read | rentalCarCompanyProfile:readOwn
   * Ownership: scoped
   */
  getById(companyId: string, options?: RequestOptions): Promise<RentalCarCompany> {
    return client().get<RentalCarCompany>(`/rental-car-company/${seg(companyId)}`, withMeta(options, META.getById));
  },

  /**
   * List rental car company profiles
   *
   * `GET /rental-car-companies`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: rentalCarCompanyProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<RentalCarCompany>> {
    return client().list<RentalCarCompany>('/rental-car-companies', withMeta(options, META.list));
  },

  /**
   * Read the caller's own rental car company profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /rental-car-company/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, rentalCarCompany
   * Permission: rentalCarCompanyProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<RentalCarCompany> {
    return client().get<RentalCarCompany>('/rental-car-company/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived rental car company profile
   *
   * `POST /rental-car-company/{companyId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: rentalCarCompanyProfile:update
   * Ownership: none
   */
  restore(companyId: string, options?: RequestOptions): Promise<RentalCarCompany> {
    return client().post<RentalCarCompany>(`/rental-car-company/${seg(companyId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one rental car company profile
   *
   * `PATCH /rental-car-company/{companyId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: rentalCarCompanyProfile:update | rentalCarCompanyProfile:updateOwn
   * Ownership: scoped
   */
  update(companyId: string, body: RentalCarCompanyInput, options?: RequestOptions): Promise<RentalCarCompany> {
    return client().patch<RentalCarCompany>(`/rental-car-company/${seg(companyId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own rental car company profile
   *
   * `PATCH /rental-car-company/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, rentalCarCompany
   * Permission: rentalCarCompanyProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: RentalCarCompanyInput, options?: RequestOptions): Promise<RentalCarCompany> {
    return client().patch<RentalCarCompany>('/rental-car-company/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Fleet size, utilisation percentage, breakdown by availability
   *
   * `GET /rental-car-company/{companyId}/utilization`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, rentalCarCompany
   * Permission: rentalCarCompanyProfile:readOwn | rentalCarCompanyProfile:read
   * Ownership: scoped
   */
  utilization(companyId: string, options?: RequestOptions): Promise<FleetUtilization> {
    return client().get<FleetUtilization>(`/rental-car-company/${seg(companyId)}/utilization`, withMeta(options, META.utilization));
  },

  /**
   * Advance verification on a rental car company profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /rental-car-company/{companyId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: rentalCarCompanyProfile:verify
   * Ownership: none
   */
  verify(companyId: string, body: VerificationRequest, options?: RequestOptions): Promise<RentalCarCompany> {
    return client().patch<RentalCarCompany>(`/rental-car-company/${seg(companyId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type RentalCarCompaniesApi = typeof rentalCarCompanies;
