/**
 * `resorts` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Resort,
  ResortInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postResorts', method: 'POST' as const, pathTemplate: '/resorts', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["resortProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteResortByResortId', method: 'DELETE' as const, pathTemplate: '/resort/{resortId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["resortProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getResortByResortId', method: 'GET' as const, pathTemplate: '/resort/{resortId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["resortProfile:read","resortProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getResorts', method: 'GET' as const, pathTemplate: '/resorts', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["resortProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getResortMe', method: 'GET' as const, pathTemplate: '/resort/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","resortManager"] as Role[], permissions: ["resortProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postResortByResortIdRestore', method: 'POST' as const, pathTemplate: '/resort/{resortId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["resortProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchResortByResortId', method: 'PATCH' as const, pathTemplate: '/resort/{resortId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["resortProfile:update","resortProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchResortMe', method: 'PATCH' as const, pathTemplate: '/resort/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","resortManager"] as Role[], permissions: ["resortProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchResortByResortIdVerify', method: 'PATCH' as const, pathTemplate: '/resort/{resortId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["resortProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const resorts = {
  /**
   * Create a resort profile
   *
   * `POST /resorts`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: resortProfile:create
   * Ownership: none
   */
  create(body: ResortInput, options?: RequestOptions): Promise<Resort> {
    return client().post<Resort>('/resorts', body, withMeta(options, META.create));
  },

  /**
   * Archive a resort profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /resort/{resortId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: resortProfile:delete
   * Ownership: none
   */
  delete(resortId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/resort/${seg(resortId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one resort profile
   *
   * `GET /resort/{resortId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: resortProfile:read | resortProfile:readOwn
   * Ownership: scoped
   */
  getById(resortId: string, options?: RequestOptions): Promise<Resort> {
    return client().get<Resort>(`/resort/${seg(resortId)}`, withMeta(options, META.getById));
  },

  /**
   * List resort profiles
   *
   * `GET /resorts`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: resortProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Resort>> {
    return client().list<Resort>('/resorts', withMeta(options, META.list));
  },

  /**
   * Read the caller's own resort profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /resort/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, resortManager
   * Permission: resortProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Resort> {
    return client().get<Resort>('/resort/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived resort profile
   *
   * `POST /resort/{resortId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: resortProfile:update
   * Ownership: none
   */
  restore(resortId: string, options?: RequestOptions): Promise<Resort> {
    return client().post<Resort>(`/resort/${seg(resortId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one resort profile
   *
   * `PATCH /resort/{resortId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: resortProfile:update | resortProfile:updateOwn
   * Ownership: scoped
   */
  update(resortId: string, body: ResortInput, options?: RequestOptions): Promise<Resort> {
    return client().patch<Resort>(`/resort/${seg(resortId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own resort profile
   *
   * `PATCH /resort/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, resortManager
   * Permission: resortProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: ResortInput, options?: RequestOptions): Promise<Resort> {
    return client().patch<Resort>('/resort/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a resort profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /resort/{resortId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: resortProfile:verify
   * Ownership: none
   */
  verify(resortId: string, body: VerificationRequest, options?: RequestOptions): Promise<Resort> {
    return client().patch<Resort>(`/resort/${seg(resortId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type ResortsApi = typeof resorts;
