/**
 * `rides` — 12 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AcceptRideRequest,
  CancelRideRequest,
  CompleteRideRequest,
  RequestRideRequest,
  Ride,
  RideMatchResult,
  StartRideRequest,
  UpdateRideRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  accept: { operationId: 'postRideByRideIdAccept', method: 'POST' as const, pathTemplate: '/ride/{rideId}/accept', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["ride:update","ride:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  cancel: { operationId: 'postRideByRideIdCancel', method: 'POST' as const, pathTemplate: '/ride/{rideId}/cancel', zone: 'MEMBER_PORTAL' as const, roles: ["founder","driver","rider"] as Role[], permissions: ["ride:update"], ownership: 'scoped' as const, auth: 'required' as const },
  complete: { operationId: 'postRideByRideIdComplete', method: 'POST' as const, pathTemplate: '/ride/{rideId}/complete', zone: 'MEMBER_PORTAL' as const, roles: ["founder","driver","rider"] as Role[], permissions: ["ride:update"], ownership: 'scoped' as const, auth: 'required' as const },
  dispatchQueue: { operationId: 'getDriverMeDispatchQueue', method: 'GET' as const, pathTemplate: '/driver/me/dispatch-queue', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["ride:readOwn","ride:read"], ownership: 'self' as const, auth: 'required' as const },
  getById: { operationId: 'getRideByRideId', method: 'GET' as const, pathTemplate: '/ride/{rideId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["ride:read","ride:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getRides', method: 'GET' as const, pathTemplate: '/rides', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["ride:read","ride:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  matches: { operationId: 'getRideByRideIdMatches', method: 'GET' as const, pathTemplate: '/ride/{rideId}/matches', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["ride:read","ride:update"], ownership: 'scoped' as const, auth: 'required' as const },
  mineAsDriver: { operationId: 'getDriverMeRides', method: 'GET' as const, pathTemplate: '/driver/me/rides', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["ride:readOwn","ride:read"], ownership: 'self' as const, auth: 'required' as const },
  mineAsRider: { operationId: 'getRiderMeRides', method: 'GET' as const, pathTemplate: '/rider/me/rides', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["ride:readOwn","ride:read"], ownership: 'self' as const, auth: 'required' as const },
  request: { operationId: 'postRidesRequests', method: 'POST' as const, pathTemplate: '/rides/requests', zone: 'MEMBER_PORTAL' as const, roles: ["founder","rider"] as Role[], permissions: ["ride:create"], ownership: 'self' as const, auth: 'required' as const },
  start: { operationId: 'postRideByRideIdStart', method: 'POST' as const, pathTemplate: '/ride/{rideId}/start', zone: 'MEMBER_PORTAL' as const, roles: ["founder","driver","rider"] as Role[], permissions: ["ride:update"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchRideByRideId', method: 'PATCH' as const, pathTemplate: '/ride/{rideId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","driver","rider"] as Role[], permissions: ["ride:update"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const rides = {
  /**
   * A driver claims the ride
   * 
   * Verified drivers only. Guarded by `RIDE_TRANSITIONS` and an optimistic-concurrency filter on the current status, so two drivers cannot both claim one ride.
   *
   * `POST /ride/{rideId}/accept`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: ride:update | ride:readOwn
   * Ownership: self
   */
  accept(rideId: string, body: AcceptRideRequest, options?: RequestOptions): Promise<Ride> {
    return client().post<Ride>(`/ride/${seg(rideId)}/accept`, body, withMeta(options, META.accept));
  },

  /**
   * Cancel a ride
   * 
   * Resolves to `cancelledByDriver` or `cancelledByRider` from the caller's role, so the cancellation rate attaches to whoever actually cancelled.
   *
   * `POST /ride/{rideId}/cancel`
   * Zone: MEMBER_PORTAL
   * Roles: founder, driver, rider
   * Permission: ride:update
   * Ownership: scoped
   */
  cancel(rideId: string, body: CancelRideRequest, options?: RequestOptions): Promise<Ride> {
    return client().post<Ride>(`/ride/${seg(rideId)}/cancel`, body, withMeta(options, META.cancel));
  },

  /**
   * The trip ends: stamp the fare and write the ledger row
   * 
   * Splits the platform commission and creates the `Payment` in the same request — a completed ride with no ledger row is an earnings dispute.
   *
   * `POST /ride/{rideId}/complete`
   * Zone: MEMBER_PORTAL
   * Roles: founder, driver, rider
   * Permission: ride:update
   * Ownership: scoped
   */
  complete(rideId: string, body: CompleteRideRequest, options?: RequestOptions): Promise<Ride> {
    return client().post<Ride>(`/ride/${seg(rideId)}/complete`, body, withMeta(options, META.complete));
  },

  /**
   * Unclaimed rides the signed-in driver could take
   * 
   * Verified drivers only, narrowed to the driver's own region, oldest request first.
   *
   * `GET /driver/me/dispatch-queue`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: ride:readOwn | ride:read
   * Ownership: self
   */
  dispatchQueue(options?: ListOptions): Promise<Page<Ride>> {
    return client().list<Ride>('/driver/me/dispatch-queue', withMeta(options, META.dispatchQueue));
  },

  /**
   * Read one ride
   *
   * `GET /ride/{rideId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: ride:read | ride:readOwn
   * Ownership: scoped
   */
  getById(rideId: string, options?: RequestOptions): Promise<Ride> {
    return client().get<Ride>(`/ride/${seg(rideId)}`, withMeta(options, META.getById));
  },

  /**
   * List rides
   *
   * `GET /rides`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: ride:read | ride:readOwn
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Ride>> {
    return client().list<Ride>('/rides', withMeta(options, META.list));
  },

  /**
   * Ranked driver candidates for a ride
   * 
   * Hard filters first (verified, active, fresh heartbeat, right vehicle, in region, within radius), then a weighted score. The rejection tally comes back too. Deterministic: ties break on driver id.
   *
   * `GET /ride/{rideId}/matches`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: ride:read | ride:update
   * Ownership: scoped
   */
  matches(rideId: string, options?: RequestOptions): Promise<RideMatchResult> {
    return client().get<RideMatchResult>(`/ride/${seg(rideId)}/matches`, withMeta(options, META.matches));
  },

  /**
   * The signed-in driver's trip history
   *
   * `GET /driver/me/rides`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: ride:readOwn | ride:read
   * Ownership: self
   */
  mineAsDriver(options?: ListOptions): Promise<Page<Ride>> {
    return client().list<Ride>('/driver/me/rides', withMeta(options, META.mineAsDriver));
  },

  /**
   * The signed-in rider's trip history
   *
   * `GET /rider/me/rides`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: ride:readOwn | ride:read
   * Ownership: self
   */
  mineAsRider(options?: ListOptions): Promise<Page<Ride>> {
    return client().list<Ride>('/rider/me/rides', withMeta(options, META.mineAsRider));
  },

  /**
   * A rider asks for a trip
   * 
   * The rider is resolved from the token, never from the body. Fare and driver are the server's to decide; the ride opens in `searching`.
   *
   * `POST /rides/requests`
   * Zone: MEMBER_PORTAL
   * Roles: founder, rider
   * Permission: ride:create
   * Ownership: self
   */
  request(body: RequestRideRequest, options?: RequestOptions): Promise<Ride> {
    return client().post<Ride>('/rides/requests', body, withMeta(options, META.request));
  },

  /**
   * The trip begins
   *
   * `POST /ride/{rideId}/start`
   * Zone: MEMBER_PORTAL
   * Roles: founder, driver, rider
   * Permission: ride:update
   * Ownership: scoped
   */
  start(rideId: string, body: StartRideRequest, options?: RequestOptions): Promise<Ride> {
    return client().post<Ride>(`/ride/${seg(rideId)}/start`, body, withMeta(options, META.start));
  },

  /**
   * Correct a ride record
   * 
   * Lifecycle changes go through the transition endpoints; this is for corrections only.
   *
   * `PATCH /ride/{rideId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, driver, rider
   * Permission: ride:update
   * Ownership: scoped
   */
  update(rideId: string, body: UpdateRideRequest, options?: RequestOptions): Promise<Ride> {
    return client().patch<Ride>(`/ride/${seg(rideId)}`, body, withMeta(options, META.update));
  },
};

export type RidesApi = typeof rides;
