/**
 * `riders` — 8 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Rider,
  RiderInput,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postRiders', method: 'POST' as const, pathTemplate: '/riders', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["riderProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteRiderByRiderId', method: 'DELETE' as const, pathTemplate: '/rider/{riderId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["riderProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getRiderByRiderId', method: 'GET' as const, pathTemplate: '/rider/{riderId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["riderProfile:read","riderProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getRiders', method: 'GET' as const, pathTemplate: '/riders', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["riderProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getRiderMe', method: 'GET' as const, pathTemplate: '/rider/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","driver","rider"] as Role[], permissions: ["riderProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postRiderByRiderIdRestore', method: 'POST' as const, pathTemplate: '/rider/{riderId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["riderProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchRiderByRiderId', method: 'PATCH' as const, pathTemplate: '/rider/{riderId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["riderProfile:update","riderProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchRiderMe', method: 'PATCH' as const, pathTemplate: '/rider/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","rider"] as Role[], permissions: ["riderProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const riders = {
  /**
   * Create a rider profile
   *
   * `POST /riders`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: riderProfile:create
   * Ownership: none
   */
  create(body: RiderInput, options?: RequestOptions): Promise<Rider> {
    return client().post<Rider>('/riders', body, withMeta(options, META.create));
  },

  /**
   * Archive a rider profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /rider/{riderId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: riderProfile:delete
   * Ownership: none
   */
  delete(riderId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/rider/${seg(riderId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one rider profile
   *
   * `GET /rider/{riderId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: riderProfile:read | riderProfile:readOwn
   * Ownership: scoped
   */
  getById(riderId: string, options?: RequestOptions): Promise<Rider> {
    return client().get<Rider>(`/rider/${seg(riderId)}`, withMeta(options, META.getById));
  },

  /**
   * List rider profiles
   *
   * `GET /riders`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: riderProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Rider>> {
    return client().list<Rider>('/riders', withMeta(options, META.list));
  },

  /**
   * Read the caller's own rider profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /rider/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, driver, rider
   * Permission: riderProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Rider> {
    return client().get<Rider>('/rider/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived rider profile
   *
   * `POST /rider/{riderId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: riderProfile:update
   * Ownership: none
   */
  restore(riderId: string, options?: RequestOptions): Promise<Rider> {
    return client().post<Rider>(`/rider/${seg(riderId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one rider profile
   *
   * `PATCH /rider/{riderId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: riderProfile:update | riderProfile:updateOwn
   * Ownership: scoped
   */
  update(riderId: string, body: RiderInput, options?: RequestOptions): Promise<Rider> {
    return client().patch<Rider>(`/rider/${seg(riderId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own rider profile
   *
   * `PATCH /rider/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, rider
   * Permission: riderProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: RiderInput, options?: RequestOptions): Promise<Rider> {
    return client().patch<Rider>('/rider/me', body, withMeta(options, META.updateMe));
  },
};

export type RidersApi = typeof riders;
