/**
 * `security` — 3 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  AnomalyFeed,
  ErrorReceipt,
  ErrorReport,
  ErrorReportRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  anomalies: { operationId: 'getSecurityAnomalies', method: 'GET' as const, pathTemplate: '/security/anomalies', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["auditLog:read","analytics:read"], ownership: 'none' as const, auth: 'required' as const },
  capture: { operationId: 'postSecurityErrors', method: 'POST' as const, pathTemplate: '/security/errors', zone: 'PUBLIC_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","seller","customer","buyer","publicUser"] as Role[], permissions: [], ownership: 'none' as const, auth: 'optional' as const },
  recent: { operationId: 'getSecurityErrors', method: 'GET' as const, pathTemplate: '/security/errors', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["auditLog:read","analytics:read"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const security = {
  /**
   * The anomaly feed
   * 
   * Read-only, and the only way to see the pipeline. Counts are held IN MEMORY PER PROCESS: with two C4 servers a threshold is effectively halved per node, so the signals are conservative — the failure direction is a missed alert, never a false one. That is said in the reply itself so a reader comparing against a log knows why the numbers are low rather than concluding the pipeline is broken. The ceiling is `escalate`; nothing here locks, blocks or throttles anybody.
   *
   * `GET /security/anomalies`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: auditLog:read | analytics:read
   * Ownership: none
   */
  anomalies(options?: RequestOptions): Promise<AnomalyFeed> {
    return client().get<AnomalyFeed>('/security/anomalies', withMeta(options, META.anomalies));
  },

  /**
   * A browser reporting that something went wrong
   * 
   * UNAUTHENTICATED ON PURPOSE. The most valuable report is the one from a page that broke before the member could sign in, and requiring a token would discard exactly those. NOTHING ON THIS ROUTE CAN ACT AGAINST A MEMBER — no block, no lock, no throttle that removes the application. Past a per-browser storage bound the report is dropped and the session is entirely unaffected; the reply is still 201, because telling a client it is being dropped invites a retry and a page in a render loop needs no encouragement. The reply carries nothing about the outcome: an intake that echoed its own grading would be a way to discover the thresholds. `severity` is derived from `kind` and cannot be supplied — a client that could set it could page a coordinator at will. URLs are reduced to path templates and every free-text field is redacted before storage, because an error log that quietly becomes a second copy of the tenant database is what every naive implementation produces.
   *
   * `POST /security/errors`
   * Zone: PUBLIC_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, seller, customer, buyer, publicUser
   * Ownership: none
   */
  capture(body: ErrorReportRequest, options?: RequestOptions): Promise<ErrorReceipt> {
    return client().post<ErrorReceipt>('/security/errors', body, withMeta(options, META.capture));
  },

  /**
   * What is breaking for members lately
   * 
   * Append-only: there is no update route and no delete route, because an error log somebody can edit is one nobody can rely on and the first thing anybody wants to do with an embarrassing entry is tidy it away. Rows expire after 90 days by TTL index — a retention decision, not a storage one, since these carry fragments of what members were doing. Each row carries a plain-English summary computed on read rather than stored, so a change to the wording reaches old rows.
   *
   * `GET /security/errors`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: auditLog:read | analytics:read
   * Ownership: none
   */
  recent(options?: RequestOptions): Promise<ErrorReport[]> {
    return client().get<ErrorReport[]>('/security/errors', withMeta(options, META.recent));
  },
};

export type SecurityApi = typeof security;
