/**
 * `staff` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  BackOfficeStaff,
  BackOfficeStaffInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postStaffMembers', method: 'POST' as const, pathTemplate: '/staff-members', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteStaffMemberByStaffId', method: 'DELETE' as const, pathTemplate: '/staff-member/{staffId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getStaffMemberByStaffId', method: 'GET' as const, pathTemplate: '/staff-member/{staffId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:read","backOfficeStaffProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getStaffMembers', method: 'GET' as const, pathTemplate: '/staff-members', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getStaffMemberMe', method: 'GET' as const, pathTemplate: '/staff-member/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postStaffMemberByStaffIdRestore', method: 'POST' as const, pathTemplate: '/staff-member/{staffId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchStaffMemberByStaffId', method: 'PATCH' as const, pathTemplate: '/staff-member/{staffId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:update","backOfficeStaffProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchStaffMemberMe', method: 'PATCH' as const, pathTemplate: '/staff-member/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchStaffMemberByStaffIdVerify', method: 'PATCH' as const, pathTemplate: '/staff-member/{staffId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["backOfficeStaffProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const staff = {
  /**
   * Create a back office staff profile
   *
   * `POST /staff-members`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: backOfficeStaffProfile:create
   * Ownership: none
   */
  create(body: BackOfficeStaffInput, options?: RequestOptions): Promise<BackOfficeStaff> {
    return client().post<BackOfficeStaff>('/staff-members', body, withMeta(options, META.create));
  },

  /**
   * Archive a back office staff profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /staff-member/{staffId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: backOfficeStaffProfile:delete
   * Ownership: none
   */
  delete(staffId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/staff-member/${seg(staffId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one back office staff profile
   *
   * `GET /staff-member/{staffId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: backOfficeStaffProfile:read | backOfficeStaffProfile:readOwn
   * Ownership: scoped
   */
  getById(staffId: string, options?: RequestOptions): Promise<BackOfficeStaff> {
    return client().get<BackOfficeStaff>(`/staff-member/${seg(staffId)}`, withMeta(options, META.getById));
  },

  /**
   * List back office staff profiles
   *
   * `GET /staff-members`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: backOfficeStaffProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<BackOfficeStaff>> {
    return client().list<BackOfficeStaff>('/staff-members', withMeta(options, META.list));
  },

  /**
   * Read the caller's own back office staff profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /staff-member/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: backOfficeStaffProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<BackOfficeStaff> {
    return client().get<BackOfficeStaff>('/staff-member/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived back office staff profile
   *
   * `POST /staff-member/{staffId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: backOfficeStaffProfile:update
   * Ownership: none
   */
  restore(staffId: string, options?: RequestOptions): Promise<BackOfficeStaff> {
    return client().post<BackOfficeStaff>(`/staff-member/${seg(staffId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one back office staff profile
   *
   * `PATCH /staff-member/{staffId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: backOfficeStaffProfile:update | backOfficeStaffProfile:updateOwn
   * Ownership: scoped
   */
  update(staffId: string, body: BackOfficeStaffInput, options?: RequestOptions): Promise<BackOfficeStaff> {
    return client().patch<BackOfficeStaff>(`/staff-member/${seg(staffId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own back office staff profile
   *
   * `PATCH /staff-member/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff
   * Permission: backOfficeStaffProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: BackOfficeStaffInput, options?: RequestOptions): Promise<BackOfficeStaff> {
    return client().patch<BackOfficeStaff>('/staff-member/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a back office staff profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /staff-member/{staffId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: backOfficeStaffProfile:verify
   * Ownership: none
   */
  verify(staffId: string, body: VerificationRequest, options?: RequestOptions): Promise<BackOfficeStaff> {
    return client().patch<BackOfficeStaff>(`/staff-member/${seg(staffId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type StaffApi = typeof staff;
