/**
 * `stats` — 5 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  ApplicationStats,
  MaintenanceStats,
  PaymentStats,
  PropertyStats,
  UsusuStats,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  applications: { operationId: 'getStatsApplications', method: 'GET' as const, pathTemplate: '/stats/applications', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["analytics:read","application:readOwn","application:read"], ownership: 'scoped' as const, auth: 'required' as const },
  maintenance: { operationId: 'getStatsMaintenance', method: 'GET' as const, pathTemplate: '/stats/maintenance', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["analytics:read","maintenanceRequest:readOwn","maintenanceRequest:read"], ownership: 'scoped' as const, auth: 'required' as const },
  payments: { operationId: 'getStatsPayments', method: 'GET' as const, pathTemplate: '/stats/payments', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager","rentalCarCompany","driver","rider","advertiser","merchant","customer"] as Role[], permissions: ["analytics:read","payment:readOwn","payment:read"], ownership: 'scoped' as const, auth: 'required' as const },
  properties: { operationId: 'getStatsProperties', method: 'GET' as const, pathTemplate: '/stats/properties', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","tenant","airbnbHost","hotelManager","resortManager"] as Role[], permissions: ["analytics:read","property:readOwn","property:read"], ownership: 'scoped' as const, auth: 'required' as const },
  ususu: { operationId: 'getStatsUsusu', method: 'GET' as const, pathTemplate: '/stats/ususu', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["analytics:read","ususuLedger:readOwn","ususuLedger:read"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const stats = {
  /**
   * Tenancy application counts by stage
   * 
   * A landlord sees applications on their own properties.
   *
   * `GET /stats/applications`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: analytics:read | application:readOwn | application:read
   * Ownership: scoped
   */
  applications(options?: RequestOptions): Promise<ApplicationStats> {
    return client().get<ApplicationStats>('/stats/applications', withMeta(options, META.applications));
  },

  /**
   * Maintenance counts by stage
   * 
   * Ten statuses into four buckets, and `stalled` is reported rather than hidden so the buckets sum to the total.
   *
   * `GET /stats/maintenance`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: analytics:read | maintenanceRequest:readOwn | maintenanceRequest:read
   * Ownership: scoped
   */
  maintenance(options?: RequestOptions): Promise<MaintenanceStats> {
    return client().get<MaintenanceStats>('/stats/maintenance', withMeta(options, META.maintenance));
  },

  /**
   * Payment counts and reliability
   * 
   * Reliability is of *settled* instalments; dividing by every row would drag it down each time one fell due. `succeeded` is the ledger’s word for settled — `paid` belongs to the marketplace order lifecycle.
   *
   * `GET /stats/payments`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager, rentalCarCompany, driver, rider, advertiser, merchant, customer
   * Permission: analytics:read | payment:readOwn | payment:read
   * Ownership: scoped
   */
  payments(options?: RequestOptions): Promise<PaymentStats> {
    return client().get<PaymentStats>('/stats/payments', withMeta(options, META.payments));
  },

  /**
   * Portfolio counts, computed by the database
   * 
   * Scoped to the caller from the token, never from a parameter: a landlord gets their own portfolio, a coordinator their region, Back Office everything. Occupancy is of lettable properties — an off-market unit is not a vacancy.
   *
   * `GET /stats/properties`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, tenant, airbnbHost, hotelManager, resortManager
   * Permission: analytics:read | property:readOwn | property:read
   * Ownership: scoped
   */
  properties(options?: RequestOptions): Promise<PropertyStats> {
    return client().get<PropertyStats>('/stats/properties', withMeta(options, META.properties));
  },

  /**
   * Ususu ledger totals and average group health
   * 
   * Reports `totalMembers`, not `totalGroups`: the ledger records contributions per person and there is no group entity to count.
   *
   * `GET /stats/ususu`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, tenant
   * Permission: analytics:read | ususuLedger:readOwn | ususuLedger:read
   * Ownership: scoped
   */
  ususu(options?: RequestOptions): Promise<UsusuStats> {
    return client().get<UsusuStats>('/stats/ususu', withMeta(options, META.ususu));
  },
};

export type StatsApi = typeof stats;
