/**
 * `tenants` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Tenant,
  TenantInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postTenants', method: 'POST' as const, pathTemplate: '/tenants', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["tenantProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteTenantByTenantId', method: 'DELETE' as const, pathTemplate: '/tenant/{tenantId}', zone: 'BACK_OFFICE' as const, roles: ["founder"] as Role[], permissions: ["tenantProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getTenantByTenantId', method: 'GET' as const, pathTemplate: '/tenant/{tenantId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["tenantProfile:read","tenantProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getTenants', method: 'GET' as const, pathTemplate: '/tenants', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["tenantProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getTenantMe', method: 'GET' as const, pathTemplate: '/tenant/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["tenantProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postTenantByTenantIdRestore', method: 'POST' as const, pathTemplate: '/tenant/{tenantId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["tenantProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchTenantByTenantId', method: 'PATCH' as const, pathTemplate: '/tenant/{tenantId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["tenantProfile:update","tenantProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchTenantMe', method: 'PATCH' as const, pathTemplate: '/tenant/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","tenant"] as Role[], permissions: ["tenantProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchTenantByTenantIdVerify', method: 'PATCH' as const, pathTemplate: '/tenant/{tenantId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["tenantProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const tenants = {
  /**
   * Create a tenant profile
   *
   * `POST /tenants`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: tenantProfile:create
   * Ownership: none
   */
  create(body: TenantInput, options?: RequestOptions): Promise<Tenant> {
    return client().post<Tenant>('/tenants', body, withMeta(options, META.create));
  },

  /**
   * Archive a tenant profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /tenant/{tenantId}`
   * Zone: BACK_OFFICE
   * Roles: founder
   * Permission: tenantProfile:delete
   * Ownership: none
   */
  delete(tenantId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/tenant/${seg(tenantId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one tenant profile
   *
   * `GET /tenant/{tenantId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: tenantProfile:read | tenantProfile:readOwn
   * Ownership: scoped
   */
  getById(tenantId: string, options?: RequestOptions): Promise<Tenant> {
    return client().get<Tenant>(`/tenant/${seg(tenantId)}`, withMeta(options, META.getById));
  },

  /**
   * List tenant profiles
   *
   * `GET /tenants`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: tenantProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Tenant>> {
    return client().list<Tenant>('/tenants', withMeta(options, META.list));
  },

  /**
   * Read the caller's own tenant profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /tenant/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, landlord, tenant
   * Permission: tenantProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Tenant> {
    return client().get<Tenant>('/tenant/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived tenant profile
   *
   * `POST /tenant/{tenantId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: tenantProfile:update
   * Ownership: none
   */
  restore(tenantId: string, options?: RequestOptions): Promise<Tenant> {
    return client().post<Tenant>(`/tenant/${seg(tenantId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one tenant profile
   *
   * `PATCH /tenant/{tenantId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: tenantProfile:update | tenantProfile:updateOwn
   * Ownership: scoped
   */
  update(tenantId: string, body: TenantInput, options?: RequestOptions): Promise<Tenant> {
    return client().patch<Tenant>(`/tenant/${seg(tenantId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own tenant profile
   *
   * `PATCH /tenant/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, tenant
   * Permission: tenantProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: TenantInput, options?: RequestOptions): Promise<Tenant> {
    return client().patch<Tenant>('/tenant/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a tenant profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /tenant/{tenantId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: tenantProfile:verify
   * Ownership: none
   */
  verify(tenantId: string, body: VerificationRequest, options?: RequestOptions): Promise<Tenant> {
    return client().patch<Tenant>(`/tenant/${seg(tenantId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type TenantsApi = typeof tenants;
