/**
 * `vendors` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  Vendor,
  VendorInput,
  VerificationRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  create: { operationId: 'postVendors', method: 'POST' as const, pathTemplate: '/vendors', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["vendorProfile:create"], ownership: 'none' as const, auth: 'required' as const },
  delete: { operationId: 'deleteVendorByVendorId', method: 'DELETE' as const, pathTemplate: '/vendor/{vendorId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["vendorProfile:delete"], ownership: 'none' as const, auth: 'required' as const },
  getById: { operationId: 'getVendorByVendorId', method: 'GET' as const, pathTemplate: '/vendor/{vendorId}', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["vendorProfile:read","vendorProfile:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getVendors', method: 'GET' as const, pathTemplate: '/vendors', zone: 'BACK_OFFICE' as const, roles: ["founder","hqExecutive","backOfficeStaff"] as Role[], permissions: ["vendorProfile:read"], ownership: 'scoped' as const, auth: 'required' as const },
  me: { operationId: 'getVendorMe', method: 'GET' as const, pathTemplate: '/vendor/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","hqExecutive","backOfficeStaff","coordinator","vendor","landlord","airbnbHost","hotelManager","resortManager","rentalCarCompany"] as Role[], permissions: ["vendorProfile:readOwn"], ownership: 'self' as const, auth: 'required' as const },
  restore: { operationId: 'postVendorByVendorIdRestore', method: 'POST' as const, pathTemplate: '/vendor/{vendorId}/restore', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["vendorProfile:update"], ownership: 'none' as const, auth: 'required' as const },
  update: { operationId: 'patchVendorByVendorId', method: 'PATCH' as const, pathTemplate: '/vendor/{vendorId}', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["vendorProfile:update","vendorProfile:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  updateMe: { operationId: 'patchVendorMe', method: 'PATCH' as const, pathTemplate: '/vendor/me', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","vendor"] as Role[], permissions: ["vendorProfile:updateOwn"], ownership: 'self' as const, auth: 'required' as const },
  verify: { operationId: 'patchVendorByVendorIdVerify', method: 'PATCH' as const, pathTemplate: '/vendor/{vendorId}/verify', zone: 'BACK_OFFICE' as const, roles: ["founder","backOfficeStaff"] as Role[], permissions: ["vendorProfile:verify"], ownership: 'none' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const vendors = {
  /**
   * Create a vendor profile
   *
   * `POST /vendors`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: vendorProfile:create
   * Ownership: none
   */
  create(body: VendorInput, options?: RequestOptions): Promise<Vendor> {
    return client().post<Vendor>('/vendors', body, withMeta(options, META.create));
  },

  /**
   * Archive a vendor profile (soft delete)
   * 
   * Sets deletedAt and status=archived. Nothing is removed from the collection.
   *
   * `DELETE /vendor/{vendorId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: vendorProfile:delete
   * Ownership: none
   */
  delete(vendorId: string, options?: RequestOptions): Promise<void> {
    return client().delete<void>(`/vendor/${seg(vendorId)}`, withMeta(options, META.delete));
  },

  /**
   * Read one vendor profile
   *
   * `GET /vendor/{vendorId}`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: vendorProfile:read | vendorProfile:readOwn
   * Ownership: scoped
   */
  getById(vendorId: string, options?: RequestOptions): Promise<Vendor> {
    return client().get<Vendor>(`/vendor/${seg(vendorId)}`, withMeta(options, META.getById));
  },

  /**
   * List vendor profiles
   *
   * `GET /vendors`
   * Zone: BACK_OFFICE
   * Roles: founder, hqExecutive, backOfficeStaff
   * Permission: vendorProfile:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Vendor>> {
    return client().list<Vendor>('/vendors', withMeta(options, META.list));
  },

  /**
   * Read the caller's own vendor profile
   * 
   * Record resolved from the token, never from the URL. Declared before the `:id` route — otherwise Express parses `me` as an id.
   *
   * `GET /vendor/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, hqExecutive, backOfficeStaff, coordinator, vendor, landlord, airbnbHost, hotelManager, resortManager, rentalCarCompany
   * Permission: vendorProfile:readOwn
   * Ownership: self
   */
  me(options?: RequestOptions): Promise<Vendor> {
    return client().get<Vendor>('/vendor/me', withMeta(options, META.me));
  },

  /**
   * Restore an archived vendor profile
   *
   * `POST /vendor/{vendorId}/restore`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: vendorProfile:update
   * Ownership: none
   */
  restore(vendorId: string, options?: RequestOptions): Promise<Vendor> {
    return client().post<Vendor>(`/vendor/${seg(vendorId)}/restore`, undefined, withMeta(options, META.restore));
  },

  /**
   * Update one vendor profile
   *
   * `PATCH /vendor/{vendorId}`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: vendorProfile:update | vendorProfile:updateOwn
   * Ownership: scoped
   */
  update(vendorId: string, body: VendorInput, options?: RequestOptions): Promise<Vendor> {
    return client().patch<Vendor>(`/vendor/${seg(vendorId)}`, body, withMeta(options, META.update));
  },

  /**
   * Update the caller's own vendor profile
   *
   * `PATCH /vendor/me`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, vendor
   * Permission: vendorProfile:updateOwn
   * Ownership: self
   */
  updateMe(body: VendorInput, options?: RequestOptions): Promise<Vendor> {
    return client().patch<Vendor>('/vendor/me', body, withMeta(options, META.updateMe));
  },

  /**
   * Advance verification on a vendor profile
   * 
   * Back Office act. `verified` stamps verifiedAt/verifiedBy; `rejected` requires a note.
   *
   * `PATCH /vendor/{vendorId}/verify`
   * Zone: BACK_OFFICE
   * Roles: founder, backOfficeStaff
   * Permission: vendorProfile:verify
   * Ownership: none
   */
  verify(vendorId: string, body: VerificationRequest, options?: RequestOptions): Promise<Vendor> {
    return client().patch<Vendor>(`/vendor/${seg(vendorId)}/verify`, body, withMeta(options, META.verify));
  },
};

export type VendorsApi = typeof vendors;
