/**
 * `viewing` — 9 operations.
 *
 * GENERATED by `npm run generate` from backend/docs/openapi.json.
 * Do not edit — change the API, regenerate.
 */

import { seg } from '../client/ApiClient.js';
import type { OperationMeta } from '../client/types.js';
import type { Page } from '../types/pagination.js';
import type { Role } from '../types/roles.js';
import type {
  RequestViewingRequest,
  UpdateViewingRequest,
  Viewing,
  ViewingDecisionRequest,
  ViewingOutcomeRequest,
} from '../types/index.js';
import { client, withMeta, type ListOptions, type RequestOptions } from './_runtime.js';

/** Zone, roles and permissions for each operation, straight from the spec. */
export const META = {
  cancel: { operationId: 'postViewingByViewingIdCancel', method: 'POST' as const, pathTemplate: '/viewing/{viewingId}/cancel', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["viewing:readOwn"], ownership: 'scoped' as const, auth: 'required' as const },
  complete: { operationId: 'postViewingByViewingIdComplete', method: 'POST' as const, pathTemplate: '/viewing/{viewingId}/complete', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["viewing:update"], ownership: 'scoped' as const, auth: 'required' as const },
  confirm: { operationId: 'postViewingByViewingIdConfirm', method: 'POST' as const, pathTemplate: '/viewing/{viewingId}/confirm', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["viewing:approve"], ownership: 'scoped' as const, auth: 'required' as const },
  create: { operationId: 'postViewings', method: 'POST' as const, pathTemplate: '/viewings', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","tenant"] as Role[], permissions: ["viewing:create"], ownership: 'none' as const, auth: 'required' as const },
  decline: { operationId: 'postViewingByViewingIdDecline', method: 'POST' as const, pathTemplate: '/viewing/{viewingId}/decline', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["viewing:approve"], ownership: 'scoped' as const, auth: 'required' as const },
  getById: { operationId: 'getViewingByViewingId', method: 'GET' as const, pathTemplate: '/viewing/{viewingId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["viewing:readOwn","viewing:read"], ownership: 'scoped' as const, auth: 'required' as const },
  list: { operationId: 'getViewings', method: 'GET' as const, pathTemplate: '/viewings', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","landlord","tenant"] as Role[], permissions: ["viewing:readOwn","viewing:read"], ownership: 'scoped' as const, auth: 'required' as const },
  noShow: { operationId: 'postViewingByViewingIdNoShow', method: 'POST' as const, pathTemplate: '/viewing/{viewingId}/no-show', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator"] as Role[], permissions: ["viewing:update"], ownership: 'scoped' as const, auth: 'required' as const },
  update: { operationId: 'patchViewingByViewingId', method: 'PATCH' as const, pathTemplate: '/viewing/{viewingId}', zone: 'MEMBER_PORTAL' as const, roles: ["founder","backOfficeStaff","coordinator","tenant"] as Role[], permissions: ["viewing:updateOwn"], ownership: 'scoped' as const, auth: 'required' as const },
} satisfies Record<string, OperationMeta>;

export const viewing = {
  /**
   * Call off your own viewing
   * 
   * No permission gate: `viewingRules.mayAct` is what stops a landlord cancelling on a tenant’s behalf, which would leave a record reading as though the tenant lost interest.
   *
   * `POST /viewing/{viewingId}/cancel`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord, tenant
   * Permission: viewing:readOwn
   * Ownership: scoped
   */
  cancel(viewingId: string, body: ViewingDecisionRequest, options?: RequestOptions): Promise<Viewing> {
    return client().post<Viewing>(`/viewing/${seg(viewingId)}/cancel`, body, withMeta(options, META.cancel));
  },

  /**
   * Record that the viewing happened
   * 
   * Refused before the slot has passed. An outcome recorded early is a prediction.
   *
   * `POST /viewing/{viewingId}/complete`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: viewing:update
   * Ownership: scoped
   */
  complete(viewingId: string, body: ViewingOutcomeRequest, options?: RequestOptions): Promise<Viewing> {
    return client().post<Viewing>(`/viewing/${seg(viewingId)}/complete`, body, withMeta(options, META.complete));
  },

  /**
   * Agree to be there
   *
   * `POST /viewing/{viewingId}/confirm`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: viewing:approve
   * Ownership: scoped
   */
  confirm(viewingId: string, body: ViewingDecisionRequest, options?: RequestOptions): Promise<Viewing> {
    return client().post<Viewing>(`/viewing/${seg(viewingId)}/confirm`, body, withMeta(options, META.confirm));
  },

  /**
   * Ask to view a property
   * 
   * Refuses a slot outside viewing hours, inside the notice window, or beyond the booking horizon — see `viewingRules.slotProblem`. Also refuses a second live request on the same property.
   *
   * `POST /viewings`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, tenant
   * Permission: viewing:create
   * Ownership: none
   */
  create(body: RequestViewingRequest, options?: RequestOptions): Promise<Viewing> {
    return client().post<Viewing>('/viewings', body, withMeta(options, META.create));
  },

  /**
   * Refuse a slot, with a reason
   *
   * `POST /viewing/{viewingId}/decline`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: viewing:approve
   * Ownership: scoped
   */
  decline(viewingId: string, body: ViewingDecisionRequest, options?: RequestOptions): Promise<Viewing> {
    return client().post<Viewing>(`/viewing/${seg(viewingId)}/decline`, body, withMeta(options, META.decline));
  },

  /**
   * Read one viewing
   *
   * `GET /viewing/{viewingId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord, tenant
   * Permission: viewing:readOwn | viewing:read
   * Ownership: scoped
   */
  getById(viewingId: string, options?: RequestOptions): Promise<Viewing> {
    return client().get<Viewing>(`/viewing/${seg(viewingId)}`, withMeta(options, META.getById));
  },

  /**
   * List viewings you can see
   * 
   * A tenant sees their own, a landlord sees those on their properties, a coordinator sees their region, Back Office sees all.
   *
   * `GET /viewings`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, landlord, tenant
   * Permission: viewing:readOwn | viewing:read
   * Ownership: scoped
   */
  list(options?: ListOptions): Promise<Page<Viewing>> {
    return client().list<Viewing>('/viewings', withMeta(options, META.list));
  },

  /**
   * Record that the tenant did not come
   * 
   * Refused before the slot has passed, and it lands on a tenant’s record where it counts at application time.
   *
   * `POST /viewing/{viewingId}/no-show`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator
   * Permission: viewing:update
   * Ownership: scoped
   */
  noShow(viewingId: string, body: ViewingOutcomeRequest, options?: RequestOptions): Promise<Viewing> {
    return client().post<Viewing>(`/viewing/${seg(viewingId)}/no-show`, body, withMeta(options, META.noShow));
  },

  /**
   * Change the note on your own request
   * 
   * The tenant’s own words only. Status moves through the action routes.
   *
   * `PATCH /viewing/{viewingId}`
   * Zone: MEMBER_PORTAL
   * Roles: founder, backOfficeStaff, coordinator, tenant
   * Permission: viewing:updateOwn
   * Ownership: scoped
   */
  update(viewingId: string, body: UpdateViewingRequest, options?: RequestOptions): Promise<Viewing> {
    return client().patch<Viewing>(`/viewing/${seg(viewingId)}`, body, withMeta(options, META.update));
  },
};

export type ViewingApi = typeof viewing;
